export function computeLabResponse(): Response {
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OMEGA R170 Computation Truth Lab</title>
<style>
:root{color-scheme:dark;--bg:#090b0d;--panel:#11151a;--line:#2b323a;--text:#edf1f4;--muted:#9da7b1;--accent:#d5a84b;--ok:#83d0bd;--bad:#ef9c8e}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -15%,#20252b 0,#0b0e11 38%,var(--bg) 70%);font:14px/1.45 Inter,ui-sans-serif,system-ui,sans-serif;color:var(--text)}main{max-width:1280px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.eyebrow{letter-spacing:.16em;text-transform:uppercase;color:var(--accent);font-size:11px}.title{font-size:clamp(26px,4vw,52px);font-weight:650;line-height:1.02;margin:5px 0}.sub{max-width:880px;color:var(--muted)}.badge{border:1px solid var(--line);border-radius:999px;padding:8px 11px;white-space:nowrap;color:var(--ok)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px}.card{grid-column:span 6;background:linear-gradient(180deg,rgba(20,25,30,.96),rgba(12,15,18,.96));border:1px solid var(--line);border-radius:16px;padding:16px;min-width:0}.wide{grid-column:1/-1}.card h2{font-size:15px;margin:0 0 4px}.desc{color:var(--muted);font-size:12px;margin-bottom:12px}.inputs{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.inputs.two{grid-template-columns:repeat(2,1fr)}label{display:grid;gap:4px;color:var(--muted);font-size:11px}input,textarea,button{font:inherit}input,textarea{width:100%;background:#090c0f;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px}textarea{min-height:72px;resize:vertical}button{border:1px solid #605233;background:#1d1a13;color:#f7e4b5;border-radius:9px;padding:9px 12px;cursor:pointer}button:hover{background:#292215}.actions{display:flex;gap:8px;align-items:center;margin:10px 0}.result{white-space:pre-wrap;overflow:auto;background:#080a0c;border:1px solid var(--line);border-radius:10px;padding:10px;min-height:104px;max-height:280px;font:12px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace}.metric{display:grid;grid-template-columns:1fr auto;gap:10px;padding:5px 0;border-bottom:1px solid #1d2329}.metric:last-child{border-bottom:0}.metric span:first-child{color:var(--muted)}canvas{width:100%;height:180px;background:#080a0c;border:1px solid var(--line);border-radius:10px}.truth{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.truth div{border:1px solid var(--line);border-radius:10px;padding:10px}.truth strong{display:block;font-size:16px}.truth small{color:var(--muted)}@media(max-width:850px){main{padding:14px}.top{display:block}.badge{display:inline-block;margin-top:12px}.card{grid-column:1/-1}.inputs,.inputs.two,.truth{grid-template-columns:1fr 1fr}}@media(max-width:520px){.inputs,.inputs.two,.truth{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><div><div class="eyebrow">OMEGA · R170 · computation truth</div><div class="title">Reference computation you can inspect.</div><div class="sub">Every panel calls the live Worker. Outputs are derived from explicit equations and carry numerical residuals. Nothing on this surface is promoted to empirical measurement, full-wave optical validation, native PC execution, or CanonState unless separately proven.</div></div><div class="badge" id="status">loading manifest…</div></div>
<div class="grid">
<section class="card wide"><h2>Truth boundary</h2><div class="desc">Address hierarchy is computational resolution; physical equations declare their own units and validity.</div><div class="truth" id="truth"></div></section>
<section class="card"><h2>Special relativity · 3D Lorentz event</h2><div class="desc">General Lorentz boost in SI units. Accuracy is checked by the Minkowski interval residual.</div><div class="inputs"><label>t (s)<input id="lt" value="1.25"></label><label>x (m)<input id="lx" value="120000000"></label><label>y (m)<input id="ly" value="-25000000"></label><label>z (m)<input id="lz" value="4000000"></label><label>vx (m/s)<input id="lvx" value="40000000"></label><label>vy (m/s)<input id="lvy" value="-20000000"></label><label>vz (m/s)<input id="lvz" value="10000000"></label></div><div class="actions"><button onclick="runLorentz()">Compute boost</button><span id="lstate"></span></div><div class="result" id="lout">waiting</div></section>
<section class="card"><h2>Optics · multilayer transfer matrix</h2><div class="desc">Coherent normal-incidence 1D layered-media solver. It is intentionally not labeled RCWA/FDTD/FEM.</div><div class="inputs"><label>λ (nm)<input id="owl" value="550"></label><label>incident n<input id="on0" value="1"></label><label>substrate n<input id="ons" value="1.5"></label><label>layer n<input id="on" value="1.22474487139"></label><label>layer k<input id="ok" value="0"></label><label>thickness (nm)<input id="od" value="112.268279878"></label></div><div class="actions"><button onclick="runOptics()">Solve stack</button><span id="ostate"></span></div><div class="result" id="oout">waiting</div></section>
<section class="card"><h2>Woven continuity · conservative transfer</h2><div class="desc">Actual redistribution with a conserved scalar sum. The residual exposes numerical drift instead of hiding it.</div><label>values<textarea id="cvalues">[4,3,2,1]</textarea></label><label>transfers<textarea id="ctransfers">[{"from":0,"to":1,"amount":1.25},{"from":1,"to":2,"amount":0.5},{"from":2,"to":3,"amount":0.25}]</textarea></label><div class="actions"><button onclick="runContinuity()">Apply transfer</button><span id="cstate"></span></div><div class="result" id="cout">waiting</div></section>
<section class="card"><h2>Scalar wave · FDTD 1D</h2><div class="desc">Second-order finite-difference solution of uₜₜ=c²uₓₓ with explicit CFL enforcement. The graph below is returned solver state, not decorative animation.</div><div class="inputs"><label>grid points<input id="wn" value="161"></label><label>steps<input id="wsteps" value="180"></label><label>CFL<input id="wcfl" value="0.7"></label></div><div class="actions"><button onclick="runWave()">Propagate wave</button><span id="wstate"></span></div><canvas id="wave"></canvas><div class="result" id="wout">waiting</div></section>
</div></main><script>
const $=id=>document.getElementById(id);const n=id=>Number($(id).value);const pretty=x=>JSON.stringify(x,null,2);async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||j.code||('HTTP '+r.status));return j}function state(id,msg,ok=true){$(id).textContent=msg;$(id).style.color=ok?'var(--ok)':'var(--bad)'}
async function loadManifest(){try{const j=await api('/api/compute/manifest');$('status').textContent='live · '+j.revision;$('truth').innerHTML='<div><small>speed of light</small><strong>'+j.constants.c_m_s.toLocaleString()+' m/s</strong></div><div><small>address levels</small><strong>'+j.hierarchy.addressLevels.join(' → ')+'</strong></div><div><small>physical dimension claim</small><strong>'+j.hierarchy.physicalDimensionClaim+'</strong></div><div><small>canonical mutation</small><strong>'+j.canonicalMutation+'</strong></div>'}catch(e){$('status').textContent='manifest failed';$('status').style.color='var(--bad)'}}
async function runLorentz(){state('lstate','running…');try{const j=await api('/api/compute/relativity/event',{t_seconds:n('lt'),position_m:[n('lx'),n('ly'),n('lz')],frame_velocity_m_s:[n('lvx'),n('lvy'),n('lvz')]});const r=j.result;$('lout').textContent=pretty({gamma:r.gamma,transformed_t_seconds:r.transformed_t_seconds,transformed_position_m:r.transformed_position_m,interval_before_m2:r.interval_before_m2,interval_after_m2:r.interval_after_m2,invariant_relative_residual:r.invariant_relative_residual,receipt:j.receipt.receiptSha256});state('lstate','derived · residual '+r.invariant_relative_residual.toExponential(3))}catch(e){state('lstate',e.message,false)}}
async function runOptics(){state('ostate','running…');try{const j=await api('/api/compute/optics/tmm',{wavelength_nm:n('owl'),incident_n:n('on0'),substrate_n:n('ons'),layers:[{n:n('on'),k:n('ok'),thickness_nm:n('od')}]});const r=j.result;$('oout').textContent=pretty({R:r.reflectance,T:r.transmittance,A:r.absorptance,energy_balance:r.energy_balance,energy_balance_residual:r.energy_balance_residual,solver:r.solver,solverTier:r.solverTier,fabricationGrade:r.fabricationGrade,receipt:j.receipt.receiptSha256});state('ostate','derived · balance residual '+r.energy_balance_residual.toExponential(3))}catch(e){state('ostate',e.message,false)}}
async function runContinuity(){state('cstate','running…');try{const j=await api('/api/compute/continuity/transfer',{values:JSON.parse($('cvalues').value),transfers:JSON.parse($('ctransfers').value)});const r=j.result;$('cout').textContent=pretty({values_after:r.values_after,invariant_before:r.invariant_before,invariant_after:r.invariant_after,invariant_absolute_residual:r.invariant_absolute_residual,receipt:j.receipt.receiptSha256});state('cstate','derived · invariant residual '+r.invariant_absolute_residual.toExponential(3))}catch(e){state('cstate',e.message,false)}}
function drawWave(values){const c=$('wave'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle='#343c45';x.beginPath();x.moveTo(0,h/2);x.lineTo(w,h/2);x.stroke();const m=Math.max(1e-12,...values.map(Math.abs));x.strokeStyle='#d5a84b';x.lineWidth=1.5;x.beginPath();values.forEach((v,i)=>{const px=i/(values.length-1)*w,py=h/2-v/m*h*.42;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
async function runWave(){state('wstate','running…');try{const count=Math.max(3,Math.min(4096,Math.trunc(n('wn')))),arr=Array(count).fill(0),mid=(count-1)/2,sigma=count/18;for(let i=0;i<count;i++)arr[i]=Math.exp(-.5*((i-mid)/sigma)**2);const cfl=n('wcfl'),j=await api('/api/compute/wave/fdtd1d',{initial_displacement:arr,wave_speed:1,dx:1,dt:cfl,steps:Math.trunc(n('wsteps')),snapshot_stride:0});const r=j.result;drawWave(r.final_state);$('wout').textContent=pretty({grid_points:r.final_state.length,steps:r.steps,cfl:r.cfl,max_abs_amplitude:r.max_abs_amplitude,solver:r.solver,maxwellSolver:r.maxwellSolver,receipt:j.receipt.receiptSha256});state('wstate','derived · CFL '+r.cfl.toFixed(4))}catch(e){state('wstate',e.message,false)}}
loadManifest();runLorentz();runOptics();runContinuity();runWave();
</script></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "x-omega-surface": "R170_COMPUTATION_TRUTH_LAB" } });
}
