import {MODES,BOUNDARY} from "./catalog.js";
export const clamp=(v,l=0,h=1)=>Math.max(l,Math.min(h,Number(v))), clean=n=>Number.isFinite(n)?n:null, pad=n=>String(n).padStart(12,"0");
function stable(v){if(Array.isArray(v))return`[${v.map(stable).join(",")}]`;if(v&&typeof v==="object")return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;return JSON.stringify(v)}
export async function hash(v){const b=new TextEncoder().encode(typeof v==="string"?v:stable(v)),d=await crypto.subtle.digest("SHA-256",b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export function idx(a){return(((a[0]-1)*12+(a[1]-1))*12+(a[2]-1))*12+(a[3]-1)}
export function addr(i){i=Math.max(0,Math.min(20735,Math.trunc(+i||0)));const l=i%12+1;i=Math.floor(i/12);const r=i%12+1;i=Math.floor(i/12);const p=i%12+1;i=Math.floor(i/12);return[i%12+1,p,r,l]}
export function validAddr(a){return Array.isArray(a)&&a.length===4&&a.every(x=>Number.isInteger(x)&&x>=1&&x<=12)}
export function validMetrics(m){return Object.values(m).every(x=>typeof x==="number"&&Number.isFinite(x))}
export function arc(s,t,p=1,n=12){const a=((+s-1)%n+n)%n,b=((+t-1)%n+n)%n,d=((b-a+n/2)%n+n)%n-n/2;return((a+d*clamp(p))%n+n)%n+1}
export function gate(m){const d=m.burden+m.contradiction+m.burden*m.contradiction,r=d<=0?(m.continuity>0?Infinity:0):m.continuity/d;return r>1.05?{ratio:clean(r),dispatch:"STAY",admission:"ACCEPT"}:r>=.95?{ratio:clean(r),dispatch:"TURN",admission:"CONDITIONAL"}:{ratio:clean(r),dispatch:"ESCALATE",admission:"PRUNE"}}
export function calc(m){const c=clamp(m.continuity),p=clamp(m.future_plasticity),b=clamp(m.burden),q=clamp(m.contradiction),s=clamp(m.stability),e=clamp(m.evidence_strength),x=clamp(m.scar),cap=c+.72*p+.58*s+.42*e+.18*x,load=b+q+b*q+.25*x*q,total=cap+load+1e-12;return{mode188:gate(m),dewey_balance:1-b,rsc:{capacity:cap,load,margin:cap-load,continuity_ratio:c/total,plasticity_ratio:p/total,burden_ratio:b/total,contradiction_ratio:q/total},deep_mother:clamp(.5+.5*((.34*c+.26*p+.22*s+.18*e)-(.58*b+.42*q))),high_father:clamp(.5+.5*((.55*s+.45*e)-(.62*q+.38*b))),deep_thought:c&&s&&e&&(1-q)?4/(1/c+1/s+1/e+1/(1-q)):0,water:clamp(c*(p+1e-12)/(1+b+q))}}
export function coh(m){return clamp(.28*clamp(m.continuity)+.18*clamp(m.future_plasticity)+.18*clamp(m.stability)+.18*clamp(m.evidence_strength)+.18*clamp(1-m.contradiction)-.18*clamp(m.burden))}
export async function digestState(s){const b={...s};delete b.digest;return{...b,digest:await hash(b)}}
export async function seed(){return digestState({schema_version:"omega-genesis-cloud-state-v1.1",address:[1,1,7,12],metrics:{continuity:1,future_plasticity:0,burden:0,contradiction:0,stability:1,scar:0,evidence_strength:1,water_conductance:0,triangulation:0,occupancy:0,proof_scar:0,normalized_mri:0},evidence_class:"DERIVED",motion:{phase:1,velocity:0,acceleration:0,jerk:0,heading_rad:0,face:1,antipode:7,transition_progress:0},sources:[],parent_digest:null,sequence:0,observer_id:"cloud-canonical",created_at:new Date().toISOString(),payload:{seed:"OMEGA_GENESIS_CLOUD"}})}
export async function proj(s){const c=calc(s.metrics),o={state_digest:s.digest,state_id:idx(s.address)+1,address:s.address,skin:"GENESIS",phase:s.motion.phase,transition_progress:s.motion.transition_progress,channels:{continuity:s.metrics.continuity,plasticity:s.metrics.future_plasticity,burden:s.metrics.burden,contradiction:s.metrics.contradiction,scar:s.metrics.scar,evidence:s.metrics.evidence_strength,water:c.water,proof_scar:s.metrics.proof_scar,normalized_mri:s.metrics.normalized_mri},derived:{torsion:clamp(s.metrics.contradiction),pressure:clamp((s.metrics.burden+s.metrics.contradiction)/2),route_strength:clamp((s.metrics.continuity+s.metrics.future_plasticity-s.metrics.burden+1)/3)},boundary:"projection only; renderer cannot rewrite canonical state or evidence class"};return{...o,packet_fingerprint:await hash(o)}}
export function forecast(s,h=1){const m=s.metrics,a=clamp((m.continuity+m.stability+1-m.burden+1-m.contradiction)/4),b=clamp(1-Math.abs(m.continuity-(m.burden+m.contradiction)/2)),c=clamp((m.burden+m.contradiction)/2),z=a+b+c||1;return{state_digest:s.digest,horizon:Math.max(1,+h||1),continuity:m.continuity,plasticity:m.future_plasticity,burden:m.burden,contradiction:m.contradiction,probability_stay:a/z,probability_turn:b/z,probability_escalate:c/z,future_observation_used:false,evidence_class:"FORECAST"}}
export function classify(n){if(/OMEGA_ONE_SYSTEM_FULL_SOFTWARE_MENU_LEDGER/i.test(n))return{disposition:"KEEP",authority:100,role:"CONTROL_LEDGER"};if(/OMEGA_ALL_SOFTWARE_61917364224D_FULL_BUILD/i.test(n))return{disposition:"KEEP",authority:98,role:"SOFTWARE_LEDGER"};if(/Math_Atlas_20736D_FullCanon_GraphEdges/i.test(n))return{disposition:"KEEP",authority:98,role:"ATLAS_GRAPH"};if(/HYBRID_LINK/i.test(n))return{disposition:"MERGE",authority:94,role:"HYBRID_LINK"};if(/CORRESPONDENCE_LEDGER|ACCEPTANCE|QA|VERIFY/i.test(n))return{disposition:"KEEP",authority:95,role:"PROOF_QA"};if(/PATCHED|FIXED|FIX\d|repair/i.test(n))return{disposition:"DONOR",authority:64,role:"REPAIR_DONOR"};return{disposition:"QUARANTINE",authority:0,role:"UNKNOWN"}}
export function mode(id,s){const c=calc(s.metrics),m=s.metrics;if(BOUNDARY.has(id))return{id,status:"BOUNDARY_ONLY",reason:"requires an external/host evidence adapter"};if(id==="MODE188")return c.mode188;if(id==="RSC")return c.rsc;if(id==="DEWEY_BAL")return{score:c.dewey_balance,burden:m.burden};if(id==="DEEP_MOTHER")return{score:c.deep_mother};if(id==="HIGH_FATHER")return{score:c.high_father};if(id==="DEEP_THOUGHT")return{score:c.deep_thought};if(id==="UNIFIED_COHERENCE")return{score:coh(m),contradiction_retained:clamp(m.contradiction)};if(id==="AUTOPING")return{reversible:true,state_id:idx(s.address)+1};if(id==="FORECAST")return forecast(s,1);return{id,status:"PASS",score:coh(m),state_digest:s.digest,evidence_class:s.evidence_class}}
export function orchestrate(s){const results={},boundary=[];for(const id of MODES){results[id]=mode(id,s);if(results[id].status==="BOUNDARY_ONLY")boundary.push(id)}results.ALL_MODES={registered:MODES.length,active_ids:MODES,canonical_digest:s.digest,mutation_authority:"OmegaGenesisState only"};return{canonical_digest:s.digest,state_id:idx(s.address)+1,registered:MODES.length,evaluated:MODES.length-boundary.length,boundary_only:boundary,mutation_authority:"OmegaGenesisState only",summary:{coherence:coh(s.metrics),dispatch:calc(s.metrics).mode188.dispatch,admission:calc(s.metrics).mode188.admission,evidence_class:s.evidence_class},results}}
const R=6371008.8,rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
export function dest(lat,lon,b,d){const p=rad(lat),l=rad(lon),q=d/R,s=Math.sin(p)*Math.cos(q)+Math.cos(p)*Math.sin(q)*Math.cos(b),p2=Math.asin(s),l2=l+Math.atan2(Math.sin(b)*Math.sin(q)*Math.cos(p),Math.cos(q)-Math.sin(p)*Math.sin(p2));return{lat:deg(p2),lon:((deg(l2)+540)%360)-180}}
export function hav(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(x)))}
