import { hash } from "./kernel.js";

export const LINK_ACTIONS=new Set(["BUILD","TEST","INDEX","READ_TEXT","SEARCH_TEXT","HASH_TREE","WORKBOOK_AUDIT","PACKAGE","SUPPORT_BUNDLE","APPLY_PATCH","TRAIN_LOCAL","REALITY_ANALYZE"]);
const PAIR_TTL_MS=10*60*1000,ONLINE_MS=90*1000,JOB_TTL_MS=120*1000;
const SOVEREIGN_STATUSES=new Set(["IDLE","VERIFYING_BASELINE","AUTHORING","TESTING_CANDIDATE","JUDGING","PROMOTING","PROMOTED","LOCAL_MODEL_UNAVAILABLE","BLOCKED_LOCAL_TOOLING","CANDIDATE_REJECTED","SUPERSEDED","PROMOTION_PUSH_BLOCKED","QUARANTINE"]);
function token(bytes=24){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return[...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
function code(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",a=new Uint8Array(8);crypto.getRandomValues(a);return[...a].map(x=>alphabet[x%alphabet.length]).join("")}
function bearer(req){const h=req.headers.get("Authorization")||"";return h.startsWith("Bearer ")?h.slice(7).trim():""} function now(){return new Date().toISOString()} function ms(v){return Date.parse(v)||0}
async function authController(storage,req){const raw=bearer(req);if(!raw)return null;const h=await hash(raw),rec=await storage.get("c:"+h);return rec?{hash:h,record:rec}:null}
async function authDevice(storage,req,deviceId){const raw=bearer(req);if(!raw||!deviceId)return null;const rec=await storage.get("d:"+deviceId);if(!rec||rec.revoked)return null;const h=await hash(raw);return h===rec.token_hash?{record:rec,raw}:null}
async function listPrefix(storage,prefix){return[...(await storage.list({prefix})).entries()]}
function safeRel(value){const s=String(value||".").trim().replaceAll("\\","/");if(!s||s.startsWith("/")||/^[A-Za-z]:/.test(s)||s.split("/").includes(".."))return null;return s.split("/").filter(x=>x&&x!==".").join("/")||"."}
function safeHex(value,n){const s=String(value||"").toLowerCase();return new RegExp(`^[0-9a-f]{${n}}$`).test(s)?s:null}
function sovereignTelemetry(value){const v=value&&typeof value==="object"?value:{},status=String(v.status||"").toUpperCase();if(!SOVEREIGN_STATUSES.has(status))return null;const observed_at=typeof v.observed_at==="string"&&Number.isFinite(Date.parse(v.observed_at))?new Date(v.observed_at).toISOString():null;if(!observed_at)return null;const out={schema:"OMEGA_LINK_SOVEREIGN_EVOLUTION_V1",status,observed_at,active:Boolean(v.active),provider:String(v.provider||"local-ollama").slice(0,64),model:String(v.model||"unknown").slice(0,160),paid_external_ai_required:false,external_paid_ai_fallback:false,canonical_mutation:false};const baseline=safeHex(v.baseline_sha,40),promoted=safeHex(v.promoted_sha,40),current=safeHex(v.current_sha,40);if(baseline)out.baseline_sha=baseline;if(promoted)out.promoted_sha=promoted;if(current)out.current_sha=current;return out}
function planSteps(draft){const p=safeRel(draft.project_path||".");if(!p)throw new Error("unsafe project path");const confirmed=Boolean(draft.confirmed),profile=draft.profile||"AUTO_BUILD";switch(String(draft.action||"").toUpperCase()){case"INDEX":return[{op:"INDEX",path:p}];case"READ_TEXT":return[{op:"READ_TEXT",path:p}];case"SEARCH_TEXT":return[{op:"SEARCH_TEXT",path:p,args:{pattern:String(draft.pattern||"").slice(0,256)}}];case"HASH_TREE":return[{op:"HASH_TREE",path:p}];case"WORKBOOK_AUDIT":return[{op:"WORKBOOK_AUDIT",path:p}];case"PACKAGE":return[{op:"PACKAGE",path:p,output:String(draft.output||".omega/packages/OMEGA_PACKAGE.zip")}];case"SUPPORT_BUNDLE":return[{op:"SUPPORT_BUNDLE",output:String(draft.output||".omega/support/OMEGA_SUPPORT.zip")}];case"TRAIN_LOCAL":return[{op:"TRAIN_LOCAL",path:p,args:{proof_lessons:Array.isArray(draft.proof_lessons)?draft.proof_lessons.slice(0,100):[]}}];case"REALITY_ANALYZE":return[{op:"REALITY_ANALYZE",path:p,args:{config:draft.config||{}}}];case"BUILD":return[{op:"BUILD",path:p,args:{profile,confirmed}}];case"TEST":return[{op:"TEST",path:p,args:{profile,confirmed}}];case"APPLY_PATCH":return[{op:"APPLY_PATCH",path:p,args:{before_sha256:draft.before_sha256,content:draft.content,confirmed}}];default:throw new Error("unsupported action")}}
async function signEnvelope(job,raw){const issued=Date.now(),unsigned={schema:"omega.link.execution-envelope.v1",job,issued_at_ms:issued,expires_at_ms:issued+JOB_TTL_MS,nonce:(await hash(`${job.job_id}:${issued}:${job.plan_fingerprint||""}`)).slice(0,32)},key=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw)),hkey=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]),canonical=JSON.stringify(unsigned,Object.keys(unsigned).sort()),sig=await crypto.subtle.sign("HMAC",hkey,new TextEncoder().encode(canonical));return{...unsigned,signature:[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("")}}
export async function createPair(storage){const controller=token(),pairCode=code(),ch=await hash(controller),ph=await hash(pairCode),created=now(),expires=new Date(Date.now()+PAIR_TTL_MS).toISOString();await storage.put("c:"+ch,{created_at:created});await storage.put("pair:"+ph,{controller_hash:ch,created_at:created,expires_at:expires});return{schema:"OMEGA_LINK_PAIR_V1",pair_code:pairCode,expires_at:expires,controller_token:controller,controller_token_returned_once:true}}
export async function claimPair(storage,body){const ph=await hash(String(body.code||"").trim().toUpperCase()),pair=await storage.get("pair:"+ph);if(!pair||ms(pair.expires_at)<Date.now())throw new Error("invalid_or_expired_pair_code");const device_token=token(),device_id=crypto.randomUUID(),rec={device_id,device_name:String(body.device_name||"OMEGA Windows Host").slice(0,120),controller_hash:pair.controller_hash,token_hash:await hash(device_token),created_at:now(),last_seen:null,revoked:false,capabilities:[],sovereign_evolution:null};await storage.put("d:"+device_id,rec);await storage.delete("pair:"+ph);return{schema:"OMEGA_LINK_DEVICE_V1",device_id,device_name:rec.device_name,device_token,device_token_returned_once:true,authority:"SOVEREIGN_HOST_EXECUTOR",execution_protocol:"SIGNED_ENVELOPE_V1"}}
export async function heartbeat(storage,req,body){const auth=await authDevice(storage,req,body.device_id);if(!auth)throw new Error("device_unauthorized");const rec=auth.record;rec.last_seen=now();rec.capabilities=(body.capabilities||[]).filter(x=>LINK_ACTIONS.has(String(x))).slice(0,32);rec.sovereign_evolution=sovereignTelemetry(body.sovereign_evolution);rec.execution_protocol=body.execution_protocol==="SIGNED_ENVELOPE_V1"?"SIGNED_ENVELOPE_V1":"LEGACY_UNSUPPORTED";await storage.put("d:"+rec.device_id,rec);return{status:"ONLINE",device_id:rec.device_id,last_seen:rec.last_seen,capabilities:rec.capabilities,execution_protocol:rec.execution_protocol,sovereign_evolution:rec.sovereign_evolution,authority:"HOST_ADAPTER / LINK_CORE",boundary:"host telemetry is authenticated device observation; it does not mutate canonical state"}}
export async function linkStatus(storage,req){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const devices=(await listPrefix(storage,"d:")).map(([,v])=>v).filter(v=>v.controller_hash===c.hash).map(v=>({...v,token_hash:undefined,controller_hash:undefined,online:Boolean(v.last_seen&&Date.now()-ms(v.last_seen)<ONLINE_MS)}));const jobs=(await listPrefix(storage,"job:")).map(([,v])=>v).filter(v=>v.controller_hash===c.hash).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,100);const missions=(await listPrefix(storage,"m:")).map(([,v])=>v).filter(v=>v.controller_hash===c.hash).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,50);return{schema:"OMEGA_MISSION_CONTROL_V1",devices,jobs,missions,controller_authority:"CONTROL_VIEWPORT_ONLY",hostStateMutation:false,boundary:"online and sovereign evolution state derive from authenticated device heartbeat only"}}
export async function revokeDevice(storage,req,body){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const rec=await storage.get("d:"+body.device_id);if(!rec||rec.controller_hash!==c.hash)throw new Error("device_not_found");rec.revoked=true;await storage.put("d:"+rec.device_id,rec);return{status:"REVOKED",device_id:rec.device_id}}
export async function queueJob(storage,req,body){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");if(!body.confirmed)throw new Error("explicit_confirmation_required");const action=String(body.action||"").toUpperCase();if(!LINK_ACTIONS.has(action))throw new Error("action_not_allowed");const device=await storage.get("d:"+body.device_id);if(!device||device.controller_hash!==c.hash||device.revoked)throw new Error("device_not_available");if(!device.last_seen||Date.now()-ms(device.last_seen)>=ONLINE_MS)throw new Error("device_not_online");if(device.execution_protocol!=="SIGNED_ENVELOPE_V1")throw new Error("device_signed_protocol_required");const draft={...body,action,confirmed:true},steps=planSteps(draft),job_id=crypto.randomUUID(),base={schema:"OMEGA_LINK_JOB_V1",job_id,device_id:device.device_id,controller_hash:c.hash,action,profile:String(body.profile||"NONE"),project_path:safeRel(body.project_path||"."),steps,status:"QUEUED",created_at:now(),claimed_at:null,completed_at:null,mission_id:body.mission_id||null};base.plan_fingerprint=await hash({action:base.action,profile:base.profile,project_path:base.project_path,steps:base.steps});await storage.put("job:"+job_id,base);return{...base,controller_hash:undefined}}
export async function nextJob(storage,req,body){const auth=await authDevice(storage,req,body.device_id);if(!auth)throw new Error("device_unauthorized");const dev=auth.record,jobs=(await listPrefix(storage,"job:")).map(([,v])=>v).filter(v=>v.device_id===dev.device_id&&v.status==="QUEUED").sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))),job=jobs[0];if(!job)return{envelope:null};job.status="CLAIMED";job.claimed_at=now();await storage.put("job:"+job.job_id,job);const visible={...job,controller_hash:undefined};return{envelope:await signEnvelope(visible,auth.raw)}}
export async function completeJob(storage,req,body){const auth=await authDevice(storage,req,body.device_id);if(!auth)throw new Error("device_unauthorized");const dev=auth.record,job=await storage.get("job:"+body.job_id);if(!job||job.device_id!==dev.device_id)throw new Error("job_not_found");if(job.status!=="CLAIMED")throw new Error("job_not_claimed");const result=body.result||{};job.status=result.status==="PASS"?"PASS":"FAIL";job.completed_at=now();job.result=result;job.result_fingerprint=await hash(result);job.production_summary=translateResult(job);await storage.put("job:"+job.job_id,job);return{status:job.status,job_id:job.job_id,result_fingerprint:job.result_fingerprint,production_summary:job.production_summary}}
function translateResult(job){const results=job.result?.results||[],passed=results.filter(x=>x.status==="PASS").length,failed=results.filter(x=>x.status==="FAIL"),changed=results.flatMap(x=>{const r=x.result||{};return[r.output,r.path,r.backup_path,r.release_path].filter(Boolean)}).slice(0,20);return{what_changed:changed.length?changed:["No output path reported"],what_passed:`${passed}/${results.length} typed steps returned PASS`,blocked_or_held:failed.length?failed.map(x=>x.detail||x.error):[],next_action:failed.length?"Review the first failed typed step before retrying.":"Review returned proof and promote only if it satisfies the target acceptance gate.",result_fingerprint:job.result_fingerprint||null,boundary:"derived from host-returned proof only; missing proof is never promoted to success"}}
export async function createMission(storage,req,body){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const device=await storage.get("d:"+body.device_id);if(!device||device.controller_hash!==c.hash||device.revoked)throw new Error("device_not_available");const ops=(body.allowed_operations||[]).map(x=>String(x).toUpperCase());if(!ops.length||ops.some(x=>!LINK_ACTIONS.has(x)))throw new Error("mission_operation_not_allowed");const cycles=Number(body.cycle_budget||3);if(!Number.isInteger(cycles)||cycles<2||cycles>8)throw new Error("cycle_budget_must_be_2_to_8");const project=safeRel(body.project_path||".");if(!project)throw new Error("unsafe_project_path");const domains=[...new Set((body.allowed_domains||[]).map(x=>String(x).toLowerCase().trim()).filter(Boolean))];if(domains.some(d=>d.includes("/")||d.includes(":")||d.startsWith(".")||d.endsWith(".")))throw new Error("invalid_allowed_domain");const id=crypto.randomUUID(),m={schema:"OMEGA_BUILD_MISSION_V1",mission_id:id,controller_hash:c.hash,device_id:device.device_id,project_path:project,allowed_operations:ops,allowed_domains:domains,cycle_budget:cycles,cycles_used:0,status:"APPROVED",created_at:now(),updated_at:now(),hostStateMutation:false};m.mission_fingerprint=await hash({...m,controller_hash:undefined});await storage.put("m:"+id,m);return{...m,controller_hash:undefined}}
