import { hash } from "./kernel.js";

const MAX_RECORDS=250,MAX_TITLE=160,MAX_SUMMARY=4000,MAX_TRANSCRIPT=12000,MAX_TAGS=24;
const WORD=/[a-z0-9][a-z0-9_'-]{2,}/gi;
const SECRET_PATTERNS=[
  [/(bearer\s+)[A-Za-z0-9._~+\-/=]{12,}/ig,"$1[REDACTED]"],
  [/((?:api[_ -]?key|token|password|secret)\s*[:=]\s*)[^\s,;]{6,}/ig,"$1[REDACTED]"]
];
function bearer(req){const h=req.headers.get("Authorization")||"";return h.startsWith("Bearer ")?h.slice(7).trim():""}
async function authController(storage,req){const raw=bearer(req);if(!raw)return null;const h=await hash(raw),rec=await storage.get("c:"+h);return rec?{hash:h,record:rec}:null}
function redact(v,limit){let s=String(v||"").trim().slice(0,limit);for(const [p,r] of SECRET_PATTERNS)s=s.replace(p,r);return s}
function tokenSet(v){return new Set((String(v||"").match(WORD)||[]).map(x=>x.toLowerCase()))}
function safeId(v){const s=String(v||"").replace(/[^a-zA-Z0-9._:-]/g,"-").slice(0,128).replace(/^-+|-+$/g,"");return s||crypto.randomUUID()}
function validDigest(v){return /^[0-9a-f]{64}$/.test(String(v||"").toLowerCase())}
function key(scope,id){return `mem:${scope}:${id}`}
function prefix(scope){return `mem:${scope}:`}
async function scopedRows(storage,scope){return[...(await storage.list({prefix:prefix(scope)})).values()].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))}
async function verifyRecord(r){if(!r||r.schema!=="omega.conversation.memory.cloud.v1"||r.canonical_mutation!==false)return false;const supplied=r.record_hash,b={...r};delete b.record_hash;return supplied===await hash(b)}
function importance(text,explicit=true){const t=String(text||"").toLowerCase(),signals=[["decision",.20,["decide","decision","agreed","choose","selected","final"]],["commitment",.18,["will","commit","must","require","promise","deadline"]],["goal",.16,["goal","objective","want","need","build","make"]],["constraint",.16,["constraint","never","avoid","cannot","do not","must not"]],["recovery",.12,["rollback","restore","repair","recover","broken","failure"]],["identity",.10,["canonical","authority","source","proof","version","release"]],["future",.08,["next","later","future","follow up","continue","pending"]]];let score=explicit?.15:0,reasons=explicit?["explicit_user_save"]:[];for(const [reason,w,needles] of signals)if(needles.some(n=>t.includes(n))){score+=w;reasons.push(reason)}if(t.length>=800){score+=.05;reasons.push("substantive_context")}score=Math.min(1,+score.toFixed(4));return{score,reasons,suggest_save:explicit||score>=.48}}
async function boundedPut(storage,scope,record){await storage.put(key(scope,record.conversation_id),record);const rows=await scopedRows(storage,scope);if(rows.length<=MAX_RECORDS)return;for(const row of rows.slice(MAX_RECORDS))await storage.delete(key(scope,row.conversation_id))}

export async function saveConversation(storage,req,body,currentDigest){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const canonical_digest=String(body.canonical_digest||currentDigest||"").toLowerCase();if(!validDigest(canonical_digest))throw new Error("canonical_digest_invalid");const title=redact(body.title,MAX_TITLE)||"Important conversation",summary=redact(body.summary,MAX_SUMMARY),transcript=redact(body.transcript,MAX_TRANSCRIPT),tags=[...new Set((body.tags||[]).map(x=>redact(x,64).toLowerCase()).filter(Boolean))].sort().slice(0,MAX_TAGS);if(!summary&&!transcript)throw new Error("conversation_content_required");const signal=importance(`${title}\n${summary}\n${transcript}`,true),id=safeId(body.conversation_id),previous=await storage.get(key(c.hash,id));const base={schema:"omega.conversation.memory.cloud.v1",conversation_id:id,title,summary,transcript,tags,importance:signal,canonical_digest,created_at:previous?.created_at||new Date().toISOString(),updated_at:new Date().toISOString(),previous_hash:previous?.record_hash||null,archived:false,canonical_mutation:false,source_class:"SAVED_CONVERSATION_CONTEXT",controller_scope_hash:c.hash};const record={...base,record_hash:await hash(base)};await boundedPut(storage,c.hash,record);return{status:"SAVED_CLOUD",record:{...record,controller_scope_hash:undefined},boundary:"Authenticated controller-scoped context only; saved conversation memory does not mutate canonical OMEGA state."}}
export async function listConversations(storage,req){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const rows=await scopedRows(storage,c.hash),visible=[];for(const r of rows){if(await verifyRecord(r))visible.push({...r,controller_scope_hash:undefined})}return{schema:"omega.conversation.memory.list.v1",records:visible.slice(0,MAX_RECORDS),invalid_records:rows.length-visible.length,canonical_mutation:false}}
export async function searchConversations(storage,req,query,limit=8){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const q=tokenSet(query);if(!q.size)return{schema:"omega.conversation.memory.search.v1",query:String(query||""),matches:[],canonical_mutation:false};const rows=await scopedRows(storage,c.hash),ranked=[];for(const r of rows){if(r.archived||!(await verifyRecord(r)))continue;const h=tokenSet(`${r.title} ${r.summary} ${(r.tags||[]).join(" ")}`),matched=[...q].filter(x=>h.has(x)).sort();if(!matched.length)continue;const union=new Set([...q,...h]),lexical=matched.length/Math.max(1,union.size),imp=Number(r.importance?.score||0),relevance=Math.min(1,+((lexical*2.2)+(imp*.28)).toFixed(4));ranked.push({conversation_id:r.conversation_id,title:r.title,summary:r.summary,tags:r.tags,relevance,why:{matched_terms:matched.slice(0,12),importance:imp},record_hash:r.record_hash,canonical_digest:r.canonical_digest,source_class:r.source_class})}ranked.sort((a,b)=>b.relevance-a.relevance||String(a.conversation_id).localeCompare(String(b.conversation_id)));return{schema:"omega.conversation.memory.search.v1",query:String(query||""),matches:ranked.slice(0,Math.max(1,Math.min(20,+limit||8))),canonical_mutation:false,boundary:"Context ranking is controller-scoped saved memory, not external evidence or canonical truth."}}
export async function archiveConversation(storage,req,body){const c=await authController(storage,req);if(!c)throw new Error("controller_unauthorized");const id=safeId(body.conversation_id),old=await storage.get(key(c.hash,id));if(!old||!(await verifyRecord(old)))throw new Error("conversation_not_found_or_invalid");const base={...old,archived:true,updated_at:new Date().toISOString(),previous_hash:old.record_hash};delete base.record_hash;const record={...base,record_hash:await hash(base)};await storage.put(key(c.hash,id),record);return{status:"ARCHIVED",conversation_id:id,record_hash:record.record_hash,previous_hash:old.record_hash,canonical_mutation:false}}
export async function memoryStatus(storage,req){const c=await authController(storage,req);if(!c)return{authenticated:false,storage:"controller_scoped_durable_object",max_records:MAX_RECORDS};const rows=await scopedRows(storage,c.hash);return{authenticated:true,storage:"controller_scoped_durable_object",records:rows.length,max_records:MAX_RECORDS,canonical_mutation:false}}
