export const MISSION_SURFACE_RELEASE_R200 = "r200-unified-mission-control";

const style = `<style id="omegaMissionSurfaceR200Style">
#r200MissionBtn{height:34px;border:1px solid #5b6d89;border-radius:9px;background:#15243a;color:#f2f6fb;padding:0 10px;cursor:pointer;font:850 9px/1 Inter,system-ui;white-space:nowrap}
#omegaMissionR200{position:fixed;z-index:2147483647;inset:0;display:none;place-items:start center;padding:5vh 12px 12px;background:rgba(0,2,5,.82);backdrop-filter:blur(14px)}#omegaMissionR200.open{display:grid}.r200Box{width:min(1180px,100%);max-height:90vh;overflow:auto;border:1px solid #435d7d;border-radius:18px;background:#06101a;color:#edf4fc;box-shadow:0 42px 150px #000e;font:700 11px/1.4 Inter,system-ui}.r200Head{position:sticky;top:0;z-index:3;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px;border-bottom:1px solid #2b435f;background:#06101af3;backdrop-filter:blur(16px)}.r200Head b{display:block;font-size:14px;letter-spacing:.1em}.r200Head small{display:block;margin-top:4px;color:#8198b0;font-size:8px}.r200Close,.r200Btn{border:1px solid #3a5878;border-radius:9px;background:#0d1b2a;color:#edf4fc;padding:9px 11px;cursor:pointer;font:850 9px Inter,system-ui}.r200Body{display:grid;grid-template-columns:minmax(300px,.78fr) minmax(0,1.22fr);gap:12px;padding:13px}.r200Panel{border:1px solid #29425d;border-radius:12px;background:#08141f;padding:11px;min-width:0}.r200Label{display:block;margin:0 0 6px;color:#8aa0b7;font-size:8px;letter-spacing:.08em}.r200Intent{width:100%;min-height:190px;resize:vertical;border:1px solid #34516f;border-radius:10px;background:#050d15;color:#eff5fc;padding:11px;outline:none;font:700 10px/1.45 ui-monospace,monospace}.r200Checks{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:9px 0}.r200Check{display:flex;align-items:center;gap:7px;border:1px solid #29435e;border-radius:9px;padding:8px;background:#07111a;color:#aebfd1;font-size:8px}.r200Check input{accent-color:auto}.r200Actions{display:flex;flex-wrap:wrap;gap:7px}.r200Truth{margin-top:10px;padding:9px;border:1px solid #4d4931;border-radius:9px;background:#141308;color:#d9c879;font-size:8px;line-height:1.45}.r200Metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin-bottom:9px}.r200Metric{border:1px solid #29435e;border-radius:9px;background:#07111a;padding:8px}.r200Metric small{display:block;color:#778da4;font-size:7px}.r200Metric b{display:block;margin-top:3px;font-size:10px}.r200Modes{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0 10px}.r200Mode{border:1px solid #314b68;border-radius:999px;padding:4px 7px;background:#0b1825;color:#9fb4c9;font-size:7px}.r200Out{min-height:420px;max-height:60vh;overflow:auto;white-space:pre-wrap;word-break:break-word;border:1px solid #253d56;border-radius:9px;background:#02070c;padding:11px;color:#a9bfd4;font:9px/1.48 ui-monospace,monospace}.r200Ok{color:#67d99c}.r200Warn{color:#e3c66e}.r200Bad{color:#e88686}
@media(max-width:820px){#omegaMissionR200{padding:48px 7px 7px}.r200Box{max-height:calc(100vh - 55px)}.r200Body{grid-template-columns:1fr}.r200Intent{min-height:145px}.r200Metrics{grid-template-columns:1fr 1fr}.r200Out{min-height:260px;max-height:42vh}.r200Head small{display:none}}
</style>`;

const markup = `<div id="omegaMissionR200" aria-hidden="true"><section class="r200Box"><header class="r200Head"><div><b>OMEGA · R200 MISSION KERNEL</b><small>INTENT → ALL MODES → ROUTE → EXECUTE → RECEIPT → VERIFY → RESIDUAL → RENDER → ADMISSION</small></div><button id="r200Close" class="r200Close" type="button">CLOSE</button></header><div class="r200Body"><div class="r200Panel"><label class="r200Label" for="r200Intent">MISSION INTENT</label><textarea id="r200Intent" class="r200Intent" spellcheck="false">Review the whole OMEGA system, correlate all established development, find residual failures, preserve proven capability, and identify the highest-value bounded next build.</textarea><div class="r200Checks"><label class="r200Check"><input id="r200AllModes" type="checkbox" checked> ALL CANONICAL MODES/LENSES</label><label class="r200Check"><input id="r200AllDomains" type="checkbox" checked> WHOLE-SYSTEM DOMAIN CORRELATION</label><label class="r200Check"><input id="r200UseAI" type="checkbox" checked> SOURCE-GROUNDED SAI/AI</label><label class="r200Check"><input id="r200Earth" type="checkbox"> EARTH OBSERVATION SOURCES</label></div><div class="r200Actions"><button id="r200Plan" class="r200Btn" type="button">PLAN MISSION</button><button id="r200Execute" class="r200Btn" type="button">EXECUTE MISSION</button><button id="r200Whole" class="r200Btn" type="button">WHOLE-SYSTEM TEMPLATE</button></div><div class="r200Truth">ALL MODES means the canonical analytical/governance lens ensemble is active. It does not fabricate unavailable engines or execute every expensive specialist indiscriminately. Specialist execution remains evidence- and input-gated; RETURNED remains distinct from VERIFIED.</div></div><div class="r200Panel"><div class="r200Metrics"><div class="r200Metric"><small>MISSION</small><b id="r200MissionId">—</b></div><div class="r200Metric"><small>MODES</small><b id="r200ModeCount">—</b></div><div class="r200Metric"><small>REQUIRED</small><b id="r200Required">—</b></div><div class="r200Metric"><small>VERIFIED</small><b id="r200Verified">—</b></div><div class="r200Metric"><small>ADMISSION</small><b id="r200Admission">—</b></div></div><div id="r200Modes" class="r200Modes"></div><pre id="r200Out" class="r200Out">No mission packet yet.</pre></div></div></section></div>`;

const script = `<script id="omegaMissionSurfaceR200Runtime">(()=>{
const q=s=>document.querySelector(s);if(!q('#omegaOneSystemR199')||q('#r200MissionBtn'))return;const bar=q('#omegaOneSystemR199'),operate=q('#r199OperateBtn')||q('#r199CorrelationBtn'),btn=document.createElement('button');btn.id='r200MissionBtn';btn.type='button';btn.textContent='MISSION';operate?.before(btn);const modal=q('#omegaMissionR200'),out=q('#r200Out');
function open(on){modal?.classList.toggle('open',on);modal?.setAttribute('aria-hidden',String(!on));if(on)q('#r200Intent')?.focus()}btn.onclick=()=>open(true);q('#r200Close').onclick=()=>open(false);modal?.addEventListener('click',e=>{if(e.target===modal)open(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')open(false);if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='k'){e.preventDefault();open(true)}});
const whole='Review the entire OMEGA development as one system. Activate the full canonical mode/lens ensemble; correlate CanonState, V6, Genesis, authenticated Hybrid/PC truth, AI/SAI, swarm, computation, validation, optical solvers, Earth observation, Drive corpus, recovery, render/traversal, packaging and proof. Preserve all proven capability, identify contradictions and residuals, heavily prune redundant presentation, and route the highest-value bounded successor work without inventing execution or promotion authority.';q('#r200Whole').onclick=()=>{q('#r200Intent').value=whole;q('#r200AllModes').checked=true;q('#r200AllDomains').checked=true;q('#r200UseAI').checked=true};
function body(){return{intent:q('#r200Intent').value,allModes:q('#r200AllModes').checked,allDomains:q('#r200AllDomains').checked,useAI:q('#r200UseAI').checked,earth:q('#r200Earth').checked}}
function cls(el,state){if(!el)return;el.className=state==='ok'?'r200Ok':state==='warn'?'r200Warn':state==='bad'?'r200Bad':''}
function render(d,executed){q('#r200MissionId').textContent=(d.missionId||'—').replace('mission_','').slice(0,12);const modes=d.modes?.activeCount??d.activeModes?.length??d.modeCount??'—';q('#r200ModeCount').textContent=String(modes);const req=d.execution?.requiredTasks??(d.tasks||[]).filter(x=>x.required).length??'—',ver=d.execution?.requiredVerified??'—';q('#r200Required').textContent=String(req);q('#r200Verified').textContent=String(ver);const admission=d.admission?.state||d.authority||'PLAN';q('#r200Admission').textContent=String(admission).replaceAll('_',' ');cls(q('#r200Admission'),String(admission).includes('ELIGIBLE')?'ok':String(admission).includes('HOLD')?'warn':'');const priority=d.modes?.priority||d.priorityModes||[];q('#r200Modes').innerHTML=priority.slice(0,18).map(x=>'<span class="r200Mode">'+String(x)+'</span>').join('');out.textContent=JSON.stringify(d,null,2);if(executed){cls(q('#r200Verified'),Number(ver)>=Number(req)&&Number(req)>0?'ok':'warn')}}
async function call(path,payload){out.textContent='Mission kernel working…';try{const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify(payload)}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={text:t}};render(d,path.endsWith('/execute'));if(!r.ok)cls(q('#r200Admission'),'bad')}catch(e){out.textContent=String(e);cls(q('#r200Admission'),'bad')}}
q('#r200Plan').onclick=()=>call('/api/mission/r200/plan',body());q('#r200Execute').onclick=()=>call('/api/mission/r200/execute',body());
})();</script>`;

export async function enhanceMissionSurfaceR200(response: Response): Promise<Response> {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  let html = await response.text();
  if (!html.includes('id="omegaOneSystemR199"') || html.includes('id="omegaMissionR200"')) return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  html = html.includes("</head>") ? html.replace("</head>", style + "</head>") : style + html;
  html = html.includes("</body>") ? html.replace("</body>", markup + script + "</body>") : html + markup + script;
  const headers = new Headers(response.headers);
  headers.set("cache-control", "no-store");
  headers.set("x-omega-mission-surface", MISSION_SURFACE_RELEASE_R200);
  return new Response(html, { status: response.status, statusText: response.statusText, headers });
}
