export const ONE_SYSTEM_OPERATOR_SURFACE_R199 = "r199-unified-operator-console";

const style = `<style id="omegaOneSystemOperatorSurfaceR199Style">
#r199OperateBtn{height:34px;border:1px solid #496681;border-radius:9px;background:#112236;color:#f1f6fc;padding:0 10px;cursor:pointer;font:800 9px/1 Inter,system-ui;white-space:nowrap}
#omegaR199Operator{position:fixed;z-index:2147483647;inset:0;display:none;place-items:start center;padding:7vh 14px 14px;background:rgba(0,2,5,.78);backdrop-filter:blur(13px)}#omegaR199Operator.open{display:grid}.r199OpBox{width:min(980px,100%);max-height:88vh;overflow:auto;border:1px solid #3a5675;border-radius:17px;background:#07111b;color:#edf4fc;box-shadow:0 36px 130px #000d;font:700 11px/1.35 Inter,system-ui}.r199OpHead{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 14px;border-bottom:1px solid #29415c;background:#07111bf2;backdrop-filter:blur(15px)}.r199OpHead b{display:block;font-size:13px;letter-spacing:.09em}.r199OpHead small{display:block;color:#8196ad;margin-top:4px;font-size:8px}.r199OpClose,.r199OpRun,.r199OpSnapshot,.r199OpTemplate{border:1px solid #395674;border-radius:9px;background:#0d1a28;color:#edf4fc;padding:9px 11px;cursor:pointer;font:800 9px Inter,system-ui}.r199OpBody{display:grid;grid-template-columns:minmax(250px,.72fr) minmax(0,1.28fr);gap:12px;padding:13px}.r199OpControls,.r199OpOutput{border:1px solid #263e58;border-radius:12px;background:#08131e;padding:11px;min-width:0}.r199OpField{margin-bottom:10px}.r199OpField label{display:block;margin-bottom:5px;color:#89a0b8;font-size:8px;letter-spacing:.07em}.r199OpField select,.r199OpField textarea{width:100%;border:1px solid #314c69;border-radius:9px;background:#07101a;color:#eaf2fb;padding:10px;font:700 10px/1.35 ui-monospace,monospace;outline:none}.r199OpField textarea{min-height:190px;resize:vertical}.r199OpActions{display:flex;gap:7px;flex-wrap:wrap}.r199OpHint{margin:9px 0;color:#7d93aa;font-size:8px;line-height:1.45}.r199OpState{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-bottom:9px}.r199OpMetric{padding:8px;border:1px solid #29435e;border-radius:9px;background:#07101a}.r199OpMetric small{display:block;color:#748aa1;font-size:7px}.r199OpMetric b{display:block;margin-top:3px;font-size:10px}.r199OpResult{min-height:330px;max-height:56vh;overflow:auto;white-space:pre-wrap;word-break:break-word;border:1px solid #233a52;border-radius:9px;background:#03080d;padding:11px;color:#aac0d5;font:9px/1.45 ui-monospace,monospace}.r199OpRestore{color:#e4c56c}.r199OpOk{color:#61d89b}.r199OpBad{color:#ed8585}
@media(max-width:760px){#r199OperateBtn{padding:0 8px}#omegaR199Operator{padding:54px 8px 8px}.r199OpBox{max-height:calc(100vh - 62px)}.r199OpBody{grid-template-columns:1fr}.r199OpState{grid-template-columns:1fr 1fr}.r199OpField textarea{min-height:145px}.r199OpResult{min-height:240px;max-height:42vh}}
</style>`;

const markup = `<div id="omegaR199Operator" aria-hidden="true"><section class="r199OpBox"><header class="r199OpHead"><div><b>OMEGA · UNIFIED OPERATOR</b><small>ONE CONTROL PLANE · SPECIALIST ROUTING · RECEIPT BEFORE ADMISSION</small></div><button id="r199OpClose" class="r199OpClose" type="button">CLOSE</button></header><div class="r199OpBody"><div class="r199OpControls"><div class="r199OpField"><label>MASTER FUNCTION</label><select id="r199OpMenu"><option value="MENU-01">01 · LAUNCH</option><option value="MENU-02">02 · HOST INTAKE</option><option value="MENU-03">03 · STATE MANIFOLD</option><option value="MENU-04">04 · 20,736 EXPAND</option><option value="MENU-05">05 · RENDERER</option><option value="MENU-06">06 · TRAVERSAL</option><option value="MENU-07">07 · FORECAST</option><option value="MENU-08">08 · PROOF</option><option value="MENU-09">09 · AUDIO · RESTORE REQUIRED</option><option value="MENU-10">10 · AI ASSIST</option><option value="MENU-11">11 · RECOVERY</option><option value="MENU-12">12 · PACKAGING</option></select></div><div class="r199OpField"><label>ACTION</label><select id="r199OpAction"></select></div><div class="r199OpField"><label>INPUT / PAYLOAD</label><textarea id="r199OpPayload" spellcheck="false"></textarea></div><div class="r199OpActions"><button id="r199OpRun" class="r199OpRun" type="button">RUN + RECEIPT</button><button id="r199OpSnapshot" class="r199OpSnapshot" type="button">CORRELATED SNAPSHOT</button><button id="r199OpTemplate" class="r199OpTemplate" type="button">LOAD TEMPLATE</button></div><div id="r199OpHint" class="r199OpHint"></div></div><div class="r199OpOutput"><div class="r199OpState"><div class="r199OpMetric"><small>MENU</small><b id="r199OpStateMenu">—</b></div><div class="r199OpMetric"><small>ACTION</small><b id="r199OpStateAction">—</b></div><div class="r199OpMetric"><small>RETURNED</small><b id="r199OpStateReturned">—</b></div><div class="r199OpMetric"><small>VERIFIED</small><b id="r199OpStateVerified">—</b></div></div><pre id="r199OpResult" class="r199OpResult">No operator action yet.</pre></div></div></section></div>`;

const script = `<script id="omegaOneSystemOperatorSurfaceR199Runtime">(()=>{
const q=s=>document.querySelector(s);if(!q('#omegaOneSystemR199')||q('#r199OperateBtn'))return;const bar=q('#omegaOneSystemR199'),corr=q('#r199CorrelationBtn'),btn=document.createElement('button');btn.id='r199OperateBtn';btn.type='button';btn.textContent='OPERATE';corr?.before(btn);
const modal=q('#omegaR199Operator'),menu=q('#r199OpMenu'),action=q('#r199OpAction'),payload=q('#r199OpPayload'),result=q('#r199OpResult'),hint=q('#r199OpHint');
const config={
'MENU-01':['observe','snapshot'],'MENU-02':['observe','snapshot'],'MENU-03':['observe','earth_search','corpus_analyze','snapshot'],'MENU-04':['observe','snapshot'],'MENU-05':['observe','specialist_execute','earth_search','snapshot'],'MENU-06':['observe','specialist_execute','corpus_analyze','snapshot'],'MENU-07':['observe','specialist_execute','snapshot'],'MENU-08':['observe','earth_search','corpus_analyze','snapshot'],'MENU-09':['observe'],'MENU-10':['observe','specialist_execute','snapshot'],'MENU-11':['observe','corpus_analyze','snapshot'],'MENU-12':['observe','prepare_build_candidate','snapshot']};
const templates={
observe:'{}',snapshot:'{}',earth_search:'{"providers":["sentinel1","nisar","umbra","capella","iceye"],"days":45,"limit":16}',corpus_analyze:'{"table":"registry","q":"","limit":100}',prepare_build_candidate:'{"objective":"Describe the bounded successor candidate","refs":["warp-session-ref"],"warpId":"warp-id","profile":"PULSE","purpose":"BUILD"}',specialist_execute:'{"operation":"sai.query","prompt":"Ask OMEGA using source-grounded SAI"}'};
const hints={observe:'Read the authoritative domain surface for this master function.',snapshot:'Correlate State, V6/Genesis/Hybrid, proof, workspace, fabric, AI/SAI, swarm, build, recovery and Earth-source availability into one receipt.',earth_search:'Query real public SAR catalogs. Observation metadata stays separate from inference and forecast.',corpus_analyze:'Apply the established R195 calculus only where source metrics exist; no invented decision thresholds.',prepare_build_candidate:'Create a bounded R178 candidate from an exact completed warp receipt. This does not authorize source mutation, deployment or promotion.',specialist_execute:'Route through the R195 specialist execution registry. For AI use sai.query, ai.fuse or ai.cloud; compute supports relativity, optics, continuity and scalar FDTD operations.'};
function refresh(){const acts=config[menu.value]||['observe'];action.innerHTML=acts.map(x=>'<option value="'+x+'">'+x.replaceAll('_',' ').toUpperCase()+'</option>').join('');loadTemplate()}
function loadTemplate(){payload.value=templates[action.value]||'{}';hint.textContent=menu.value==='MENU-09'?'AUDIO remains visible as RESTORE REQUIRED; no fake canonical route will be created.':(hints[action.value]||'')}
function open(on){modal?.classList.toggle('open',on);modal?.setAttribute('aria-hidden',String(!on));if(on)menu.focus()}
btn.onclick=()=>open(true);q('#r199OpClose').onclick=()=>open(false);modal?.addEventListener('click',e=>{if(e.target===modal)open(false)});document.addEventListener('keydown',e=>{if(e.key==='Escape')open(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open(true)}});menu.onchange=refresh;action.onchange=loadTemplate;q('#r199OpTemplate').onclick=loadTemplate;
function state(menuId,act,returned,verified){q('#r199OpStateMenu').textContent=menuId;q('#r199OpStateAction').textContent=act;q('#r199OpStateReturned').textContent=returned?'YES':'NO';q('#r199OpStateReturned').className=returned?'r199OpOk':'r199OpBad';q('#r199OpStateVerified').textContent=verified?'YES':'NO / HOLD';q('#r199OpStateVerified').className=verified?'r199OpOk':'r199OpRestore'}
async function send(menuId,act,data){result.textContent='Executing through unified operator…';state(menuId,act,false,false);try{const r=await fetch('/api/system/r199/operate',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({menuId,action:act,payload:data})}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={text:t}};const returned=Boolean(d?.executionState?.returned||d?.downstream?.result||d?.result),verified=Boolean(d?.executionState?.verified||d?.downstream?.result?.executionState?.verified||d?.downstream?.result?.verification?.verified);state(menuId,act,returned,verified);result.textContent=JSON.stringify(d,null,2)}catch(e){result.textContent=String(e);state(menuId,act,false,false)}}
q('#r199OpRun').onclick=async()=>{let data={};try{data=JSON.parse(payload.value||'{}')}catch{result.textContent='Payload must be valid JSON.';return}await send(menu.value,action.value,data)};
q('#r199OpSnapshot').onclick=async()=>{result.textContent='Reading correlated one-system snapshot…';state('ALL','snapshot',false,false);try{const r=await fetch('/api/system/r199/snapshot',{cache:'no-store',headers:{accept:'application/json'}}),d=await r.json();const verified=Boolean(r.ok&&d?.runtimeReady);state('ALL','snapshot',true,verified);result.textContent=JSON.stringify(d,null,2)}catch(e){result.textContent=String(e);state('ALL','snapshot',false,false)}};
refresh();
})();</script>`;

export async function enhanceOneSystemOperatorSurfaceR199(response: Response): Promise<Response> {
  const type=response.headers.get('content-type')||'';
  if(!type.includes('text/html')) return response;
  let html=await response.text();
  if(!html.includes('id="omegaOneSystemR199"')||html.includes('id="omegaR199Operator"')) return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
  html=html.includes('</head>')?html.replace('</head>',style+'</head>'):style+html;
  html=html.includes('</body>')?html.replace('</body>',markup+script+'</body>'):html+markup+script;
  const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-omega-operator-surface',ONE_SYSTEM_OPERATOR_SURFACE_R199);
  return new Response(html,{status:response.status,statusText:response.statusText,headers});
}
