import type { Env } from "./index";
import { handleStateWorkbenchRequest } from "./stateWorkbench";
import { handleRelationWorkbenchRequest } from "./relationWorkbench";
import { handleMemoryWorkbenchRequest } from "./memoryWorkbench";

export type GenesisBinding={fetch(input:Request|string|URL,init?:RequestInit):Promise<Response>};
export type CapabilityEnv=Env&{GENESIS?:GenesisBinding}; export type V6View="Field"|"Earth"|"Assistant"|"Hybrid"|"Proof"; export type EdgeLoader=()=>Promise<any>;
type CapabilityDetail={id:string;title:string|null;category:string|null;domain:string|null;summary:string|null;status:string|null;declared_route:string|null};
export const CAPABILITY_BOUNDARY="Capability discovery is observational until an admitted route is previewed. This surface cannot promote Genesis candidates, mutate canonical state, generate on selection, or claim native execution.";
export const VIEWS:readonly V6View[]=["Field","Earth","Assistant","Hybrid","Proof"];
const text=(v:unknown,max=360)=>typeof v==="string"&&v.trim()?v.trim().slice(0,max):null; const isView=(v:string):v is V6View=>(VIEWS as readonly string[]).includes(v);
function sanitizeCapability(v:any):CapabilityDetail|null{if(!v||typeof v!=="object")return null;const id=text(v.id??v.capability_id??v.capabilityId??v.key,120);return id?{id,title:text(v.title??v.name??v.label,180),category:text(v.category??v.kind??v.family,120),domain:text(v.domain??v.surface??v.area,120),summary:text(v.summary??v.description??v.purpose,360),status:text(v.status??v.state??v.maturity,80),declared_route:text(v.route??v.app??v.menu??v.target,160)}:null}
async function genesisCapabilities(env:CapabilityEnv){if(!env.GENESIS)return null;try{const r=await env.GENESIS.fetch(new Request("https://omega-genesis.internal/api/capabilities",{headers:{accept:"application/json"}}));return r.ok?await r.json():null}catch{return null}}
async function capabilityIndex(env:CapabilityEnv,loadEdge:EdgeLoader){const[edge,source]=await Promise.all([loadEdge(),genesisCapabilities(env)]),g=edge?.genesis||{},m=g.manifest||{},ids:string[]=Array.isArray(m.capability_ids)?m.capability_ids.filter((v:unknown):v is string=>typeof v==="string"):[],items=Array.isArray(source?.capabilities)?source.capabilities:Array.isArray(source?.items)?source.items:[],details=items.map(sanitizeCapability).filter(Boolean) as CapabilityDetail[],byId=new Map(details.map(x=>[x.id,x])),capabilities=ids.map(id=>byId.get(id)||{id,title:null,category:null,domain:null,summary:null,status:null,declared_route:null});for(const d of details)if(!ids.includes(d.id))capabilities.push(d);return{schema:"OMEGA_V6_CAPABILITY_INDEX_V1",authority:"observation-only",boundary:CAPABILITY_BOUNDARY,evidence_timestamp:edge?.timestamp||null,manifest_digest:m.digest||null,manifest_agreed:Boolean(edge?.convergence?.reciprocal_manifest_ready&&m.digest&&edge?.convergence?.genesis_manifest_digest===m.digest),transport:edge?.convergence?.genesis_transport||m.transport||"UNPROVEN",capability_count:g.capability_count??capabilities.length,mode_count:m.mode_count??null,acceptance_gates:Array.isArray(g.acceptance_gates)?g.acceptance_gates:[],capabilities,hybrid:{pc_online:Boolean(edge?.topology?.sovereign_pc?.pc_online),heartbeat_current:Boolean(edge?.topology?.sovereign_pc?.heartbeat_current),state:edge?.topology?.sovereign_pc?.state||"UNPROVEN"}}}
function inferView(c:CapabilityDetail):{view:V6View;reason:string}{const declared=(c.declared_route||"").toLowerCase();for(const v of VIEWS)if(declared.includes(v.toLowerCase()))return{view:v,reason:"Genesis public capability metadata names an existing V6 specialist surface."};const x=[c.id,c.title,c.category,c.domain,c.summary].filter(Boolean).join(" ").toLowerCase(),rules:Array<[V6View,RegExp,string]>=[["Earth",/earth|geo|gis|map|weather|seismic|osm|noaa|terrain|source[- ]bound/,"Earth/source vocabulary routes to the source-bound Earth specialist."],["Hybrid",/hybrid|desktop|device|heartbeat|agent|native|sovereign pc|workspace/,"Device/native vocabulary routes to the heartbeat-governed Hybrid specialist."],["Assistant",/assistant|memory|context|language|intelligence|model|synthesis|conversation|route/,"Intelligence/context vocabulary routes to the route-before-generation Assistant."],["Field",/field|calculus|operator|topolog|shell|visual|mode|relation|coherence/,"Relational/calculus vocabulary routes to the Living Field specialist."],["Proof",/proof|evidence|verify|verification|rollback|govern|ledger|audit|policy/,"Proof/governance vocabulary routes to Proof & Rollback."]];for(const[v,p,r]of rules)if(p.test(x))return{view:v,reason:r};return{view:"Proof",reason:"No specialist route is evidenced; conservative fallback is Proof & Rollback."}}
async function routePreview(request:Request,env:CapabilityEnv,loadEdge:EdgeLoader){const id=(new URL(request.url).searchParams.get("id")||"").trim();if(!id)return Response.json({ok:false,error:"capability_id_required"},{status:400});const index=await capabilityIndex(env,loadEdge),cap=index.capabilities.find((x:CapabilityDetail)=>x.id===id);if(!cap)return Response.json({ok:false,error:"capability_not_in_current_genome",id},{status:404});const r=inferView(cap);return Response.json({ok:true,schema:"OMEGA_V6_CAPABILITY_ROUTE_PREVIEW_V1",authority:"routing-only",route_before_generation:true,execution:false,capability:cap,manifest_digest:index.manifest_digest,manifest_agreed:index.manifest_agreed,target:`/app/${r.view}`,specialist:r.view,reason:r.reason,boundary:CAPABILITY_BOUNDARY},{headers:{"cache-control":"no-store","x-omega-authority":"routing-only"}})}
const capabilityBrowser=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OMEGA V6 · Capability Router</title><style>:root{color-scheme:dark;font:15px/1.45 system-ui;background:#05070b;color:#f4f7ff}body{margin:0}.top,.actions{display:flex;gap:8px;flex-wrap:wrap}.top{padding:14px;border-bottom:1px solid #293950;justify-content:space-between}.wrap{max-width:1450px;margin:auto;padding:18px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card,a,button,input{background:#0d1520;color:#f4f7ff;border:1px solid #30415c;border-radius:12px;padding:11px;text-decoration:none}input{width:100%}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style></head><body><header class="top"><b>OMEGA V6 · CAPABILITIES</b><div class="actions"><a href="/workbench">State</a><a href="/relations">Relations</a><a href="/memory">Memory</a><a href="/convergence">Convergence</a></div></header><main class="wrap"><h1>Governed capability genome</h1><input id="q" placeholder="Search"><div id="g" class="grid"></div><pre id="p"></pre></main><script>let d;const g=document.querySelector('#g'),q=document.querySelector('#q'),p=document.querySelector('#p');function draw(){const s=q.value.toLowerCase();g.innerHTML='';for(const c of d?.capabilities||[]){if(s&&!JSON.stringify(c).toLowerCase().includes(s))continue;const e=document.createElement('div');e.className='card';e.innerHTML='<b></b><p></p><button>Preview route</button>';e.querySelector('b').textContent=c.title||c.id;e.querySelector('p').textContent=c.summary||c.id;e.querySelector('button').onclick=async()=>{const r=await fetch('/api/capability/route?id='+encodeURIComponent(c.id)),x=await r.json();p.textContent=JSON.stringify(x,null,2);if(r.ok){const a=document.createElement('a');a.href=x.target;a.textContent=' Open '+x.specialist;p.after(a)}};g.append(e)}}fetch('/api/convergence/capabilities',{cache:'no-store'}).then(r=>r.json()).then(x=>{d=x;draw()});q.oninput=draw;</script></body></html>`;
export function specialistFromPath(pathname:string):{matched:boolean;view:V6View|null}{if(!pathname.startsWith("/app/"))return{matched:false,view:null};const v=decodeURIComponent(pathname.slice(5));return{matched:true,view:isView(v)?v:null}}
export async function handleCapabilityRequest(request:Request,env:CapabilityEnv,loadEdge:EdgeLoader):Promise<Response|null>{const memory=await handleMemoryWorkbenchRequest(request);if(memory)return memory;const relations=handleRelationWorkbenchRequest(request);if(relations)return relations;const workbench=handleStateWorkbenchRequest(request);if(workbench)return workbench;const u=new URL(request.url);if(request.method!=="GET")return null;if(u.pathname==="/capabilities")return new Response(capabilityBrowser,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-omega-authority":"observation-only"}});if(u.pathname==="/api/convergence/capabilities")return Response.json(await capabilityIndex(env,loadEdge),{headers:{"cache-control":"no-store","x-omega-authority":"observation-only"}});if(u.pathname==="/api/capability/route")return routePreview(request,env,loadEdge);return null}
