import type { Env } from "./index";
import { handleStateWorkbenchRequest } from "./stateWorkbench";
import { handleRelationWorkbenchRequest } from "./relationWorkbench";
import { handleMemoryWorkbenchRequest } from "./memoryWorkbench";
export type GenesisBinding={fetch(input:Request|string|URL,init?:RequestInit):Promise<Response>};
export type CapabilityEnv=Env&{GENESIS?:GenesisBinding};
export type V6View = "Field" | "Earth" | "Assistant" | "Hybrid" | "Proof";
export type EdgeLoader=()=>Promise<any>; type CapabilityDetail={id:string;title:string|null;category:string|null;domain:string|null;summary:string|null;status:string|null;declared_route:string|null};
export const CAPABILITY_BOUNDARY="Capability discovery is observational until an admitted route is previewed. This surface cannot promote Genesis candidates, mutate canonical state, generate on selection, or claim native execution.";
export const VIEWS:readonly V6View[]=["Field","Earth","Assistant","Hybrid","Proof"];
function isView(value:string):value is V6View{return(VIEWS as readonly string[]).includes(value)}
function text(value:unknown,max=360):string|null{if(typeof value!=="string")return null;const clean=value.trim();return clean?clean.slice(0,max):null}
function sanitizeCapability(value:any):CapabilityDetail|null{if(!value||typeof value!=="object")return null;const id=text(value.id??value.capability_id??value.capabilityId??value.key,120);if(!id)return null;return{id,title:text(value.title??value.name??value.label,180),category:text(value.category??value.kind??value.family,120),domain:text(value.domain??value.surface??value.area,120),summary:text(value.summary??value.description??value.purpose,360),status:text(value.status??value.state??value.maturity,80),declared_route:text(value.route??value.app??value.menu??value.target,160)}}
async function genesisCapabilities(env:CapabilityEnv){if(!env.GENESIS)return null;try{const response=await env.GENESIS.fetch(new Request("https://omega-genesis.internal/api/capabilities",{method:"GET",headers:{accept:"application/json"}}));return response.ok?await response.json():null}catch{return null}}
async function capabilityIndex(env:CapabilityEnv,loadEdge:EdgeLoader){const[edge,source]=await Promise.all([loadEdge(),genesisCapabilities(env)]),genesis=edge?.genesis||{},manifest=genesis.manifest||{},ids:string[]=Array.isArray(manifest.capability_ids)?manifest.capability_ids.filter((v:unknown):v is string=>typeof v==="string"):[],sourceItems=Array.isArray(source?.capabilities)?source.capabilities:Array.isArray(source?.items)?source.items:[],details=sourceItems.map(sanitizeCapability).filter(Boolean) as CapabilityDetail[],byId=new Map(details.map(item=>[item.id,item])),capabilities=ids.map(id=>byId.get(id)||({id,title:null,category:null,domain:null,summary:null,status:null,declared_route:null} as CapabilityDetail));for(const detail of details)if(!ids.includes(detail.id))capabilities.push(detail);return{schema:"OMEGA_V6_CAPABILITY_INDEX_V1",authority:"observation-only",boundary:CAPABILITY_BOUNDARY,evidence_timestamp:edge?.timestamp||null,manifest_digest:manifest.digest||null,manifest_agreed:Boolean(edge?.convergence?.reciprocal_manifest_ready&&manifest.digest&&edge?.convergence?.genesis_manifest_digest===manifest.digest),transport:edge?.convergence?.genesis_transport||manifest.transport||"UNPROVEN",capability_count:genesis.capability_count??capabilities.length,mode_count:manifest.mode_count??null,acceptance_gates:Array.isArray(genesis.acceptance_gates)?genesis.acceptance_gates:[],capabilities,hybrid:{pc_online:Boolean(edge?.topology?.sovereign_pc?.pc_online),heartbeat_current:Boolean(edge?.topology?.sovereign_pc?.heartbeat_current),state:edge?.topology?.sovereign_pc?.state||"UNPROVEN"}}}
function declaredView(capability:CapabilityDetail):V6View|null{const declared=(capability.declared_route||"").toLowerCase();for(const view of VIEWS)if(declared.includes(view.toLowerCase()))return view;return null}
function inferView(capability:CapabilityDetail):{view:V6View;reason:string}{const explicit=declaredView(capability);if(explicit)return{view:explicit,reason:"Genesis public capability metadata names an existing V6 specialist surface."};const corpus=[capability.id,capability.title,capability.category,capability.domain,capability.summary].filter(Boolean).join(" ").toLowerCase(),rules:Array<[V6View,RegExp,string]>=[["Earth",/earth|geo|gis|map|weather|seismic|osm|noaa|terrain|source[- ]bound/,"Earth/source vocabulary routes to the source-bound Earth specialist."],["Hybrid",/hybrid|desktop|device|heartbeat|agent|native|sovereign pc|workspace/,"Device/native vocabulary routes to the heartbeat-governed Hybrid specialist."],["Assistant",/assistant|memory|context|language|intelligence|model|synthesis|conversation|route/,"Intelligence/context vocabulary routes to the route-before-generation Assistant."],["Field",/field|calculus|operator|topolog|shell|visual|mode|relation|coherence/,"Relational/calculus vocabulary routes to the Living Field specialist."],["Proof",/proof|evidence|verify|verification|rollback|govern|ledger|audit|policy/,"Proof/governance vocabulary routes to the Proof & Rollback specialist."]];for(const[view,pattern,reason]of rules)if(pattern.test(corpus))return{view,reason};return { view: "Proof", reason: "No specialist route is evidenced by current metadata, so the conservative fallback is Proof & Rollback." }}
async function routePreview(request:Request,env:CapabilityEnv,loadEdge:EdgeLoader):Promise<Response>{const url=new URL(request.url),id=(url.searchParams.get("id")||"").trim();if(!id)return Response.json({ok:false,error:"capability_id_required"},{status:400});const index=await capabilityIndex(env,loadEdge),capability=index.capabilities.find((item:CapabilityDetail)=>item.id===id);if(!capability)return Response.json({ok:false,error:"capability_not_in_current_genome",id},{status:404});const route=inferView(capability);return Response.json({ok:true,schema:"OMEGA_V6_CAPABILITY_ROUTE_PREVIEW_V1",authority: "routing-only",route_before_generation:true,execution:false,capability,manifest_digest:index.manifest_digest,manifest_agreed:index.manifest_agreed,target:`/app/${route.view}`,specialist:route.view,reason:route.reason,boundary:CAPABILITY_BOUNDARY},{headers:{"cache-control":"no-store","x-omega-authority":"routing-only"}})}
const capabilityBrowser=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OMEGA V6 · Capability Router</title></head><body style="background:#05070b;color:#f4f7ff;font:15px system-ui"><nav><a href="/workbench">State Workbench</a> · <a href="/relations">Relations</a> · <a href="/memory">Memory / Scar / Forecast</a> · <a href="/convergence">Convergence</a></nav><h1>Capability Router</h1><p>Discovery → admitted route → specialist. Selection alone never executes or mutates canonical state.</p><input id="search" placeholder="Search capability genome"><div id="capGrid"></div><pre id="routeProof"></pre><script>let index;const q=s=>document.querySelector(s),grid=q('#capGrid');function render(){const term=q('#search').value.toLowerCase();grid.innerHTML='';for(const c of index?.capabilities||[]){if(term&&!JSON.stringify(c).toLowerCase().includes(term))continue;const b=document.createElement('button');b.textContent='Inspect + route '+(c.title||c.id);b.onclick=async()=>{const r=await fetch('/api/capability/route?id='+encodeURIComponent(c.id),{cache:'no-store'}),d=await r.json();q('#routeProof').textContent=JSON.stringify(d,null,2);if(r.ok){const a=document.createElement('a');a.href=d.target;a.textContent=' Open specialist '+d.specialist;grid.prepend(a)}};grid.append(b)}}fetch('/api/convergence/capabilities',{cache:'no-store'}).then(r=>r.json()).then(d=>{index=d;render()});q('#search').oninput=render;</script></body></html>`;
export function specialistFromPath(pathname:string):{matched:boolean;view:V6View|null}{if(!pathname.startsWith("/app/"))return{matched:false,view:null};const view=decodeURIComponent(pathname.slice(5));return{matched:true,view:isView(view)?view:null}}
export async function handleCapabilityRequest(request:Request,env:CapabilityEnv,loadEdge:EdgeLoader):Promise<Response|null>{const memory=await handleMemoryWorkbenchRequest(request);if(memory)return memory;const relations = handleRelationWorkbenchRequest(request);if(relations)return relations;const workbench = handleStateWorkbenchRequest(request);if(workbench)return workbench;const url = new URL(request.url);if(request.method!=="GET")return null;if(url.pathname === "/capabilities")return new Response(capabilityBrowser,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-omega-authority": "observation-only"}});if(url.pathname === "/api/convergence/capabilities")return Response.json(await capabilityIndex(env,loadEdge),{headers:{"cache-control":"no-store","x-omega-authority": "observation-only"}});if(url.pathname === "/api/capability/route")return routePreview(request,env,loadEdge);return null}
async function mutateHtml(response:Response,mutate:(body:string)=>string){const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;const headers=new Headers(response.headers);headers.set("cache-control","no-store");return new Response(mutate(await response.text()),{status:response.status,headers})}
export async function injectCapabilityLink(response:Response):Promise<Response>{return mutateHtml(response,body=>{let next=body;if(!next.includes('href="/capabilities"'))next=next.replace("</body>",'<a href="/capabilities" style="position:fixed;right:14px;bottom:62px;z-index:9999">CAPABILITY ROUTER</a></body>');if(!next.includes('href="/workbench"'))next=next.replace("</body>",'<a href="/workbench" style="position:fixed;right:14px;bottom:110px;z-index:9999">STATE WORKBENCH</a></body>');if(!next.includes('href="/relations"'))next=next.replace("</body>",'<a href="/relations" style="position:fixed;right:14px;bottom:158px;z-index:9999">RELATION WORKBENCH</a></body>');if(!next.includes('href="/memory"'))next=next.replace("</body>",'<a href="/memory" style="position:fixed;right:14px;bottom:206px;z-index:9999">MEMORY / SCAR</a></body>');return next})}
export async function injectSpecialistActivation(response:Response,view:V6View):Promise<Response>{return mutateHtml(response,body=>body.replace("</body>",`<script>addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('button[data-app="${view}"]');if(b instanceof HTMLElement)b.click()})</script></body>`))}
