export const EARTH_SAR_REPAIR_R198_1 = "r198.1-native-earth-stage-repair";

const css = `<style id="omegaSarIntegratedR198_1Style">
#omegaEarthTruthLayers[data-sar1981="1"] .etlTabs{grid-template-columns:repeat(5,minmax(0,1fr))}
.sar1981Tab{border:1px solid #294054;border-radius:12px;background:#08131b;color:inherit;padding:10px;cursor:pointer;text-align:left;min-width:0}.sar1981Tab small{display:block;color:#718a9d;font-size:.55rem;letter-spacing:.09em}.sar1981Tab b{display:block;margin-top:3px;font-size:.76rem}.sar1981Tab[data-active="1"]{outline:2px solid rgba(255,255,255,.12);background:#102230;border-color:#55a6bd}.sar1981Count{display:inline-block;margin-left:5px;color:#9dc9d6}
.sar1981Overlay{display:none;position:absolute;inset:0;z-index:2;background:#02070b}.sar1981Overlay[data-active="1"]{display:block}.sar1981Canvas{display:block;width:100%;height:100%}.sar1981Hud{position:absolute;left:10px;right:10px;top:10px;display:flex;justify-content:space-between;align-items:flex-start;gap:8px;pointer-events:none}.sar1981HudGroup{display:flex;gap:6px;flex-wrap:wrap;max-width:78%}.sar1981Badge{border:1px solid #31566a;border-radius:999px;background:#041019e8;padding:5px 8px;font:800 .55rem ui-monospace,monospace;color:#b9cfda;backdrop-filter:blur(8px)}.sar1981Badge.ok{border-color:#3c766d}.sar1981Badge.warn{border-color:#75574b}.sar1981Select{pointer-events:auto;border:1px solid #31566a;border-radius:9px;background:#071620;color:#dcebf1;padding:6px 8px;font:800 .56rem ui-monospace,monospace}.sar1981Controls{position:absolute;left:10px;right:10px;bottom:10px;z-index:3;display:flex;gap:6px;flex-wrap:wrap;align-items:center}.sar1981Provider{border:1px solid #35576a;border-radius:999px;background:#071620dd;color:#c7d8df;padding:6px 8px;font:800 .55rem ui-monospace,monospace;cursor:pointer;backdrop-filter:blur(8px)}.sar1981Provider[data-on="1"]{background:#143044;border-color:#6595aa;color:#fff}.sar1981Provider:disabled{opacity:.45}.sar1981Refresh{margin-left:auto;border:1px solid #456d80;border-radius:999px;background:#0e2632dd;color:#dcebf1;padding:6px 9px;font:850 .55rem ui-monospace,monospace;cursor:pointer}.sar1981Refresh:disabled{opacity:.5}
.sar1981Ledger{margin-top:10px;border-top:1px solid #203748;padding-top:9px}.sar1981Metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.sar1981Metric{border:1px solid #253f50;border-radius:10px;background:#081720;padding:7px}.sar1981Metric small{display:block;color:#718a9d;font-size:.49rem;letter-spacing:.07em}.sar1981Metric b{display:block;margin-top:2px;font:800 .65rem ui-monospace,monospace;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sar1981Selected{margin-top:7px;border:1px solid #263f50;border-radius:10px;background:#07141c;padding:8px;min-height:38px}.sar1981Selected b{display:block;font-size:.63rem}.sar1981Selected span{display:block;margin-top:2px;color:#7e96a5;font-size:.55rem;line-height:1.35}.sar1981Proof{white-space:pre-wrap;max-height:180px;overflow:auto;font:9px/1.42 ui-monospace,monospace;color:#8fa7b6}.sar1981Boundary{margin-top:6px;color:#6f8795;font-size:.54rem;line-height:1.4}
@media(max-width:900px){#omegaEarthTruthLayers[data-sar1981="1"] .etlTabs{display:flex;overflow-x:auto}.sar1981Tab{min-width:170px;flex:0 0 auto}.sar1981HudGroup{max-width:70%}}
@media(max-width:620px){.sar1981Hud{left:7px;right:7px;top:7px}.sar1981Controls{left:7px;right:7px;bottom:7px}.sar1981Metrics{grid-template-columns:1fr 1fr}.sar1981Badge.optional{display:none}.sar1981Refresh{margin-left:0}.sar1981Provider{padding:5px 7px}.sar1981Select{max-width:92px}}
</style>`;

const script = `<script id="omegaSarIntegratedR198_1Runtime">(()=>{
const root=document.querySelector('#omegaEarthTruthLayers');if(!root||root.dataset.sar1981==='1')return;root.dataset.sar1981='1';
const q=s=>root.querySelector(s),qa=s=>Array.from(root.querySelectorAll(s)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=q('.etlTabs'),stage=q('.etlStage'),panel=q('.etlPanel'),baseCanvas=q('#etlCanvas'),baseLegend=q('.etlLegend');if(!tabs||!stage||!panel||!baseCanvas)return;
const tab=document.createElement('button');tab.className='sar1981Tab';tab.type='button';tab.dataset.active='0';tab.innerHTML='<small>OBSERVED_SOURCE · SAR</small><b>Real radar <span class="sar1981Count" id="sar1981TabCount">—</span></b>';tabs.appendChild(tab);
const overlay=document.createElement('div');overlay.className='sar1981Overlay';overlay.dataset.active='0';overlay.innerHTML='<canvas class="sar1981Canvas" id="sar1981Canvas"></canvas><div class="sar1981Hud"><div class="sar1981HudGroup"><span class="sar1981Badge" id="sar1981Status">SAR · UNQUERIED</span><span class="sar1981Badge optional">SOURCE GEOMETRY ONLY</span><span class="sar1981Badge optional">NO SYNTHETIC FOOTPRINTS</span></div><select class="sar1981Select" id="sar1981Days" aria-label="SAR time window"><option value="7">7 DAYS</option><option value="30" selected>30 DAYS</option><option value="90">90 DAYS</option><option value="365">1 YEAR</option></select></div><div class="sar1981Controls"><button class="sar1981Provider" data-sar-p="sentinel1" data-on="1">S1 · C</button><button class="sar1981Provider" data-sar-p="nisar" data-on="1">NISAR · L/S</button><button class="sar1981Provider" data-sar-p="umbra" data-on="1">UMBRA · X</button><button class="sar1981Provider" data-sar-p="capella" data-on="1">CAPELLA · X</button><button class="sar1981Provider" data-sar-p="iceye" data-on="1">ICEYE · X</button><button class="sar1981Refresh" id="sar1981Refresh">REFRESH SOURCES</button></div>';stage.appendChild(overlay);
const ledger=document.createElement('div');ledger.className='sar1981Ledger';ledger.innerHTML='<div class="etlEy">REAL SAR · SOURCE FRAME</div><div class="sar1981Metrics"><div class="sar1981Metric"><small>GEOREFERENCED</small><b id="sar1981Geo">0</b></div><div class="sar1981Metric"><small>LATEST SOURCE TIME</small><b id="sar1981Latest">—</b></div><div class="sar1981Metric"><small>SENSOR FAMILIES</small><b id="sar1981Families">0</b></div></div><div class="sar1981Selected" id="sar1981Selected"><b>No SAR record selected.</b><span>Select a source footprint in REAL SAR view for exact returned metadata.</span></div><details style="margin-top:7px"><summary class="etlEy">SAR provenance / frame proof</summary><pre class="sar1981Proof" id="sar1981Proof">Unqueried.</pre></details><div class="sar1981Boundary">R198.1 keeps SAR as an observed source channel inside the existing Earth truth instrument. Geographic footprint and acquisition time are displayed only when returned by the source catalog. Display projection is derived. Inference, displacement and forecast remain withheld unless separately proven.</div>';
const before=panel.querySelector('.etlBoundary')||null;panel.insertBefore(ledger,before);
let active=false,busy=false,data=null,hit=[],selected=null;const providers=new Set(['sentinel1','nisar','umbra','capella','iceye']);
const colors={sentinel1:'#e6bd4e',nisar:'#55cc84',umbra:'#ef6a65',capella:'#a67cff',iceye:'#5d98ff'};
function setSar(on){active=on;tab.dataset.active=on?'1':'0';overlay.dataset.active=on?'1':'0';baseCanvas.style.visibility=on?'hidden':'';if(baseLegend)baseLegend.style.visibility=on?'hidden':'';if(on){qa('[data-etl-view]').forEach(b=>b.dataset.active='0');draw()} }
qa('[data-etl-view]').forEach(b=>b.addEventListener('click',()=>setSar(false),true));tab.addEventListener('click',()=>setSar(true));
function fit(c){const r=c.getBoundingClientRect(),D=Math.min(2,devicePixelRatio||1),x=c.getContext('2d');c.width=Math.max(1,Math.round(r.width*D));c.height=Math.max(1,Math.round(r.height*D));x.setTransform(D,0,0,D,0,0);return{x,W:r.width,H:r.height}}
function xy(lon,lat,W,H){return[(Number(lon)+180)/360*W,(90-Number(lat))/180*H]}
function draw(){if(!active)return;const c=q('#sar1981Canvas');if(!c)return;const {x,W,H}=fit(c);hit=[];x.fillStyle='#02070b';x.fillRect(0,0,W,H);const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071822');g.addColorStop(.5,'#091c24');g.addColorStop(1,'#051016');x.fillStyle=g;x.fillRect(0,0,W,H);x.strokeStyle='rgba(147,185,198,.13)';x.lineWidth=1;for(let lon=-180;lon<=180;lon+=30){const[p]=xy(lon,0,W,H);x.beginPath();x.moveTo(p,0);x.lineTo(p,H);x.stroke()}for(let lat=-60;lat<=60;lat+=30){const[,p]=xy(0,lat,W,H);x.beginPath();x.moveTo(0,p);x.lineTo(W,p);x.stroke()}x.strokeStyle='rgba(197,220,228,.25)';x.strokeRect(.5,.5,W-1,H-1);const obs=Array.isArray(data?.observations)?data.observations:[];for(const o of obs){if(!providers.has(o.provider)||!Array.isArray(o.bbox)||o.bbox.length<4)continue;const b=o.bbox,[x0,y1]=xy(b[0],b[1],W,H),[x1,y0]=xy(b[2],b[3],W,H),w=Math.max(2,x1-x0),h=Math.max(2,y1-y0),col=colors[o.provider]||'#b9d0da';x.fillStyle=col+'20';x.strokeStyle=selected?.id===o.id?'#ffffff':col;x.lineWidth=selected?.id===o.id?2:1.15;x.fillRect(x0,y0,w,h);x.strokeRect(x0,y0,w,h);hit.push({o,x:x0,y:y0,w,h})}x.fillStyle='#91a7b4';x.font='800 9px ui-monospace,monospace';x.textAlign='right';x.fillText('EQUIRECTANGULAR DISPLAY · SOURCE BBOX',W-10,H-13)}
function visible(){return (Array.isArray(data?.observations)?data.observations:[]).filter(o=>providers.has(o.provider))}
function render(){const obs=visible(),geo=obs.filter(o=>Array.isArray(o.bbox)),times=obs.map(o=>Date.parse(o.datetime||'')).filter(Number.isFinite).sort((a,b)=>b-a),families=new Set(obs.map(o=>o.provider));q('#sar1981Geo').textContent=String(geo.length);q('#sar1981Latest').textContent=times.length?new Date(times[0]).toISOString().slice(0,10):'WITHHELD';q('#sar1981Families').textContent=String(families.size);q('#sar1981TabCount').textContent=String(geo.length);q('#sar1981Status').textContent=data?'SAR · '+geo.length+' GEOREFERENCED':'SAR · UNQUERIED';q('#sar1981Status').className='sar1981Badge '+(data?'ok':'warn');q('#sar1981Proof').textContent=JSON.stringify({patch:'r198.1-native-earth-stage-repair',build:data?.build||null,query:data?.query||null,provider_results:data?.provider_results||null,truth_boundary:data?.truth_boundary||null,display_projection:'DERIVED_FRAMEWORK_MATH / equirectangular from source bbox',coordinates:'SOURCE_GEOMETRY only',inference:'WITHHELD',insar_displacement:'WITHHELD',forecast:'WITHHELD'},null,2);draw()}
function selectObs(o){selected=o;if(!o){q('#sar1981Selected').innerHTML='<b>No SAR record selected.</b><span>Select a source footprint for returned metadata.</span>';return}q('#sar1981Selected').innerHTML='<b>'+esc(o.provider_label)+' · '+esc(o.id)+'</b><span>'+esc(o.datetime||'time withheld')+' · '+esc(o.band)+'-band · '+esc((o.polarization||[]).join('/')||'polarization unreported')+' · '+esc(o.orbit_state||'orbit unreported')+' · resolution '+esc(o.resolution_m==null?'unreported':o.resolution_m+' m')+' · geometry '+esc(o.calibration?.coordinate_authority||'WITHHELD')+'</span>';draw()}
q('#sar1981Canvas').addEventListener('click',e=>{if(!active)return;const r=e.currentTarget.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;const candidates=hit.filter(h=>px>=h.x&&px<=h.x+h.w&&py>=h.y&&py<=h.y+h.h);if(!candidates.length){selectObs(null);return}candidates.sort((a,b)=>(a.w*a.h)-(b.w*b.h));selectObs(candidates[0].o)});
async function load(){if(busy)return;busy=true;q('#sar1981Refresh').disabled=true;q('#sar1981Status').textContent='SAR · QUERYING SOURCES';try{const days=Number(q('#sar1981Days').value)||30,ps=Array.from(providers).join(','),u='/api/earth/sar/r198/search?days='+encodeURIComponent(days)+'&limit=24&providers='+encodeURIComponent(ps),r=await fetch(u,{cache:'no-store',headers:{accept:'application/json'}}),t=await r.text();if(!r.ok)throw new Error('HTTP '+r.status+' '+t.slice(0,180));data=JSON.parse(t);render()}catch(e){data=null;q('#sar1981Status').textContent='SAR · SOURCE DEGRADED';q('#sar1981Status').className='sar1981Badge warn';q('#sar1981Proof').textContent=String(e);q('#sar1981TabCount').textContent='!';draw()}finally{busy=false;q('#sar1981Refresh').disabled=false}}
qa('[data-sar-p]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.sarP;if(providers.has(p))providers.delete(p);else providers.add(p);b.dataset.on=providers.has(p)?'1':'0';render()}));q('#sar1981Refresh').addEventListener('click',load);q('#sar1981Days').addEventListener('change',load);addEventListener('resize',draw,{passive:true});load();
})();</script>`;

export async function enhanceEarthSarIntegratedRepairR198_1(response: Response, requestUrl: string): Promise<Response> {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  const url = new URL(requestUrl);
  const app = (url.searchParams.get("app") || "").toLowerCase();
  const earthRoute = app === "earth" || url.pathname === "/earth" || url.pathname.startsWith("/earth/");
  let html = await response.text();
  const hasEarthInstrument = html.includes('id="omegaEarthTruthLayers"');
  if (!hasEarthInstrument) return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  if (!earthRoute && app && app !== "earth") return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  if (html.includes("omegaSarIntegratedR198_1Runtime")) return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  html = html.includes("</head>") ? html.replace("</head>", css + "</head>") : css + html;
  html = html.includes("</body>") ? html.replace("</body>", script + "</body>") : html + script;
  const headers = new Headers(response.headers);
  headers.set("cache-control", "no-store");
  headers.set("x-omega-earth-sar-ui", EARTH_SAR_REPAIR_R198_1);
  return new Response(html, { status: response.status, statusText: response.statusText, headers });
}
