export const FIELD_EXPERIENCE_BOUNDARY = "R164 keeps Field living and state-bound without erasing the workstation around it. Motion remains driven by canonical state controls, governed operator semantics and time; truth, x-ray channels, replay, shell context and expert controls stay recoverable as layered instruments. Visualization is not empirical evidence or a second state authority.";

const style=`<style id="omegaFieldExperienceStyle">
html.omega-field-focus #omegaSpatialCore,html.omega-field-focus #omegaLivePhaseRail{opacity:.22;filter:saturate(.75);transition:opacity .18s ease,filter .18s ease}html.omega-field-focus #omegaSpatialCore:hover,html.omega-field-focus #omegaSpatialCore:focus-within,html.omega-field-focus #omegaLivePhaseRail:hover,html.omega-field-focus #omegaLivePhaseRail:focus-within{opacity:1;filter:none}
html.omega-field-focus .archiveWorkstation{margin:8px 0 18px;border-radius:18px}
html.omega-field-focus .archiveWorkstation .awTop{padding:13px 16px 11px}
html.omega-field-focus .archiveWorkstation .awTop h2{font-size:clamp(1.25rem,2.2vw,2rem);margin:2px 0}
html.omega-field-focus .archiveWorkstation .awTop p{display:block;max-width:760px;color:#8195ad}html.omega-field-focus .archiveWorkstation .awTruth{display:grid}
html.omega-field-focus .archiveWorkstation .awToolbar{padding:8px 12px}
html.omega-field-focus .archiveWorkstation .awStage{grid-template-columns:minmax(0,1fr) 250px;min-height:0}
html.omega-field-focus .archiveWorkstation .awViewport{min-height:clamp(520px,70vh,880px)!important}
html.omega-field-focus .archiveWorkstation .awPanel{padding:10px}
html.omega-field-focus .archiveWorkstation .awSection{margin-top:9px;padding-top:8px}
#omegaFieldFocusBar{display:none}#offControls{border:1px solid #35506e;border-radius:999px;background:#0a1624;color:#dbe8f7;padding:6px 9px;font:800 9px ui-monospace,monospace;letter-spacing:.06em;cursor:pointer}#offControls[aria-expanded="true"]{border-color:#7898bd;background:#17283b}
html.omega-field-focus #omegaFieldFocusBar{display:flex;align-items:center;gap:8px;margin:4px 0 8px;padding:8px 10px;border:1px solid #263d59;border-radius:13px;background:rgba(4,9,15,.82);backdrop-filter:blur(18px)}
.offEy{font:800 9px ui-monospace,monospace;letter-spacing:.12em;color:#7890ad}.offState{font:800 10px ui-monospace,monospace;color:#eaf2ff}.offHint{margin-left:auto;color:#72849b;font:9px ui-monospace,monospace}.offPulse{width:8px;height:8px;border-radius:50%;background:#42cb7c;box-shadow:0 0 14px #42cb7c88}
@media(max-width:760px){html.omega-field-focus .archiveWorkstation .awStage{grid-template-columns:1fr}html.omega-field-focus .archiveWorkstation .awViewport{min-height:calc(100svh - 300px)!important}html.omega-field-focus .archiveWorkstation .awPanel{display:block;position:fixed;left:8px;right:8px;bottom:calc(78px + env(safe-area-inset-bottom));z-index:125;max-height:68svh;overflow:auto;border:1px solid #2d4664;border-radius:18px;background:rgba(5,12,20,.97);box-shadow:0 28px 90px #000b;transform:translateY(calc(100% + 120px));transition:transform .2s ease}html.omega-field-panel-open .archiveWorkstation .awPanel{transform:none}.offHint{display:none}#offControls{margin-left:auto;min-height:36px}}
</style>`;
const bar=`<div id="omegaFieldFocusBar"><span class="offPulse"></span><span class="offEy">LIVING FIELD</span><span class="offState" id="offState">STATE-BOUND MOTION</span><span class="offHint">drag · zoom · x-ray · replay · atlas remain available</span><button id="offControls" type="button" aria-expanded="false">FIELD CONTROLS</button></div>`;
const runtime=`<script id="omegaFieldExperienceRuntime">(()=>{if(window.__omegaFieldExperience)return;window.__omegaFieldExperience=true;const p=new URLSearchParams(location.search),view=(p.get('view')||'Field').toLowerCase(),field=view==='field'||view==='';document.documentElement.classList.toggle('omega-field-focus',field);if(!field)return;const controls=document.querySelector('#offControls');if(controls){controls.onclick=()=>{const on=!document.documentElement.classList.contains('omega-field-panel-open');document.documentElement.classList.toggle('omega-field-panel-open',on);controls.setAttribute('aria-expanded',String(on));controls.textContent=on?'CLOSE CONTROLS':'FIELD CONTROLS'}}const ws=document.querySelector('#archiveWorkstation');if(ws){const h=ws.querySelector('.awTop h2');if(h)h.textContent='Living Field';const ey=ws.querySelector('.awEy');if(ey)ey.textContent='ONE CANONICAL PACKET · STATE / TIME / OPERATOR MOTION';const live=ws.querySelector('[data-aw-lens="live"]');if(live&&!live.classList.contains('active'))live.click()}const state=document.querySelector('#offState');function sync(){const mode=document.querySelector('#hdMode')?.textContent?.trim()||document.querySelector('[data-mode].active')?.textContent?.trim()||'BASE';const op=document.querySelector('#hdOperator')?.textContent?.trim()||'OMEGA';if(state)state.textContent=mode+' · '+op+' · LIVE'}sync();setInterval(sync,1200);document.documentElement.dataset.omegaFieldExperience='r164'})();</script>`;
export async function enhanceFieldExperience(response:Response):Promise<Response>{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('OMEGA V6')||html.includes('omegaFieldExperienceRuntime'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});html=html.replace('</head>',style+'</head>');const target=html.includes('<main class="work">')?'<main class="work">':html.includes('<main class="wrap">')?'<main class="wrap">':'<body>';html=html.replace(target,target+bar);html=html.replace('</body>',runtime+'</body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});}
