export const FIELD_EXPERIENCE_BOUNDARY = "R166 keeps the living Field clean without discarding depth. The primary canvas owns normal interaction; X-ray, Atlas, Split, Replay and channel controls move into an explicit Advanced Tools drawer opened from the Field toolbar. Those tools remain functional and state-bound, but no longer duplicate the primary renderer in the normal layout.";

const style=`<style id="omegaFieldExperienceStyle">
#omegaFieldFocusBar{display:none!important}
html.omega-field-focus .archiveWorkstation{position:fixed!important;z-index:140;right:14px;top:78px;bottom:14px;width:min(860px,calc(100vw - 28px));max-height:calc(100svh - 92px);margin:0!important;border-radius:20px!important;overflow:auto!important;background:#050b12!important;box-shadow:0 34px 110px #000d!important;transform:translateX(calc(100% + 42px));opacity:0;pointer-events:none;transition:transform .22s ease,opacity .18s ease}
html.omega-field-tools-open .archiveWorkstation{transform:none;opacity:1;pointer-events:auto}
html.omega-field-focus .archiveWorkstation .awTop{padding:13px 16px 11px}
html.omega-field-focus .archiveWorkstation .awTop h2{font-size:clamp(1.2rem,2vw,1.8rem);margin:2px 0}
html.omega-field-focus .archiveWorkstation .awTop p{display:block;max-width:760px;color:#8195ad}
html.omega-field-focus .archiveWorkstation .awTruth{display:grid}
html.omega-field-focus .archiveWorkstation .awToolbar{position:sticky;top:0;z-index:20;padding:8px 12px;background:rgba(5,11,18,.96);backdrop-filter:blur(18px)}
html.omega-field-focus .archiveWorkstation .awStage{grid-template-columns:minmax(0,1fr) 280px;min-height:0}
html.omega-field-focus .archiveWorkstation .awViewport{min-height:clamp(480px,64vh,760px)!important}
html.omega-field-focus .archiveWorkstation .awPanel{padding:10px}
html.omega-field-focus .archiveWorkstation .awSection{margin-top:9px;padding-top:8px}
#awCloseTools{border:1px solid #405b79;border-radius:999px;background:#0a1623;color:#dce8f6;padding:7px 10px;font-size:.68rem;font-weight:850;cursor:pointer}
@media(max-width:760px){html.omega-field-focus .archiveWorkstation{left:8px;right:8px;top:max(58px,env(safe-area-inset-top));bottom:calc(78px + env(safe-area-inset-bottom));width:auto;max-height:none;border-radius:17px!important;transform:translateY(calc(100% + 110px))}html.omega-field-tools-open .archiveWorkstation{transform:none}html.omega-field-focus .archiveWorkstation .awStage{grid-template-columns:1fr}html.omega-field-focus .archiveWorkstation .awViewport{min-height:48svh!important}html.omega-field-focus .archiveWorkstation .awPanel{display:block;position:static;max-height:none;overflow:visible;border-left:0;border-top:1px solid #1f3047;border-radius:0;background:#07101a;box-shadow:none;transform:none}}
@media(prefers-reduced-motion:reduce){html.omega-field-focus .archiveWorkstation{transition:none}}
</style>`;
const bar=`<div id="omegaFieldFocusBar" aria-hidden="true"><span class="offEy">FIELD CONTROLS</span></div>`;
const runtime=`<script id="omegaFieldExperienceRuntime">(()=>{if(window.__omegaFieldExperience)return;window.__omegaFieldExperience=true;const p=new URLSearchParams(location.search),view=(p.get('view')||'Field').toLowerCase(),field=view==='field'||view==='';document.documentElement.classList.toggle('omega-field-focus',field);if(!field)return;const root=document.documentElement,ws=document.querySelector('#archiveWorkstation'),tools=document.querySelector('#gmaToolsToggle');function setTools(on){root.classList.toggle('omega-field-tools-open',on);if(tools){tools.classList.toggle('active',on);tools.setAttribute('aria-expanded',String(on));tools.textContent=on?'CLOSE':'TOOLS'}document.dispatchEvent(new CustomEvent('omega-archive-visible',{detail:{visible:on}}))}document.addEventListener('omega-field-tools',()=>setTools(!root.classList.contains('omega-field-tools-open')));addEventListener('keydown',e=>{if(e.key==='Escape'&&root.classList.contains('omega-field-tools-open'))setTools(false)});if(ws){const h=ws.querySelector('.awTop h2');if(h)h.textContent='Advanced Field Tools';const ey=ws.querySelector('.awEy');if(ey)ey.textContent='X-RAY · ATLAS · SPLIT · REPLAY · CHANNEL CONTROLS';const p=ws.querySelector('.awTop p');if(p)p.textContent='Deep inspection tools for the same live state. Open them when needed; they do not create a second state or renderer authority.';const toolbar=ws.querySelector('.awToolbar');if(toolbar&&!ws.querySelector('#awCloseTools')){const close=document.createElement('button');close.type='button';close.id='awCloseTools';close.textContent='CLOSE';close.onclick=()=>setTools(false);toolbar.appendChild(close)}}setTools(false);document.documentElement.dataset.omegaFieldExperience='r166'})();</script>`;
export async function enhanceFieldExperience(response:Response):Promise<Response>{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('OMEGA V6')||html.includes('omegaFieldExperienceRuntime'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});html=html.replace('</head>',style+'</head>');const target=html.includes('<main class="work">')?'<main class="work">':html.includes('<main class="wrap">')?'<main class="wrap">':'<body>';html=html.replace(target,target+bar);html=html.replace('</body>',runtime+'</body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});}
