export const GOVERNED_MODE_ATLAS_BOUNDARY =
  "R167 binds Field state metrics to the canonical /api/omega/state contract instead of inventing fallback values. Continuity, future plasticity, contradiction, burden, dispatch, evidence class, digest and Address20736 are shown only when returned by the sovereign runtime. The renderer remains one presentation-only governed Field renderer. It may use a neutral presentation basis while state is unavailable, but that basis is explicitly unbound and is never presented as canonical state. 20,736 is a software/model state atlas, not a physical dimension claim.";

const MODES = [
  ["full-overall-canon", "FULL CANON", "constitutional synthesis + admissibility"],
  ["mode-188", "MODE 188", "prune / dispatch / contradiction audit"],
  ["unified-coherence", "COHERENCE", "relation consistency + contradiction"],
  ["forecast", "FORECAST", "bounded future alternatives"],
  ["full-sphere", "FULL SPHERE", "recursive multi-perspective shell"],
  ["relational-skin", "SKIN", "boundary / scar / continuity shaping"],
  ["dewey-calculus", "CALCULUS", "trajectory / curvature / sensitivity"],
  ["unified-recursion", "RECURSION", "parent-child continuity hierarchy"],
  ["deep-mother", "RECOVERY", "recoverability + continuity weighting"],
  ["high-father", "CONSTRAINT", "boundary + law weighting"],
  ["heavy-prune", "PRUNE", "constraint removal / simplification"],
  ["alpha", "ALPHA", "exploration / plasticity emphasis"],
  ["crimson", "CRIMSON", "construction / consequence emphasis"],
  ["no-nothing-truth", "TRUTH", "evidence / contradiction exposure"],
  ["guidance-field", "GUIDANCE", "bounded directional projection"],
] as const;

const css = `<style id="omegaGovernedModeAtlasStyle">
html.omega-root-field-active #omegaRootSovereignField{min-height:100svh;border:0;border-radius:0;background:#010308;box-shadow:none}
html.omega-root-field-active #omegaRootSovereignField>.orsfStage>canvas,
html.omega-root-field-active #omegaRootSovereignField>.orsfStage>.orsfVeil,
html.omega-root-field-active #omegaRootSovereignField>.orsfStage>.orsfAxis,
html.omega-root-field-active #omegaRootSovereignField>.orsfTop,
html.omega-root-field-active #omegaRootSovereignField>.orsfPhaseTrack,
html.omega-root-field-active #omegaRootSovereignField>.orsfBottom{display:none!important}
#gma{position:absolute;inset:0;overflow:hidden;background:#010308;color:#edf5ff;font-family:Inter,system-ui,sans-serif;isolation:isolate}
.gmaCenter,.gmaViewport{position:absolute;inset:0;min-width:0;overflow:hidden}
.gmaViewport{background:radial-gradient(circle at 50% 48%,#0b1825 0,#03070d 58%,#010205 100%)}
.gmaViewport:after{content:"";position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 48%,transparent 0 45%,rgba(0,0,0,.22) 72%,rgba(0,0,0,.68) 100%),linear-gradient(rgba(140,176,221,.022) 1px,transparent 1px),linear-gradient(90deg,rgba(140,176,221,.022) 1px,transparent 1px);background-size:auto,48px 48px,48px 48px;mix-blend-mode:screen}
.gmaViewport canvas{position:absolute;inset:0;width:100%;height:100%;display:block;cursor:grab;touch-action:none;user-select:none}
.gmaViewport canvas.is-dragging{cursor:grabbing}
.gmaHead{position:absolute;z-index:12;left:18px;right:18px;top:82px;display:flex;align-items:flex-start;justify-content:space-between;gap:12px;pointer-events:none}
.gmaIdentity,.gmaActions{pointer-events:auto;border:1px solid rgba(92,129,174,.34);background:rgba(3,8,15,.72);backdrop-filter:blur(18px) saturate(1.15);box-shadow:0 16px 48px rgba(0,0,0,.34)}
.gmaIdentity{min-width:0;padding:10px 13px;border-radius:15px}.gmaTitleLine{display:flex;align-items:center;gap:8px}.gmaPulse{width:7px;height:7px;border-radius:50%;background:#42cb7c;box-shadow:0 0 18px rgba(66,203,124,.9);animation:gmaPulse 1.8s ease-in-out infinite}.gmaTitle{font:850 11px/1.1 ui-monospace,monospace;letter-spacing:.12em}.gmaSub{margin-top:5px;color:#7890a8;font:650 8px/1.2 ui-monospace,monospace;letter-spacing:.07em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gmaClock{color:#e6c86b}
.gmaActions{display:flex;gap:5px;padding:5px;border-radius:14px}.gmaAction{min-height:34px;border:1px solid transparent;border-radius:10px;background:transparent;color:#9eb2c8;padding:7px 9px;cursor:pointer;font:800 8px/1 ui-monospace,monospace;letter-spacing:.06em}.gmaAction:hover,.gmaAction:focus-visible,.gmaAction.active{border-color:#436181;background:#102033;color:#fff;outline:none}.gmaAction[data-state="paused"]{border-color:#7b6431;color:#f0d377;background:#1b160c}
.gmaFoot{position:absolute;z-index:11;left:50%;bottom:18px;translate:-50% 0;display:flex;align-items:center;gap:6px;max-width:calc(100% - 36px);padding:6px;border:1px solid rgba(78,111,151,.34);border-radius:999px;background:rgba(3,8,14,.76);backdrop-filter:blur(18px);box-shadow:0 16px 45px rgba(0,0,0,.38);overflow-x:auto;scrollbar-width:none}.gmaFoot::-webkit-scrollbar{display:none}.gmaTag{white-space:nowrap;border:1px solid #26394e;border-radius:999px;padding:5px 8px;color:#8fa4b9;font:750 8px ui-monospace,monospace}.gmaTag b{color:#eef6ff}.gmaTag.live{border-color:#24573c;color:#72dca0}.gmaTag.model{border-color:#624d20;color:#e6c96d}
.gmaGesture{position:absolute;z-index:8;left:50%;bottom:74px;translate:-50% 0;color:rgba(200,218,237,.65);font:700 8px/1.2 ui-monospace,monospace;letter-spacing:.08em;text-align:center;pointer-events:none;transition:.35s opacity,.35s transform}.gmaGesture.used{opacity:0;transform:translateY(6px)}
.gmaRail,.gmaInfo,.gmaLayerPanel{position:absolute;z-index:20;top:138px;bottom:70px;border:1px solid rgba(84,119,161,.4);border-radius:18px;background:rgba(3,8,14,.93);backdrop-filter:blur(24px) saturate(1.18);box-shadow:0 28px 90px rgba(0,0,0,.62);overflow:auto;opacity:0;pointer-events:none;transition:.2s opacity,.2s transform}
.gmaRail{left:18px;width:min(270px,calc(100% - 36px));padding:10px;transform:translateX(-12px)}.gmaInfo{right:18px;width:min(330px,calc(100% - 36px));padding:11px;transform:translateX(12px)}.gmaLayerPanel{right:18px;width:min(300px,calc(100% - 36px));padding:11px;transform:translateX(12px)}
#gma.gma-modes-open .gmaRail,#gma.gma-details-open .gmaInfo,#gma.gma-layers-open .gmaLayerPanel{opacity:1;pointer-events:auto;transform:none}
.gmaRailHead{position:sticky;top:-10px;z-index:2;display:flex;justify-content:space-between;align-items:center;margin:-2px -2px 7px;padding:10px 8px 8px;background:linear-gradient(rgba(3,8,14,.98) 70%,transparent);color:#dce8f5;font:850 9px ui-monospace,monospace;letter-spacing:.12em}.gmaRailClose{border:0;background:transparent;color:#8195aa;cursor:pointer;font-size:16px}
.gmaMode{width:100%;display:grid;gap:3px;border:1px solid transparent;border-radius:11px;background:transparent;color:#8ea3b8;padding:9px 10px;margin:2px 0;text-align:left;cursor:pointer}.gmaMode b{font:800 9px/1.15 ui-monospace,monospace;letter-spacing:.05em}.gmaMode small{color:#64798f;font-size:8px}.gmaMode:hover{background:#0c1622;color:#e8f2fc}.gmaMode.active{border-color:#476687;background:linear-gradient(135deg,#112238,#0b1622);color:#fff;box-shadow:inset 3px 0 #e6c86b}.gmaMode.active small{color:#9eb3c9}
.gmaCard{border:1px solid #20344a;border-radius:13px;background:#07111b;margin-bottom:9px;padding:11px}.gmaCard h4{margin:0 0 9px;color:#9ab0c6;font:850 9px ui-monospace,monospace;letter-spacing:.1em}.gmaMetric{display:grid;grid-template-columns:1fr auto;gap:6px 10px;font:650 9px ui-monospace,monospace;color:#71869c}.gmaMetric b{color:#f4f7fa}.gmaBars{display:grid;gap:5px}.gmaBar{display:grid;grid-template-columns:76px 1fr 34px;align-items:center;gap:6px;font:650 8px ui-monospace,monospace;color:#8094aa}.gmaBar i{height:4px;background:#14202d;border-radius:9px;overflow:hidden}.gmaBar i:after{content:"";display:block;height:100%;width:var(--v);background:linear-gradient(90deg,#315f8c,#79a6d2,#e6c86b,#67d29a)}.gmaEvidence{font:650 8px/1.5 ui-monospace,monospace;color:#8296aa}.gmaEvidence strong{color:#fff}.gmaLayerGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.gmaLayer{display:grid;gap:3px;min-height:54px;padding:9px;border:1px solid #263d55;border-radius:11px;background:#07111b;color:#9bb0c5;text-align:left;cursor:pointer}.gmaLayer b{font:850 9px ui-monospace,monospace;letter-spacing:.05em}.gmaLayer small{font:650 8px/1.25 ui-monospace,monospace;color:#657b92}.gmaLayer[aria-pressed="true"]{border-color:#4e7196;background:linear-gradient(135deg,#11243a,#0a1724);color:#fff;box-shadow:inset 3px 0 #6fd5a0}.gmaLayer[aria-pressed="false"]{opacity:.55}.gmaLayerTruth{margin-top:9px;padding:9px;border:1px solid #20354b;border-radius:10px;color:#748ba2;font:650 8px/1.45 ui-monospace,monospace}
@keyframes gmaPulse{50%{opacity:.45;transform:scale(.78)}}
@media(max-width:760px){.gmaHead{top:12px;left:10px;right:10px}.gmaIdentity{padding:9px 10px;max-width:46%}.gmaSub{display:none}.gmaActions{gap:2px;padding:4px}.gmaAction{min-width:40px;min-height:42px;padding:7px 7px}.gmaActionText{display:none}.gmaFoot{bottom:80px;max-width:calc(100% - 20px)}.gmaGesture{bottom:142px}.gmaRail,.gmaInfo,.gmaLayerPanel{top:70px;bottom:144px;left:10px;right:10px;width:auto;max-width:none;transform:translateY(10px)}#gma.gma-modes-open .gmaRail,#gma.gma-details-open .gmaInfo,#gma.gma-layers-open .gmaLayerPanel{transform:none}.gmaTag.model,.gmaTag.source{display:none}.gmaLayerGrid{grid-template-columns:1fr 1fr}}
@media(max-width:390px){.gmaTitle{font-size:9px}.gmaAction{min-width:38px;padding-inline:6px}.gmaTag{font-size:7px;padding:5px 7px}}
@media(prefers-reduced-motion:reduce){.gmaPulse{animation:none}.gmaRail,.gmaInfo,.gmaGesture{transition:none}}
</style>`;

const markup = `<div id="gma" data-evidence="USER_DEFINED_MODEL" data-paused="false">
  <section class="gmaCenter">
    <div class="gmaViewport"><canvas id="gmaCanvas" aria-label="Interactive living OMEGA field; drag to explore and use wheel or pinch to zoom"></canvas><div class="gmaGesture" id="gmaGesture">DRAG TO EXPLORE · WHEEL / PINCH TO ZOOM · DOUBLE-TAP TO RESET</div></div>
    <header class="gmaHead">
      <div class="gmaIdentity"><div class="gmaTitleLine"><i class="gmaPulse"></i><div class="gmaTitle" id="gmaTitle">LIVING FIELD</div></div><div class="gmaSub">MODE <span id="gmaModeName">FULL CANON</span> · <span id="gmaUtc" class="gmaClock">—</span> UTC</div></div>
      <div class="gmaActions" aria-label="Field controls"><button class="gmaAction" id="gmaModeToggle" aria-expanded="false">MODE</button><button class="gmaAction" id="gmaLayerToggle" aria-expanded="false">LAYERS</button><button class="gmaAction" id="gmaPause" aria-pressed="false" title="Pause field motion">Ⅱ <span class="gmaActionText">PAUSE</span></button><button class="gmaAction" id="gmaReset" title="Reset view">↺ <span class="gmaActionText">RESET</span></button><button class="gmaAction" id="gmaDetailsToggle" aria-expanded="false">DETAILS</button><button class="gmaAction" id="gmaToolsToggle" aria-expanded="false">TOOLS</button><button class="gmaAction" id="gmaFullscreen" title="Fullscreen field">⛶</button></div>
    </header>
    <footer class="gmaFoot"><span class="gmaTag live">STATUS <b id="gmaRuntime">CONNECTING</b></span><span class="gmaTag">STATE PHASE <b id="gmaPhase">—</b></span><span class="gmaTag">MOTION <b id="gmaMotion">STARTING</b></span><span class="gmaTag">ZOOM <b id="gmaZoom">1.00×</b></span><span class="gmaTag">LAYERS <b id="gmaLayers">5/5</b></span></footer>
  </section>
  <aside class="gmaRail" aria-label="Governed mode projections"><div class="gmaRailHead"><span>MODES</span><button class="gmaRailClose" id="gmaModeClose" aria-label="Close modes">×</button></div>${MODES.map((m, i) => `<button class="gmaMode${i === 0 ? " active" : ""}" data-gma-mode="${m[0]}"><b>${m[1]}</b><small>${m[2]}</small></button>`).join("")}</aside>
  <aside class="gmaLayerPanel" aria-label="Field presentation layers"><div class="gmaRailHead"><span>FIELD LAYERS</span><button class="gmaRailClose" id="gmaLayerClose" aria-label="Close field layers">×</button></div><div class="gmaLayerGrid"><button class="gmaLayer" data-gma-layer="field" aria-pressed="true"><b>FIELD</b><small>scalar potential surface</small></button><button class="gmaLayer" data-gma-layer="contours" aria-pressed="true"><b>CONTOURS</b><small>local potential structure</small></button><button class="gmaLayer" data-gma-layer="flow" aria-pressed="true"><b>FLOW</b><small>derived vector field</small></button><button class="gmaLayer" data-gma-layer="particles" aria-pressed="true"><b>PARTICLES</b><small>advected motion traces</small></button><button class="gmaLayer" data-gma-layer="trajectory" aria-pressed="true"><b>TRAJECTORY</b><small>RK2 simulated continuation</small></button></div><div class="gmaLayerTruth">These switches change presentation cost and visibility only. They do not alter canonical state, mode choice, calculus coefficients, evidence class or route authority.</div></aside>
  <aside class="gmaInfo" aria-label="Field evidence and computed data"><div class="gmaRailHead"><span>DETAILS</span><button class="gmaRailClose" id="gmaDetailsClose" aria-label="Close field data">×</button></div><div class="gmaCard"><h4>CURRENT STATE</h4><div class="gmaMetric"><span>Continuity CΩ</span><b id="gmaC">—</b><span>Future plasticity Φ</span><b id="gmaP">—</b><span>Contradiction q</span><b id="gmaQ">—</b><span>Burden Λ</span><b id="gmaB">—</b><span>Dispatch</span><b id="gmaDispatch">—</b><span>Derived display score Ω*</span><b id="gmaScore">—</b></div></div><div class="gmaCard"><h4>DERIVED RELATIONAL SKINS</h4><div class="gmaBars" id="gmaSkins"></div></div><div class="gmaCard"><h4>SOURCE & PROOF</h4><div class="gmaEvidence" id="gmaEvidence">Waiting for canonical runtime state. Geometry, relational-skin bars and Ω* are derived presentation; they do not inherit the state evidence class.</div></div><div class="gmaCard"><h4>MODE OPERATOR</h4><div class="gmaEvidence" id="gmaOperator">Full Overall Canon: constitutional synthesis and admissibility over the current canonical state.</div></div></aside>
</div>`;

const js = `<script id="omegaGovernedModeAtlasRuntime">(()=>{
const host=document.querySelector('#omegaRootSovereignField');if(!host||document.querySelector('#gma'))return;host.insertAdjacentHTML('beforeend',${JSON.stringify(markup)});
const root=document.querySelector('#gma'),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],skins=['Parent','Interaction','Scar','Continuity','Compression','Skin','Interpretation','Behavior'],modeMeta=${JSON.stringify(Object.fromEntries(MODES.map(m => [m[0], [m[1], m[2]]])))};let liveAt=0,canonical=null;
const clamp=v=>Math.max(0,Math.min(1,Number(v)));function n01(v){const n=Number(v);return Number.isFinite(n)?clamp(n):null}function packet(){return canonical}
function bindCanonical(d){const s=d&&d.state&&typeof d.state==='object'?d.state:null,m=s&&s.metrics&&typeof s.metrics==='object'?s.metrics:null;if(!s||!m)return false;const c=n01(m.continuity),p=n01(m.future_plasticity),qq=n01(m.contradiction),b=n01(m.burden);if([c,p,qq,b].some(v=>v===null))return false;const address=Array.isArray(s.address)&&s.address.length===4?s.address.map(Number):null;if(!address||address.some(v=>!Number.isInteger(v)||v<1||v>12))return false;liveAt=Date.now();canonical={c,p,q:qq,b,dispatch:String(d?.mode188?.dispatch||'UNKNOWN'),evidence_class:String(s.evidence_class||'UNKNOWN'),digest:String(d?.digest||''),address,source_id:String(s.source_id||'runtime'),timestamp:String(s.timestamp||''),observed_at:liveAt};window.OMEGA_CANONICAL_PACKET=canonical;const h=document.documentElement;h.dataset.omegaCanonicalState='bound';h.dataset.omegaStateObservedAt=String(liveAt);h.dataset.omegaStateEvidenceClass=canonical.evidence_class;h.dataset.omegaStateDigest=canonical.digest;return true}
function renderPacket(){const P=packet(),ids=['#gmaC','#gmaP','#gmaQ','#gmaB','#gmaDispatch','#gmaScore'];if(!P){ids.forEach(id=>{const e=q(id);if(e)e.textContent='—'});q('#gmaSkins').innerHTML='<div class="gmaEvidence">Canonical metrics unavailable. The display is not presenting fallback values as state.</div>';root.dataset.stateBound='false';return}root.dataset.stateBound='true';q('#gmaC').textContent=P.c.toFixed(3);q('#gmaP').textContent=P.p.toFixed(3);q('#gmaQ').textContent=P.q.toFixed(3);q('#gmaB').textContent=P.b.toFixed(3);q('#gmaDispatch').textContent=P.dispatch;const score=(P.c*P.p)/(P.q+P.b+.0001);q('#gmaScore').textContent=score.toFixed(3);const v=[P.c,.5*(P.c+P.p),P.q,P.c,P.b,.5*(P.q+P.b),P.p,.5*(P.p+P.b)];q('#gmaSkins').innerHTML=skins.map((s,i)=>'<div class="gmaBar"><span>'+s+'</span><i style="--v:'+(v[i]*100).toFixed(0)+'%"></i><b>'+v[i].toFixed(2)+'</b></div>').join('')+'<div class="gmaEvidence">Derived display mapping from canonical CΩ / Φ / q / Λ; these are not additional canonical state fields.</div>'}
function closePanels(except){if(except!=='modes'){root.classList.remove('gma-modes-open');q('#gmaModeToggle').classList.remove('active');q('#gmaModeToggle').setAttribute('aria-expanded','false')}if(except!=='layers'){root.classList.remove('gma-layers-open');q('#gmaLayerToggle').classList.remove('active');q('#gmaLayerToggle').setAttribute('aria-expanded','false')}if(except!=='details'){root.classList.remove('gma-details-open');q('#gmaDetailsToggle').classList.remove('active');q('#gmaDetailsToggle').setAttribute('aria-expanded','false')}}
function togglePanel(name){const map={modes:['gma-modes-open','#gmaModeToggle'],layers:['gma-layers-open','#gmaLayerToggle'],details:['gma-details-open','#gmaDetailsToggle']},pair=map[name],cls=pair[0],button=q(pair[1]),open=!root.classList.contains(cls);closePanels(open?name:'');root.classList.toggle(cls,open);button.classList.toggle('active',open);button.setAttribute('aria-expanded',String(open))}
q('#gmaModeToggle').onclick=()=>togglePanel('modes');q('#gmaLayerToggle').onclick=()=>togglePanel('layers');q('#gmaDetailsToggle').onclick=()=>togglePanel('details');q('#gmaToolsToggle').onclick=()=>document.dispatchEvent(new CustomEvent('omega-field-tools'));q('#gmaModeClose').onclick=()=>closePanels('');q('#gmaLayerClose').onclick=()=>closePanels('');q('#gmaDetailsClose').onclick=()=>closePanels('');
qa('[data-gma-layer]').forEach(b=>b.addEventListener('click',()=>{const on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));const layers=Object.fromEntries(qa('[data-gma-layer]').map(x=>[x.dataset.gmaLayer,x.getAttribute('aria-pressed')==='true']));q('#gmaLayers').textContent=Object.values(layers).filter(Boolean).length+'/5';document.documentElement.dataset.omegaFieldLayers=Object.entries(layers).filter(([,v])=>v).map(([k])=>k).join(',');document.dispatchEvent(new CustomEvent('omega-field-layer',{detail:{layer:b.dataset.gmaLayer,enabled:on,layers}}))}));
qa('[data-gma-mode]').forEach(b=>b.addEventListener('click',()=>{qa('[data-gma-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const mode=b.dataset.gmaMode,m=modeMeta[mode];q('#gmaModeName').textContent=m[0];q('#gmaOperator').textContent=m[0]+': '+m[1]+'. Same canonical state; projection only.';root.dataset.mode=mode;document.documentElement.dataset.omegaFieldMode=mode;closePanels('');document.dispatchEvent(new CustomEvent('omega-field-mode',{detail:{mode}}))}));
q('#gmaPause').onclick=()=>{const paused=root.dataset.paused!=='true';root.dataset.paused=String(paused);const b=q('#gmaPause');b.dataset.state=paused?'paused':'live';b.setAttribute('aria-pressed',String(paused));b.innerHTML=paused?'▶ <span class="gmaActionText">RESUME</span>':'Ⅱ <span class="gmaActionText">PAUSE</span>';document.dispatchEvent(new CustomEvent('omega-field-pause',{detail:{paused}}))};
q('#gmaReset').onclick=()=>document.dispatchEvent(new CustomEvent('omega-field-reset'));q('#gmaFullscreen').onclick=()=>host.requestFullscreen?.();
document.addEventListener('pointerdown',e=>{if(!root.contains(e.target))closePanels('')},{passive:true});document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName||''))return;if(e.key.toLowerCase()==='l'){e.preventDefault();togglePanel('layers')}});
async function get(path){try{const r=await fetch(path,{cache:'no-store'}),t=await r.text();let d=null;try{d=JSON.parse(t)}catch{}return{ok:r.ok,data:d,status:r.status}}catch{return null}}
async function refresh(){const [stateRead,edgeRead]=await Promise.all([get('/api/omega/state'),get('/api/convergence/edge')]);const stateOk=Boolean(stateRead?.ok&&bindCanonical(stateRead.data)),edgeOk=Boolean(edgeRead?.ok),h=document.documentElement;if(stateOk&&canonical){q('#gmaRuntime').textContent='STATE OK';q('#gmaEvidence').innerHTML='<strong>CANONICAL STATE:</strong> '+canonical.evidence_class+' · source '+canonical.source_id+'<br><strong>ADDRESS:</strong> '+canonical.address.join(' / ')+' · digest '+(canonical.digest?canonical.digest.slice(0,16)+'…':'unavailable')+'<br><strong>STATE TIME:</strong> '+(canonical.timestamp||'unavailable')+'<br><strong>READ TIME:</strong> '+new Date(canonical.observed_at).toISOString()+'<br><strong>DISPLAY:</strong> geometry, relational skins and Ω* are derived presentation, not source evidence.';h.dataset.omegaFieldRuntime='state'}else if(canonical){const age=Math.max(0,Math.round((Date.now()-liveAt)/1000));q('#gmaRuntime').textContent='STATE STALE';q('#gmaEvidence').innerHTML='<strong>LAST CANONICAL STATE:</strong> '+canonical.evidence_class+' · '+age+'s since successful read.<br><strong>NETWORK:</strong> '+(edgeOk?'edge reachable; state endpoint unavailable':'runtime unavailable')+'.<br><strong>DISPLAY:</strong> last known state is retained and explicitly stale; no substitute values were invented.';h.dataset.omegaCanonicalState='stale';h.dataset.omegaFieldRuntime=edgeOk?'state-stale':'offline'}else if(edgeOk){q('#gmaRuntime').textContent='EDGE ONLY';q('#gmaEvidence').innerHTML='<strong>RUNTIME EDGE:</strong> reachable, but /api/omega/state did not provide a valid canonical metric packet.<br><strong>DISPLAY:</strong> visual basis is unbound and must not be read as canonical state.';h.dataset.omegaCanonicalState='unbound';h.dataset.omegaFieldRuntime='edge-only';window.OMEGA_CANONICAL_PACKET=null}else{q('#gmaRuntime').textContent='OFFLINE';q('#gmaEvidence').innerHTML='<strong>RUNTIME UNAVAILABLE.</strong><br>No canonical metrics are displayed. Any remaining geometry is presentation-only and unbound.';h.dataset.omegaCanonicalState='unbound';h.dataset.omegaFieldRuntime='offline';window.OMEGA_CANONICAL_PACKET=null}renderPacket()}
renderPacket();refresh();setInterval(refresh,5000);document.documentElement.dataset.omegaFieldLayers='field,contours,flow,particles,trajectory';document.documentElement.dataset.omegaGovernedAtlas='r167-authoritative-state';
})();</script>`;

export async function enhanceGovernedModeAtlas(response: Response): Promise<Response> {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  let html = await response.text();
  if (!html.includes("omegaRootSovereignField") || html.includes("omegaGovernedModeAtlasStyle")) {
    return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  }
  html = html.replace("</head>", css + "</head>");
  html = html.replace("</body>", js + "</body>");
  return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
}
