import convergence, { OmegaRuntime } from "./convergence";
import sovereignEnvironment from "./sovereignEnvironment";
import type { Env } from "./index";
import {
  handleCapabilityRequest,
  injectCapabilityLink,
  injectSpecialistActivation,
  specialistFromPath,
} from "./capabilityRouter";

export { OmegaRuntime };

type GenesisBinding = { fetch(input: Request | string | URL, init?: RequestInit): Promise<Response>; };
type BoundEnv = Env & { GENESIS?: GenesisBinding };

const HEARTBEAT_TRUTH_BOUNDARY = "PC ONLINE requires both an upstream authenticated-online claim and a current authenticated Hybrid heartbeat; stale or absent heartbeat proof cannot be promoted to online.";
const GENESIS_TRANSPORT_BOUNDARY = "V6 may use an internal Cloudflare service binding to observe Genesis. Binding success proves transport reachability only; Genesis canonical state and V6 release authority remain separate.";
const CONVERGENCE_COCKPIT_BOUNDARY = "The convergence cockpit is an observation surface. It visualizes current runtime evidence and cannot mutate canonical V6, Genesis, Hybrid, or release state.";

const convergenceCockpit = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OMEGA V6 · Convergence</title><style>body{margin:0;background:#05070b;color:#f4f7ff;font:15px/1.5 system-ui}.w{max-width:1100px;margin:auto;padding:28px}.c{border:1px solid #26364d;border-radius:18px;background:#0b1119;padding:18px;margin:12px 0}pre{white-space:pre-wrap;word-break:break-word;color:#aab7ca}.b{border:1px solid #34445e;border-radius:999px;padding:8px 12px;color:inherit;text-decoration:none}</style></head><body><main class="w"><a class="b" href="/">← OMEGA</a><div class="c"><h1>Governed convergence proof</h1><p>${CONVERGENCE_COCKPIT_BOUNDARY}</p></div><div class="c"><pre id="p">Loading current V6 ⇄ Genesis ⇄ PC evidence…</pre></div></main><script>async function l(){try{const r=await fetch('/api/convergence/edge',{cache:'no-store'});document.querySelector('#p').textContent=JSON.stringify(await r.json(),null,2)}catch(e){document.querySelector('#p').textContent=String(e)}}l();setInterval(l,5000)</script></body></html>`;

async function jsonFrom(response: Response): Promise<any> { const text = await response.text(); try { return JSON.parse(text); } catch { return { ok:false,error:"non_json_response",status:response.status,body_preview:text.slice(0,240) }; } }
async function genesisServiceProbe(env: BoundEnv, path: string): Promise<any | null> { if(!env.GENESIS)return null; try{const response=await env.GENESIS.fetch(new Request("https://omega-genesis.internal"+path,{method:"GET",headers:{accept:"application/json"}}));return{reachable:response.ok,status:response.status,body:await jsonFrom(response),transport:"SERVICE_BINDING"};}catch(error){return{reachable:false,status:0,error:String(error),transport:"SERVICE_BINDING"};} }
async function repairGenesisTransport(body:any,env:BoundEnv):Promise<any>{if(!env.GENESIS||!body||typeof body!=="object")return body;const[edge,health,manifestProbe,capabilitiesProbe,modesProbe]=await Promise.all([genesisServiceProbe(env,"/_omega/health"),genesisServiceProbe(env,"/api/health"),genesisServiceProbe(env,"/api/convergence/manifest"),genesisServiceProbe(env,"/api/capabilities"),genesisServiceProbe(env,"/api/mode?id=ALL_MODES")]);body.convergence=body.convergence||{};body.convergence.genesis_transport_boundary=GENESIS_TRANSPORT_BOUNDARY;body.convergence.genesis_transport=manifestProbe?.reachable?"SERVICE_BINDING":"SERVICE_BINDING_DEGRADED";const tg=body?.topology?.genesis;if(tg&&typeof tg==="object"){if(edge?.reachable)tg.edge=edge;if(health?.reachable)tg.health=health;}body.genesis=body.genesis||{};const manifest=manifestProbe?.body||{},genome=manifest.capability_genome||{},caps=capabilitiesProbe?.body||{};if(capabilitiesProbe?.reachable){body.genesis.capability_count=genome.capability_count??caps.count??(Array.isArray(caps.capabilities)?caps.capabilities.length:null);body.genesis.acceptance_gates=genome.acceptance_gates||caps.acceptance_gates||[];body.genesis.menus=caps.menus||[];}if(modesProbe?.reachable)body.genesis.all_modes=modesProbe.body?.result||modesProbe.body||null;if(manifestProbe?.reachable){body.genesis.manifest={reachable:true,status:manifestProbe.status,schema:manifest.schema||null,digest:manifest.manifest_digest||null,capability_ids:genome.capability_ids||[],mode_count:genome.mode_count??null,promotion_boundary:manifest.promotion_boundary||null,dimensional_boundary:manifest.dimensional_boundary||null,transport:"SERVICE_BINDING"};body.convergence.reciprocal_manifest_ready=Boolean(manifest.schema==="OMEGA_RECURSIVE_CONVERGENCE_MANIFEST_V2"&&manifest.manifest_digest);body.convergence.genesis_manifest_digest=manifest.manifest_digest||null;}body.ok=Boolean(body?.topology?.v6?.edge?.reachable&&body?.topology?.genesis?.edge?.reachable);return body;}
async function enforceHeartbeatTruth(response:Response,env:BoundEnv):Promise<Response>{const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))return response;let body:any=await response.json();body=await repairGenesisTransport(body,env);const node=body?.topology?.sovereign_pc;if(!node||typeof node!=="object")return Response.json(body,{status:response.status,headers:response.headers});const upstreamOnline=Boolean(node.pc_online),heartbeatCurrent=Boolean(node.heartbeat_current);node.pc_online=Boolean(upstreamOnline&&heartbeatCurrent);node.heartbeat_required_for_pc_online=true;node.upstream_online_claim=upstreamOnline;node.truth_boundary=HEARTBEAT_TRUTH_BOUNDARY;if(!heartbeatCurrent&&upstreamOnline)node.state="HEARTBEAT_STALE_OR_UNPROVEN";body.convergence=body.convergence||{};body.convergence.hybrid_truth_boundary=HEARTBEAT_TRUTH_BOUNDARY;body.convergence.pc_online_requires_current_heartbeat=true;body.convergence.cockpit_observation_boundary=CONVERGENCE_COCKPIT_BOUNDARY;return Response.json(body,{status:response.status,headers:response.headers});}
async function provenEdgeSnapshot(request:Request,env:BoundEnv):Promise<any>{const url=new URL(request.url);url.pathname="/api/convergence/edge";url.search="";const response=await convergence.fetch(new Request(url.toString(),{method:"GET",headers:{accept:"application/json"}}),env);return jsonFrom(await enforceHeartbeatTruth(response,env));}
async function injectCockpitLink(response:Response):Promise<Response>{const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;const html=await response.text();if(html.includes('href="/convergence"'))return new Response(html,response);const link='<a href="/convergence" style="position:fixed;right:14px;bottom:14px;z-index:9999;border:1px solid #3b4f71;border-radius:999px;background:#09111aee;color:#f4f7ff;padding:9px 12px;text-decoration:none;font:700 12px/1.2 system-ui">LIVE CONVERGENCE ↗</a>';return new Response(html.replace("</body>",link+"</body>"),response);}

export default { async fetch(request:Request,env:BoundEnv):Promise<Response>{const url=new URL(request.url);const capabilityResponse=await handleCapabilityRequest(request,env,()=>provenEdgeSnapshot(request,env));if(capabilityResponse)return capabilityResponse;const specialist=specialistFromPath(url.pathname);if(specialist.matched){if(!specialist.view)return Response.json({ok:false,error:"unknown_specialist",allowed:["Field","Earth","Assistant","Hybrid","Proof"]},{status:404});const root=new URL(request.url);root.pathname="/";root.search="";const response=await sovereignEnvironment.fetch(new Request(root.toString(),{method:"GET",headers:request.headers}),env);return injectSpecialistActivation(await injectCapabilityLink(await injectCockpitLink(response)),specialist.view);}if(url.pathname==="/convergence")return new Response(convergenceCockpit,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-omega-authority":"observation-only"}});if(url.pathname==="/"){const response=await sovereignEnvironment.fetch(request,env);return injectCapabilityLink(await injectCockpitLink(response));}const response=await convergence.fetch(request,env);if(url.pathname!=="/api/convergence/edge")return response;return enforceHeartbeatTruth(response,env);} };
