export const HD_LAUNCH_NAVIGATION_BOUNDARY="R121 upgrades the existing V6 launch/navigation presentation without introducing a second runtime, second canonical packet, new execution authority, new evidence authority, or hidden capability. Workspace transitions remain navigation over existing governed surfaces.";

const css=`<style id="omegaHdLaunchStyle">
:root{--hd-glass:rgba(7,11,18,.72);--hd-line:rgba(132,160,204,.24);--hd-shadow:0 32px 110px rgba(0,0,0,.52)}
body::before{content:"";position:fixed;inset:-20vmax;z-index:-3;background:radial-gradient(circle at 18% 12%,rgba(155,108,255,.12),transparent 30%),radial-gradient(circle at 80% 18%,rgba(66,203,124,.1),transparent 27%),radial-gradient(circle at 55% 82%,rgba(79,143,255,.08),transparent 28%);filter:blur(20px);animation:omegaDrift 18s ease-in-out infinite alternate;pointer-events:none}@keyframes omegaDrift{to{transform:translate3d(2.5vmax,-1.5vmax,0) scale(1.04)}}
.top{box-shadow:0 12px 45px rgba(0,0,0,.24)}.surface,.panel,.badge{backdrop-filter:blur(18px) saturate(1.15)}.surface{box-shadow:var(--hd-shadow)}
#omegaLaunch{position:fixed;inset:0;z-index:120;background:radial-gradient(circle at 50% 35%,#15233a 0,#080d15 38%,#030509 78%);display:grid;place-items:center;transition:opacity .55s ease,visibility .55s ease}#omegaLaunch.hidden{opacity:0;visibility:hidden;pointer-events:none}.launchInner{width:min(1100px,92vw);display:grid;grid-template-columns:1.2fr .8fr;gap:24px;align-items:center}.launchMark{font-size:clamp(4rem,13vw,10rem);line-height:.78;font-weight:950;letter-spacing:-.08em;background:linear-gradient(135deg,#fff 15%,#d8c7ff 38%,#76d8ae 62%,#6fa0ff 82%);-webkit-background-clip:text;color:transparent;filter:drop-shadow(0 0 40px rgba(142,129,255,.18))}.launchSub{font-size:clamp(1.05rem,2vw,1.35rem);max-width:690px;color:#aab7c9}.launchMeta{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.launchPill{border:1px solid var(--hd-line);background:rgba(10,17,27,.72);padding:8px 11px;border-radius:999px;color:#c9d3e1}.launchPanel{border:1px solid var(--hd-line);background:linear-gradient(180deg,rgba(16,25,39,.88),rgba(6,10,16,.82));border-radius:28px;padding:20px;box-shadow:var(--hd-shadow)}.launchPanel h3{margin:4px 0 12px}.launchActions{display:grid;gap:9px}.launchAction{display:flex;justify-content:space-between;align-items:center;border:1px solid #314563;border-radius:16px;background:#0b131f;padding:13px 14px;text-decoration:none;transition:.2s transform,.2s border-color,.2s background}.launchAction:hover{transform:translateY(-2px);border-color:#6488bd;background:#101b2b}.launchEnter{margin-top:12px;width:100%;border:1px solid #607fae;border-radius:15px;background:linear-gradient(135deg,#192c4b,#173429);padding:13px 16px;font-weight:800;cursor:pointer}
#omegaDock{position:fixed;z-index:90;left:50%;bottom:14px;translate:-50% 0;display:flex;gap:7px;padding:7px;border:1px solid var(--hd-line);border-radius:18px;background:rgba(5,9,15,.78);backdrop-filter:blur(22px) saturate(1.2);box-shadow:0 18px 60px rgba(0,0,0,.42)}.dockBtn{min-width:54px;border:1px solid transparent;border-radius:12px;background:transparent;color:#bac7d8;padding:8px 10px;cursor:pointer}.dockBtn:hover,.dockBtn.active{background:#122033;border-color:#334d70;color:white}.dockBtn span{display:block;font-size:10px;color:#8293aa;margin-top:2px}
#omegaPalette{position:fixed;z-index:150;inset:0;background:rgba(1,3,6,.68);backdrop-filter:blur(12px);display:none;place-items:start center;padding-top:12vh}#omegaPalette.open{display:grid}.paletteBox{width:min(720px,92vw);border:1px solid #36506f;border-radius:20px;background:#09111c;box-shadow:0 35px 120px #000c;overflow:hidden}.paletteBox input{width:100%;border:0;border-bottom:1px solid #263a54;border-radius:0;background:#0b1420;padding:16px 18px;font-size:1.05rem;outline:0}.paletteList{padding:8px;max-height:52vh;overflow:auto}.paletteItem{display:flex;justify-content:space-between;width:100%;text-align:left;border:0;border-radius:12px;background:transparent;color:#dbe4ef;padding:11px 12px;cursor:pointer}.paletteItem:hover,.paletteItem.active{background:#142238}.paletteItem small{color:#8294aa}
.app{transition:opacity .22s ease,transform .22s ease}.app.active{animation:workspaceIn .28s ease both}@keyframes workspaceIn{from{opacity:0;transform:translateY(8px) scale(.995)}to{opacity:1;transform:none}}
@media(max-width:760px){.launchInner{grid-template-columns:1fr}.launchPanel{display:none}.launchMark{font-size:clamp(4.2rem,24vw,7rem)}#omegaDock{bottom:8px;max-width:94vw;overflow:auto}.dockBtn{min-width:max-content}.work{padding-bottom:82px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.app.active,#omegaLaunch,body::before{animation:none!important;transition:none!important}}
</style>`;

const launch=`<div id="omegaLaunch"><div class="launchInner"><section><div class="eyebrow">OMEGA · SOVEREIGN COMPUTATIONAL ENVIRONMENT</div><div class="launchMark">Ω</div><h1 style="font-size:clamp(2.2rem,5vw,5rem);line-height:.92;margin:.25em 0">Enter the living system.</h1><p class="launchSub">One governed machine for state, relations, memory, forecast, observation and proof. Visuals are driven by runtime state; truth boundaries remain explicit.</p><div class="launchMeta"><span class="launchPill">STATE</span><span class="launchPill">RELATION</span><span class="launchPill">MEMORY</span><span class="launchPill">FORECAST</span><span class="launchPill">PROOF</span></div></section><aside class="launchPanel"><div class="eyebrow">WORKSPACES</div><h3>Choose a starting surface</h3><div class="launchActions"><a class="launchAction" href="/core"><b>Living Core</b><span>direct state instrument →</span></a><button class="launchAction" data-open-app="Field"><b>Living Field</b><span>operator geometry →</span></button><button class="launchAction" data-open-app="Earth"><b>Earth Now</b><span>source traversal →</span></button><button class="launchAction" data-open-app="Assistant"><b>Assistant</b><span>route + synthesis →</span></button><button class="launchAction" data-open-app="Proof"><b>Proof</b><span>evidence + rollback →</span></button></div><button class="launchEnter" id="omegaEnter">Enter current workspace</button></aside></div></div>`;
const dock=`<nav id="omegaDock" aria-label="OMEGA workspace dock"><button class="dockBtn active" data-dock-app="Field">◉<span>FIELD</span></button><button class="dockBtn" data-dock-app="Earth">◎<span>EARTH</span></button><a class="dockBtn" href="/core">Ω<span>CORE</span></a><button class="dockBtn" data-dock-app="Assistant">⌁<span>ASSIST</span></button><button class="dockBtn" data-dock-app="Hybrid">⌘<span>HYBRID</span></button><button class="dockBtn" data-dock-app="Proof">◇<span>PROOF</span></button><button class="dockBtn" id="omegaPaletteOpen">⌕<span>COMMAND</span></button></nav>`;
const palette=`<div id="omegaPalette"><div class="paletteBox"><input id="omegaPaletteInput" placeholder="Jump to a workspace or command…" autocomplete="off"><div class="paletteList" id="omegaPaletteList"></div></div></div>`;
const script=`<script id="omegaHdLaunchScript">(()=>{const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];const commands=[['Living Field','Field','workspace'],['Earth Now','Earth','workspace'],['Assistant','Assistant','workspace'],['Sovereign Build','Hybrid','workspace'],['Proof & Rollback','Proof','workspace'],['Living Operational Core','/core','route'],['Capability Instrument','/capabilities','route'],['Convergence','/convergence','route'],['Evolution Mesh','/evolution','route']];function openApp(name){const btn=all('.navbtn[data-app]').find(x=>x.dataset.app===name);if(btn){btn.click();all('.dockBtn[data-dock-app]').forEach(x=>x.classList.toggle('active',x.dataset.dockApp===name));return true}return false}function closeLaunch(){const x=$('#omegaLaunch');if(x)x.classList.add('hidden');try{sessionStorage.setItem('omega_launch_seen','1')}catch{}}all('[data-open-app]').forEach(b=>b.addEventListener('click',()=>{closeLaunch();openApp(b.dataset.openApp)}));$('#omegaEnter')?.addEventListener('click',closeLaunch);if(sessionStorage.getItem('omega_launch_seen')==='1')$('#omegaLaunch')?.classList.add('hidden');all('[data-dock-app]').forEach(b=>b.addEventListener('click',()=>openApp(b.dataset.dockApp)));function renderPalette(term=''){const list=$('#omegaPaletteList'),q=term.trim().toLowerCase();list.innerHTML='';commands.filter(c=>!q||c[0].toLowerCase().includes(q)||c[1].toLowerCase().includes(q)).forEach((c,i)=>{const b=document.createElement('button');b.className='paletteItem'+(i===0?' active':'');b.innerHTML='<b>'+c[0]+'</b><small>'+c[2]+'</small>';b.onclick=()=>{if(c[2]==='route')location.href=c[1];else openApp(c[1]);$('#omegaPalette').classList.remove('open')};list.append(b)})}function openPalette(){renderPalette();$('#omegaPalette').classList.add('open');setTimeout(()=>$('#omegaPaletteInput')?.focus(),0)}$('#omegaPaletteOpen')?.addEventListener('click',openPalette);$('#omegaPaletteInput')?.addEventListener('input',e=>renderPalette(e.target.value));$('#omegaPalette')?.addEventListener('click',e=>{if(e.target.id==='omegaPalette')e.currentTarget.classList.remove('open')});addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape')$('#omegaPalette')?.classList.remove('open')});const existing=$('#search');existing?.addEventListener('focus',()=>{existing.placeholder='Search applications or commands…  ·  Ctrl/⌘ K for palette'});})();</script>`;

export async function enhanceHdLaunchNavigation(response:Response,pathname:string):Promise<Response>{
  if(pathname!=="/"&&pathname!=="")return response;
  const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;
  const text=await response.text();if(!text.includes('id="nav"')||text.includes('id="omegaLaunch"'))return new Response(text,{status:response.status,headers:response.headers});
  const body=text.replace('</head>',css+'</head>').replace('<body>','<body>'+launch+palette).replace('</body>',dock+script+'</body>');
  const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-omega-ui','hd-launch-navigation-r121');
  return new Response(body,{status:response.status,headers});
}
