export const HD_LAUNCH_NAVIGATION_BOUNDARY="R126 expands the existing rich V6 operational surface without replacing the canonical runtime, canonical packet, execution authority, evidence authority, heartbeat truth, specialist workspaces, or existing APIs. New Calculus, Memory and Simulation instruments are views over the same governed machine.";

const css=`<style id="omegaHdLaunchStyle">
:root{--hd-glass:rgba(7,11,18,.72);--hd-line:rgba(132,160,204,.24);--hd-shadow:0 32px 110px rgba(0,0,0,.52)}
body::before{content:"";position:fixed;inset:-20vmax;z-index:-3;background:radial-gradient(circle at 18% 12%,rgba(155,108,255,.12),transparent 30%),radial-gradient(circle at 78% 18%,rgba(66,203,124,.1),transparent 27%),radial-gradient(circle at 58% 82%,rgba(79,143,255,.08),transparent 28%);filter:blur(20px);animation:omegaDrift 18s ease-in-out infinite alternate;pointer-events:none}@keyframes omegaDrift{to{transform:translate3d(2.5vmax,-1.5vmax,0) scale(1.04)}}
.top{box-shadow:0 12px 45px rgba(0,0,0,.24)}.surface,.panel,.badge{backdrop-filter:blur(18px) saturate(1.15)}.surface{box-shadow:var(--hd-shadow)}
#omegaLaunch{position:fixed;inset:0;z-index:2147483000;isolation:isolate;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;background:radial-gradient(circle at 50% 35%,#15233a 0,#080d15 38%,#030509 78%);display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) max(18px,env(safe-area-inset-right)) max(22px,env(safe-area-inset-bottom)) max(18px,env(safe-area-inset-left));box-sizing:border-box;transition:opacity .38s ease,visibility .38s ease}#omegaLaunch.hidden{opacity:0;visibility:hidden;pointer-events:none}.launchInner{width:min(1180px,100%);margin:auto;display:grid;grid-template-columns:1.16fr .84fr;gap:24px;align-items:center}.launchMark{font-size:clamp(4rem,13vw,10rem);line-height:.78;font-weight:950;letter-spacing:-.08em;background:linear-gradient(135deg,#fff 12%,#d8c7ff 34%,#e6bd4e 49%,#ef625f 61%,#4f8fff 75%,#76d8ae 90%);-webkit-background-clip:text;color:transparent;filter:drop-shadow(0 0 40px rgba(142,129,255,.18))}.launchSub{font-size:clamp(1.05rem,2vw,1.35rem);max-width:690px;color:#aab7c9}.launchMeta{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.launchPill{border:1px solid var(--hd-line);background:rgba(10,17,27,.72);padding:8px 11px;border-radius:999px;color:#c9d3e1}.launchPanel{border:1px solid var(--hd-line);background:linear-gradient(180deg,rgba(16,25,39,.88),rgba(6,10,16,.82));border-radius:28px;padding:20px;box-shadow:var(--hd-shadow)}.launchPanel h3{margin:4px 0 12px}.launchActions{display:grid;gap:8px}.launchAction{display:flex;justify-content:space-between;align-items:center;border:1px solid #314563;border-radius:14px;background:#0b131f;padding:11px 13px;text-decoration:none;transition:.2s transform,.2s border-color,.2s background}.launchAction:hover{transform:translateY(-2px);border-color:#6488bd;background:#101b2b}.launchEnter{margin-top:12px;width:100%;border:1px solid #607fae;border-radius:15px;background:linear-gradient(135deg,#192c4b,#173429);padding:13px 16px;font-weight:800;cursor:pointer}
#omegaDock{position:fixed;z-index:90;left:50%;bottom:14px;translate:-50% 0;display:flex;gap:5px;padding:7px;border:1px solid var(--hd-line);border-radius:18px;background:rgba(5,9,15,.82);backdrop-filter:blur(22px) saturate(1.2);box-shadow:0 18px 60px rgba(0,0,0,.42);max-width:96vw;overflow:auto}.dockBtn{min-width:54px;border:1px solid transparent;border-radius:12px;background:transparent;color:#bac7d8;padding:8px 9px;cursor:pointer;text-decoration:none;text-align:center}.dockBtn:hover,.dockBtn.active{background:#122033;border-color:#334d70;color:white}.dockBtn span{display:block;font-size:9px;color:#8293aa;margin-top:2px;letter-spacing:.08em}
#omegaPalette{position:fixed;z-index:150;inset:0;background:rgba(1,3,6,.68);backdrop-filter:blur(12px);display:none;place-items:start center;padding-top:12vh}#omegaPalette.open{display:grid}.paletteBox{width:min(760px,92vw);border:1px solid #36506f;border-radius:20px;background:#09111c;box-shadow:0 35px 120px #000c;overflow:hidden}.paletteBox input{width:100%;border:0;border-bottom:1px solid #263a54;border-radius:0;background:#0b1420;padding:16px 18px;font-size:1.05rem;outline:0}.paletteList{padding:8px;max-height:52vh;overflow:auto}.paletteItem{display:flex;justify-content:space-between;width:100%;text-align:left;border:0;border-radius:12px;background:transparent;color:#dbe4ef;padding:11px 12px;cursor:pointer}.paletteItem:hover,.paletteItem.active{background:#142238}.paletteItem small{color:#8294aa}
.app{transition:opacity .22s ease,transform .22s ease}.app.active{animation:workspaceIn .28s ease both}@keyframes workspaceIn{from{opacity:0;transform:translateY(8px) scale(.995)}to{opacity:1;transform:none}}
.omegaInstrumentGrid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:16px}.omegaInstrumentCanvas{position:relative;min-height:570px;border:1px solid #27354c;border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 50%,#0d1725,#04070c 70%)}.omegaInstrumentCanvas canvas{display:block;width:100%;height:570px}.omegaInstrumentHud{position:absolute;left:14px;right:14px;top:14px;display:flex;justify-content:space-between;gap:10px;pointer-events:none}.omegaReadout{border:1px solid #344966;border-radius:999px;background:#07101bd9;padding:7px 10px;backdrop-filter:blur(12px)}.omegaSlider{margin:11px 0}.omegaSlider label{display:flex;justify-content:space-between;gap:10px;font-size:.79rem;color:#a9b6c9}.omegaSlider input{width:100%}.omegaEquation{font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;color:#b6c3d6;border:1px solid #27374e;border-radius:12px;padding:11px;background:#07101a}.omegaEvidenceTag{display:inline-flex;border:1px solid #394c68;border-radius:999px;padding:5px 8px;font-size:.69rem;letter-spacing:.08em;color:#aab9ce}.omegaMemoryStage{position:relative;min-height:570px;border:1px solid #27354c;border-radius:18px;overflow:hidden;background:radial-gradient(circle at 50% 50%,#111d2e,#04070c 68%)}.omegaMemoryStage canvas{width:100%;height:570px;display:block}.omegaMemoryLegend{display:grid;grid-template-columns:1fr 1fr;gap:8px}.omegaMemoryLegend div{border:1px solid #29394f;border-radius:11px;background:#09121d;padding:10px}.omegaBranchGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.omegaBranch{border:1px solid #2b3b53;border-radius:14px;background:#09121c;padding:12px}.omegaBranch b{display:block;font-size:1.05rem}.omegaBranch canvas{width:100%;height:130px;border-radius:10px;background:#050910;margin-top:8px}.omegaModeStrip{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.omegaModeChip{border:1px solid #31445f;border-radius:999px;padding:5px 8px;font-size:.7rem;background:#09121d;color:#b8c5d8}.omegaModeChip.active{background:#15253b;border-color:#5c789f;color:white}.omegaNavNew{position:relative}.omegaNavNew::after{content:"LIVE";font-size:8px;letter-spacing:.08em;color:#7fe0aa;border:1px solid #275c43;border-radius:999px;padding:2px 5px}.omegaShellButtons{display:flex;gap:6px;flex-wrap:wrap}.omegaShellButtons button{border:1px solid #35445f;border-radius:9px;background:#0d1724;padding:7px 9px;cursor:pointer}.omegaShellButtons button.active{background:#1a2d4b;border-color:#6685b4}.omegaTimeRail{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;margin-top:10px}.omegaTimeRail input{width:100%}
@media(max-width:1000px){.omegaInstrumentGrid{grid-template-columns:1fr}.omegaBranchGrid{grid-template-columns:1fr 1fr}}
@media(max-width:760px){
#omegaLaunch{place-items:start center;padding-top:max(18px,env(safe-area-inset-top));background:radial-gradient(circle at 48% 8%,#15243a 0,#080d15 34%,#030509 76%)}
#omegaLaunch:not(.hidden)~#omegaDock{display:none!important}
.launchInner{grid-template-columns:1fr;gap:18px;align-items:start;padding:clamp(12px,3.2vh,28px) 0 8px;min-height:100%;box-sizing:border-box}
.launchInner>section{min-width:0}
.launchInner .eyebrow{font-size:clamp(.68rem,2.7vw,.82rem);letter-spacing:.16em;line-height:1.45;max-width:100%}
.launchMark{font-size:clamp(4rem,21vw,6.4rem);line-height:.78;margin-top:6px}
.launchInner h1{font-size:clamp(2.25rem,10.8vw,3.9rem)!important;line-height:.94!important;letter-spacing:-.045em;margin:.22em 0 .3em!important;max-width:11ch}
.launchSub{font-size:clamp(.98rem,4.2vw,1.15rem);line-height:1.5;max-width:34rem;margin:0;color:#b8c3d2}
.launchMeta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:16px}
.launchPill{display:flex;min-width:0;justify-content:center;align-items:center;text-align:center;padding:9px 6px;font-size:.72rem;letter-spacing:.055em;white-space:nowrap}
.launchPanel{display:block;border-radius:20px;padding:14px;background:linear-gradient(180deg,rgba(14,23,36,.96),rgba(5,9,15,.96));box-shadow:0 22px 70px rgba(0,0,0,.45)}
.launchPanel .eyebrow{font-size:.68rem}.launchPanel h3{font-size:1rem;margin:4px 0 10px}
.launchActions{grid-template-columns:1fr 1fr;gap:8px}
.launchAction{min-height:58px;padding:10px 11px;border-radius:13px;gap:8px;line-height:1.15;overflow:hidden}
.launchAction b{font-size:.88rem}.launchAction span{font-size:.72rem;color:#8fa2ba;text-align:right}
.launchEnter{min-height:48px;margin-top:10px;padding:11px 14px}
#omegaDock{bottom:max(8px,env(safe-area-inset-bottom))}.dockBtn{min-width:max-content}.work{padding-bottom:82px}.omegaInstrumentCanvas,.omegaInstrumentCanvas canvas,.omegaMemoryStage,.omegaMemoryStage canvas{height:470px;min-height:470px}.omegaBranchGrid{grid-template-columns:1fr}.omegaMemoryLegend{grid-template-columns:1fr}}
@media(max-width:430px){.launchActions{grid-template-columns:1fr}.launchAction{min-height:52px}.launchMeta{grid-template-columns:repeat(2,minmax(0,1fr))}}
body.omegaLaunchOpen{overflow:hidden!important;touch-action:none}
body.omegaLaunchOpen>.top,body.omegaLaunchOpen>main.work,body.omegaLaunchOpen>#omegaDock,body.omegaLaunchOpen>#nav{visibility:hidden!important;pointer-events:none!important}
body.omegaLaunchOpen #omegaLaunch{visibility:visible!important;pointer-events:auto!important;touch-action:pan-y}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.app.active,#omegaLaunch,body::before{animation:none!important;transition:none!important}}
</style>`;

const launch=`<div id="omegaLaunch"><div class="launchInner"><section><div class="eyebrow">OMEGA · SOVEREIGN COMPUTATIONAL ENVIRONMENT</div><div class="launchMark">Ω</div><h1 style="font-size:clamp(2.2rem,5vw,5rem);line-height:.92;margin:.25em 0">Enter the living system.</h1><p class="launchSub">One governed machine for state, relations, memory, calculus, forecast, observation, action and proof. The rich operational field remains the center; new instruments extend it rather than replace it.</p><div class="launchMeta"><span class="launchPill">STATE</span><span class="launchPill">CALCULUS</span><span class="launchPill">RELATION</span><span class="launchPill">MEMORY</span><span class="launchPill">FORECAST</span><span class="launchPill">PROOF</span></div></section><aside class="launchPanel"><div class="eyebrow">WORKSPACES</div><h3>Choose a starting instrument</h3><div class="launchActions"><button class="launchAction" data-open-app="Field"><b>Living Field</b><span>operator geometry →</span></button><button class="launchAction" data-open-app="Calculus"><b>Calculus</b><span>trajectory + curvature →</span></button><button class="launchAction" data-open-app="Memory"><b>Memory</b><span>continuity + scar graph →</span></button><button class="launchAction" data-open-app="Simulate"><b>Create / Simulate</b><span>branch futures →</span></button><button class="launchAction" data-open-app="Earth"><b>Earth Now</b><span>source traversal →</span></button><button class="launchAction" data-open-app="Assistant"><b>Assistant</b><span>route + synthesis →</span></button><a class="launchAction" href="/core"><b>Living Core</b><span>direct state instrument →</span></a></div><button class="launchEnter" id="omegaEnter">Enter current workspace</button></aside></div></div>`;
const dock=`<nav id="omegaDock" aria-label="OMEGA workspace dock"><button class="dockBtn active" data-dock-app="Field">◉<span>FIELD</span></button><button class="dockBtn" data-dock-app="Calculus">∂<span>CALCULUS</span></button><button class="dockBtn" data-dock-app="Memory">⌬<span>MEMORY</span></button><button class="dockBtn" data-dock-app="Simulate">⌁<span>SIMULATE</span></button><button class="dockBtn" data-dock-app="Earth">◎<span>EARTH</span></button><button class="dockBtn" data-dock-app="Assistant">↯<span>INTEL</span></button><button class="dockBtn" data-dock-app="Hybrid">⌘<span>HYBRID</span></button><button class="dockBtn" data-dock-app="Proof">◇<span>PROOF</span></button><button class="dockBtn" id="omegaPaletteOpen">⌕<span>COMMAND</span></button></nav>`;
const palette=`<div id="omegaPalette"><div class="paletteBox"><input id="omegaPaletteInput" placeholder="Jump to a workspace or command…" autocomplete="off"><div class="paletteList" id="omegaPaletteList"></div></div></div>`;

const workspaceMarkup=`<section class="surface app" data-view="Calculus"><div class="hero"><div><div class="eyebrow">Direct mathematical instrument</div><h1>Living Calculus</h1><p>Manipulate a local projection of continuity CΩ, future plasticity Φ, burden Λ, contradiction q, display phase and Δt. A valid canonical state may seed these controls, but every slider edit and projected trajectory remains USER_DEFINED_MODEL / SIMULATED_CONTINUATION rather than inheriting the source state evidence class.</p></div><div class="badge"><div class="eyebrow">Evidence class</div><b>USER_DEFINED_MODEL</b><div class="tiny muted">SIMULATED_CONTINUATION for projected branches</div></div></div><div class="body"><div class="omegaInstrumentGrid"><div class="omegaInstrumentCanvas"><canvas id="omegaCalcCanvas"></canvas><div class="omegaInstrumentHud"><span class="omegaReadout" id="omegaCalcShell">144 representation shell</span><span class="omegaReadout" id="omegaCalcClock">Δt 24</span></div></div><aside class="panel"><div class="eyebrow">State variables</div><div id="omegaCalcControls"></div><div class="omegaShellButtons"><button data-omega-shell="144" class="active">144</button><button data-omega-shell="1728">1728</button><button data-omega-shell="20736">20736</button></div><div class="omegaTimeRail"><span>now</span><input id="omegaDt" type="range" min="1" max="120" value="24"><span id="omegaDtOut">24</span></div><div class="omegaEquation" id="omegaEquation">Ω score = (CΩ × Φ) / (q + Λ + ε)</div><div class="omegaModeStrip" id="omegaCalcModes"></div><details class="proof"><summary>Projection proof</summary><pre id="omegaCalcProof">Awaiting canonical state.</pre></details></aside></div></div></section>
<section class="surface app" data-view="Memory"><div class="hero"><div><div class="eyebrow">Continuity + scar + relation</div><h1>Living Memory Field</h1><p>This view renders a derived relational graph around the latest valid canonical state when one is available. The graph geometry, relation density and forecast carry are presentation/model outputs; they are not additional canonical facts.</p></div><div class="badge"><div class="eyebrow">Memory authority</div><b id="omegaMemoryState">PROBING</b><div class="tiny muted">source state and derived graph remain distinct</div></div></div><div class="body"><div class="omegaInstrumentGrid"><div class="omegaMemoryStage"><canvas id="omegaMemoryCanvas"></canvas><div class="omegaInstrumentHud"><span class="omegaReadout" id="omegaMemoryFocus">State base</span><span class="omegaReadout" id="omegaMemoryCount">0 relations</span></div></div><aside class="panel"><div class="eyebrow">Memory classes</div><div class="omegaMemoryLegend"><div><b>Canonical</b><span class="tiny muted">accepted continuity</span></div><div><b>Scar</b><span class="tiny muted">contradiction + turns</span></div><div><b>Relation</b><span class="tiny muted">typed adjacency</span></div><div><b>Forecast</b><span class="tiny muted">future carry</span></div><div><b>Capability</b><span class="tiny muted">recovered behavior</span></div><div><b>Strategy</b><span class="tiny muted">successful development path</span></div></div><div class="omegaModeStrip" id="omegaMemoryModes"></div><details class="proof"><summary>Memory source packet</summary><pre id="omegaMemoryProof">Awaiting canonical state.</pre></details></aside></div></div></section>
<section class="surface app" data-view="Simulate"><div class="hero"><div><div class="eyebrow">Create + compare admissible futures</div><h1>State-Space Simulation</h1><p>Explore multiple local continuations from the latest valid canonical base when available, or from an explicitly user-defined seed otherwise. Branches remain SIMULATED_CONTINUATION and never overwrite source observations or canonical state.</p></div><div class="badge"><div class="eyebrow">Boundary</div><b>SIMULATED_CONTINUATION</b><div class="tiny muted">compare before carrying forward</div></div></div><div class="body"><div class="panel"><div class="controls"><button class="btn primary" id="omegaRunSim">Run branch comparison</button><button class="btn" id="omegaAdvanceSim">Advance Δt</button><button class="btn" data-open-app="Calculus">Tune calculus</button></div><div class="omegaBranchGrid"><div class="omegaBranch"><span class="omegaEvidenceTag">STAY</span><b>Continuity corridor</b><span class="tiny muted">minimum intervention</span><canvas id="omegaBranchStay"></canvas><div id="omegaStayMetric"></div></div><div class="omegaBranch"><span class="omegaEvidenceTag">TURN</span><b>Adaptive turn</b><span class="tiny muted">reweighted relation path</span><canvas id="omegaBranchTurn"></canvas><div id="omegaTurnMetric"></div></div><div class="omegaBranch"><span class="omegaEvidenceTag">ESCALATE</span><b>Expansion corridor</b><span class="tiny muted">higher construct pressure</span><canvas id="omegaBranchEsc"></canvas><div id="omegaEscMetric"></div></div></div><div class="omegaModeStrip" id="omegaSimModes"></div><details class="proof"><summary>Simulation packet</summary><pre id="omegaSimProof">No simulation run yet.</pre></details></div></div></section>`;

const script=`<script id="omegaHdLaunchScript">(()=>{
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];document.body.classList.add('omegaLaunchOpen');
const roleColors={ALPHA:'#9b6cff',BASE:'#e6bd4e',CONSTRUCT:'#ef625f',PRUNE:'#4f8fff',OMEGA:'#42cb7c'};
const state={canonical:null,calcSource:'USER_DEFINED_MODEL_SEED',shell:144,t:0,dt:24,calc:{C:0.72,P:0.68,L:0.28,q:0.18,phase:0.42},simTick:0};
const commands=[['Living Field','Field','workspace'],['Living Calculus','Calculus','workspace'],['Living Memory','Memory','workspace'],['Create / Simulate','Simulate','workspace'],['Earth Now','Earth','workspace'],['Assistant','Assistant','workspace'],['Sovereign Build','Hybrid','workspace'],['Proof & Rollback','Proof','workspace'],['Living Operational Core','/core','route'],['Capability Instrument','/capabilities','route'],['Convergence','/convergence','route'],['Evolution Mesh','/evolution','route']];
function closeLaunch(){const x=$('#omegaLaunch');if(x)x.classList.add('hidden');document.body.classList.remove('omegaLaunchOpen');try{sessionStorage.setItem('omega_launch_seen','1')}catch{}}
function activate(name){all('.app').forEach(x=>x.classList.toggle('active',x.dataset.view===name));all('.navbtn[data-app]').forEach(x=>x.classList.toggle('active',x.dataset.app===name));all('.dockBtn[data-dock-app]').forEach(x=>x.classList.toggle('active',x.dataset.dockApp===name));const c=$('#crumbName');if(c)c.textContent=name==='Field'?'Living Field':name==='Simulate'?'Create / Simulate':name;closeLaunch();if(name==='Calculus')drawCalc();if(name==='Memory')drawMemory();if(name==='Simulate')drawBranches();}
function openApp(name){const target=$('.app[data-view="'+name+'"]');if(target){activate(name);return true}const btn=all('.navbtn[data-app]').find(x=>x.dataset.app===name);if(btn){btn.click();return true}return false}
function injectWorkspaces(){const main=$('main.work');if(!main||$('.app[data-view="Calculus"]'))return;main.insertAdjacentHTML('beforeend',${JSON.stringify(workspaceMarkup)});const group=$('#nav .group');if(group){const earth=group.querySelector('[data-app="Earth"]');[['Calculus','Calculus','∂'],['Memory','Memory','M'],['Simulate','Create / Simulate','S']].forEach(v=>{const b=document.createElement('button');b.className='navbtn omegaNavNew';b.dataset.app=v[0];b.innerHTML='<span>'+v[1]+'</span><span>'+v[2]+'</span>';b.onclick=()=>activate(v[0]);group.insertBefore(b,earth||null)})}buildCalcControls();loadCanonical();}
function buildCalcControls(){const box=$('#omegaCalcControls');if(!box)return;const vars=[['C','CΩ continuity',0,1,.01],['P','Φ future plasticity',0,1,.01],['L','Λ burden',0,1,.01],['q','q contradiction',0,1,.01],['phase','phase',0,1,.01]];box.innerHTML=vars.map(v=>'<div class="omegaSlider"><label><span>'+v[1]+'</span><b id="out_'+v[0]+'">'+state.calc[v[0]].toFixed(2)+'</b></label><input data-calc-var="'+v[0]+'" type="range" min="'+v[2]+'" max="'+v[3]+'" step="'+v[4]+'" value="'+state.calc[v[0]]+'"></div>').join('');all('[data-calc-var]').forEach(i=>i.oninput=()=>{state.calc[i.dataset.calcVar]=Number(i.value);state.calcSource='USER_DEFINED_MODEL_EDIT';$('#out_'+i.dataset.calcVar).textContent=Number(i.value).toFixed(2);drawCalc();drawBranches()});all('[data-omega-shell]').forEach(b=>b.onclick=()=>{state.shell=Number(b.dataset.omegaShell);all('[data-omega-shell]').forEach(x=>x.classList.toggle('active',x===b));$('#omegaCalcShell').textContent=state.shell+' representation shell';drawCalc()});$('#omegaDt').oninput=e=>{state.dt=Number(e.target.value);$('#omegaDtOut').textContent=state.dt;$('#omegaCalcClock').textContent='Δt '+state.dt;drawCalc();drawBranches()};}
async function loadCanonical(){try{const r=await fetch('/api/omega/state',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),s=d?.state,m=s?.metrics,address=Array.isArray(s?.address)?s.address.map(Number):null,vals=[m?.continuity,m?.future_plasticity,m?.burden,m?.contradiction].map(Number);if(!s||vals.some(v=>!Number.isFinite(v))||!address||address.length!==4||address.some(v=>!Number.isInteger(v)||v<1||v>12))throw new Error('invalid canonical state payload');state.canonical={digest:String(d?.digest||''),state:s,mode188:d?.mode188||null};state.calc.C=Math.max(0,Math.min(1,vals[0]));state.calc.P=Math.max(0,Math.min(1,vals[1]));state.calc.L=Math.max(0,Math.min(1,vals[2]));state.calc.q=Math.max(0,Math.min(1,vals[3]));state.calc.phase=(address[1]-1)/11;state.calcSource='CANONICAL_SEED_THEN_USER_DEFINED_MODEL';const cls=String(s.evidence_class||'UNKNOWN');$('#omegaMemoryState').textContent='CANONICAL · '+cls;$('#omegaMemoryFocus').textContent='Address '+address.join(' / ');const proof={canonical:{evidence_class:cls,digest:state.canonical.digest,address,source_id:s.source_id||null,timestamp:s.timestamp||null,metrics:m},local_projection:{evidence_class:'USER_DEFINED_MODEL',source:state.calcSource,variables:state.calc,boundary:'canonical values seed controls; local controls and trajectories do not inherit source evidence'}};$('#omegaCalcProof').textContent=JSON.stringify(proof,null,2);$('#omegaMemoryProof').textContent=JSON.stringify(proof,null,2);syncControls();renderModeChips();drawCalc();drawMemory();drawBranches()}catch(e){state.canonical=null;state.calcSource='USER_DEFINED_MODEL_SEED';$('#omegaMemoryState').textContent='NO CANONICAL STATE';$('#omegaMemoryFocus').textContent='Model seed';$('#omegaCalcProof').textContent='Canonical state unavailable. Local controls remain USER_DEFINED_MODEL.\n'+String(e);$('#omegaMemoryProof').textContent='Canonical state unavailable. Derived graph is not canonical memory.\n'+String(e);drawCalc();drawMemory();drawBranches()}}
function syncControls(){all('[data-calc-var]').forEach(i=>{i.value=state.calc[i.dataset.calcVar];const o=$('#out_'+i.dataset.calcVar);if(o)o.textContent=Number(i.value).toFixed(2)})}
function renderModeChips(){const names=['Mode 188','Unified Coherence','Forecast','Unified Recursion','PRUNE→TRANSLATE→PROVE','Motion Relativity'];['omegaCalcModes','omegaMemoryModes','omegaSimModes'].forEach(id=>{const e=$('#'+id);if(e)e.innerHTML=names.map((n,i)=>'<span class="omegaModeChip '+(i<3?'active':'')+'">'+n+'</span>').join('')})}
function fit(c,h){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();c.width=Math.max(1,r.width*d);c.height=Math.max(1,(h||r.height)*d);return[c.getContext('2d'),c.width,c.height,d]}
function score(){return state.calc.C*state.calc.P/(state.calc.q+state.calc.L+.04)}
function drawCalc(){const c=$('#omegaCalcCanvas');if(!c)return;const [x,w,h]=fit(c);x.clearRect(0,0,w,h);const s=score(),cx=w*.48,cy=h*.52;const bg=x.createRadialGradient(cx,cy,0,cx,cy,Math.max(w,h)*.62);bg.addColorStop(0,'#122239');bg.addColorStop(.46,'#07101b');bg.addColorStop(1,'#030509');x.fillStyle=bg;x.fillRect(0,0,w,h);const rings=state.shell===144?4:state.shell===1728?8:12;for(let r=1;r<=rings;r++){const rr=(Math.min(w,h)*(.08+r*.026))*(1+state.calc.L*.35);x.beginPath();x.ellipse(cx,cy,rr*1.55,rr,.22+state.calc.phase*.7,0,Math.PI*2);x.strokeStyle='rgba(116,148,195,'+(0.16+r/rings*.12)+')';x.lineWidth=1;x.stroke()}const roles=[['ALPHA',state.calc.P],['BASE',state.calc.C],['CONSTRUCT',Math.min(1,state.calc.P+state.calc.L*.5)],['PRUNE',Math.min(1,state.calc.q+state.calc.L*.35)],['OMEGA',Math.min(1,s/2.2)]];roles.forEach((r,i)=>{const a=state.t*.003+(i/roles.length)*Math.PI*2+state.calc.phase*Math.PI,rad=Math.min(w,h)*(.18+i*.035),px=cx+Math.cos(a)*rad*1.35,py=cy+Math.sin(a)*rad*.72;const g=x.createRadialGradient(px,py,0,px,py,30+90*r[1]);g.addColorStop(0,roleColors[r[0]]);g.addColorStop(1,'transparent');x.fillStyle=g;x.beginPath();x.arc(px,py,30+90*r[1],0,Math.PI*2);x.fill();x.beginPath();x.arc(px,py,5+14*r[1],0,Math.PI*2);x.fillStyle=roleColors[r[0]];x.fill()});x.lineWidth=2.2;const grad=x.createLinearGradient(w*.12,h*.8,w*.88,h*.2);grad.addColorStop(0,roleColors.PRUNE);grad.addColorStop(.25,roleColors.ALPHA);grad.addColorStop(.5,roleColors.BASE);grad.addColorStop(.75,roleColors.CONSTRUCT);grad.addColorStop(1,roleColors.OMEGA);x.strokeStyle=grad;x.beginPath();const pts=120;for(let i=0;i<pts;i++){const u=i/(pts-1),tt=u*state.dt*.085,xx=w*(.08+.84*u),yy=cy+Math.sin(tt+state.calc.phase*6.28)*h*.12*(.45+state.calc.q)+Math.cos(tt*.47)*h*.08*state.calc.L-h*.13*(state.calc.C-state.calc.q)*u; if(i===0)x.moveTo(xx,yy);else x.lineTo(xx,yy)}x.stroke();for(let i=0;i<(state.shell===144?40:state.shell===1728?110:220);i++){const u=(i*0.61803398875)%1,a=i*2.399+state.t*.0015,rad=Math.min(w,h)*(.08+.34*u),px=cx+Math.cos(a)*rad*1.25,py=cy+Math.sin(a)*rad*.72;x.fillStyle=[roleColors.ALPHA,roleColors.BASE,roleColors.CONSTRUCT,roleColors.PRUNE,roleColors.OMEGA][i%5]+'99';x.fillRect(px,py,1.5+(i%3),1.5+(i%3))}$('#omegaEquation').textContent='Ω score = (CΩ × Φ) / (q + Λ + ε) = '+s.toFixed(3)+'   · curvature '+(state.calc.q+state.calc.L).toFixed(3)+'   · shell '+state.shell;state.t++;requestAnimationFrame(drawCalc)}
function memoryNodes(){const base=[[state.canonical?'Canonical base':'Model seed','OMEGA',1],['Continuity','BASE',.86],['Scar','PRUNE',.72],['Relations','CONSTRUCT',.82],['Forecast','ALPHA',.67],['Capability','OMEGA',.58],['Strategy','BASE',.54],['Observation','CONSTRUCT',.61],['Proof','PRUNE',.63]];const extra=state.shell===20736?8:state.shell===1728?4:2;for(let i=0;i<extra;i++)base.push(['Trace '+(i+1),['ALPHA','BASE','CONSTRUCT','PRUNE','OMEGA'][i%5],.32+i*.04]);return base}
function drawMemory(){const c=$('#omegaMemoryCanvas');if(!c)return;const [x,w,h]=fit(c);x.clearRect(0,0,w,h);const cx=w*.5,cy=h*.5,nodes=memoryNodes();const positions=nodes.map((n,i)=>{if(i===0)return{x:cx,y:cy};const a=(i-1)/(nodes.length-1)*Math.PI*2-.8,rad=Math.min(w,h)*(.22+((i%3)*.045));return{x:cx+Math.cos(a)*rad*1.35,y:cy+Math.sin(a)*rad*.8}});for(let i=1;i<nodes.length;i++){const p=positions[i];x.beginPath();x.moveTo(cx,cy);x.quadraticCurveTo((cx+p.x)/2+Math.sin(i)*35,(cy+p.y)/2+Math.cos(i)*22,p.x,p.y);x.strokeStyle=roleColors[nodes[i][1]]+'66';x.lineWidth=1+nodes[i][2]*2;x.stroke();if(i>2){const j=1+(i*3)%(nodes.length-1),q=positions[j];x.beginPath();x.moveTo(p.x,p.y);x.lineTo(q.x,q.y);x.strokeStyle='rgba(116,145,186,.16)';x.lineWidth=1;x.stroke()}}nodes.forEach((n,i)=>{const p=positions[i],rad=i===0?30:11+16*n[2],g=x.createRadialGradient(p.x,p.y,0,p.x,p.y,rad*2.8);g.addColorStop(0,roleColors[n[1]]+'bb');g.addColorStop(1,'transparent');x.fillStyle=g;x.beginPath();x.arc(p.x,p.y,rad*2.8,0,Math.PI*2);x.fill();x.beginPath();x.arc(p.x,p.y,rad,0,Math.PI*2);x.fillStyle=i===0?'#e9f7ef':roleColors[n[1]];x.fill();x.fillStyle='#dce6f2';x.font=(i===0?14:11)+'px system-ui';x.textAlign='center';x.fillText(n[0],p.x,p.y+rad+17)});$('#omegaMemoryCount').textContent=(nodes.length*(nodes.length-1)/2|0)+' potential relations';requestAnimationFrame(drawMemory)}
function branchPath(canvas,mult,turn){if(!canvas)return;const [x,w,h]=fit(canvas,130);x.clearRect(0,0,w,h);const bg=x.createLinearGradient(0,0,w,0);bg.addColorStop(0,'#08101a');bg.addColorStop(1,'#0e1826');x.fillStyle=bg;x.fillRect(0,0,w,h);const vals=[roleColors.BASE,roleColors.ALPHA,roleColors.CONSTRUCT,roleColors.PRUNE,roleColors.OMEGA];x.lineWidth=2.2;const g=x.createLinearGradient(0,0,w,0);vals.forEach((v,i)=>g.addColorStop(i/(vals.length-1),v));x.strokeStyle=g;x.beginPath();for(let i=0;i<90;i++){const u=i/89,xx=8+u*(w-16),pressure=(state.calc.q+state.calc.L)*mult,yy=h*.55+Math.sin(u*8+state.calc.phase*6.28+turn)*h*.13*(.5+pressure)-u*h*.18*(state.calc.C-state.calc.q)*mult; i?x.lineTo(xx,yy):x.moveTo(xx,yy)}x.stroke()}
function drawBranches(){branchPath($('#omegaBranchStay'),.65,0);branchPath($('#omegaBranchTurn'),1.0,1.2);branchPath($('#omegaBranchEsc'),1.4,2.2);const s=score();if($('#omegaStayMetric'))$('#omegaStayMetric').innerHTML='<span class="tiny muted">coherence '+Math.min(1,s*.62).toFixed(3)+' · burden '+(state.calc.L*.75).toFixed(3)+'</span>';if($('#omegaTurnMetric'))$('#omegaTurnMetric').innerHTML='<span class="tiny muted">adaptation '+Math.min(1,state.calc.P*.88+state.calc.q*.12).toFixed(3)+' · contradiction '+(state.calc.q*.82).toFixed(3)+'</span>';if($('#omegaEscMetric'))$('#omegaEscMetric').innerHTML='<span class="tiny muted">expansion '+Math.min(1,state.calc.P+state.calc.L*.35).toFixed(3)+' · risk '+Math.min(1,state.calc.q+state.calc.L*.5).toFixed(3)+'</span>'}
function runSim(){state.simTick++;drawBranches();const packet={evidence_class:'SIMULATED_CONTINUATION',starting_state_digest:state.canonical?.digest||null,starting_state_evidence_class:state.canonical?.state?.evidence_class||'USER_DEFINED_MODEL',projection_source:state.calcSource,dt:state.dt,shell:state.shell,variables:state.calc,dispatch_candidates:['STAY','TURN','ESCALATE'],simulation_tick:state.simTick};$('#omegaSimProof').textContent=JSON.stringify(packet,null,2)}
function renderPalette(term=''){const list=$('#omegaPaletteList'),q=term.trim().toLowerCase();if(!list)return;list.innerHTML='';commands.filter(c=>!q||c[0].toLowerCase().includes(q)||c[1].toLowerCase().includes(q)).forEach((c,i)=>{const b=document.createElement('button');b.className='paletteItem'+(i===0?' active':'');b.innerHTML='<b>'+c[0]+'</b><small>'+c[2]+'</small>';b.onclick=()=>{if(c[2]==='route')location.href=c[1];else openApp(c[1]);$('#omegaPalette').classList.remove('open')};list.append(b)})}
function openPalette(){renderPalette();$('#omegaPalette').classList.add('open');setTimeout(()=>$('#omegaPaletteInput')?.focus(),0)}
injectWorkspaces();all('[data-open-app]').forEach(b=>b.addEventListener('click',()=>openApp(b.dataset.openApp)));$('#omegaEnter')?.addEventListener('click',closeLaunch);try{if(sessionStorage.getItem('omega_launch_seen')==='1')$('#omegaLaunch')?.classList.add('hidden')}catch{}all('[data-dock-app]').forEach(b=>b.addEventListener('click',()=>openApp(b.dataset.dockApp)));$('#omegaPaletteOpen')?.addEventListener('click',openPalette);$('#omegaPaletteInput')?.addEventListener('input',e=>renderPalette(e.target.value));$('#omegaPalette')?.addEventListener('click',e=>{if(e.target.id==='omegaPalette')e.currentTarget.classList.remove('open')});$('#omegaRunSim')?.addEventListener('click',runSim);$('#omegaAdvanceSim')?.addEventListener('click',()=>{state.dt=Math.min(120,state.dt+12);if($('#omegaDt'))$('#omegaDt').value=state.dt;if($('#omegaDtOut'))$('#omegaDtOut').textContent=state.dt;runSim()});addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape')$('#omegaPalette')?.classList.remove('open')});const existing=$('#search');existing?.addEventListener('focus',()=>{existing.placeholder='Search applications or commands… · Ctrl/⌘ K for palette'});renderModeChips();drawCalc();drawMemory();drawBranches();
})();</script>`;

export async function enhanceHdLaunchNavigation(response:Response,pathname:string):Promise<Response>{
  if(pathname!=="/"&&pathname!=="")return response;
  const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;
  const text=await response.text();if(!text.includes('id="nav"')||text.includes('id="omegaLaunch"'))return new Response(text,{status:response.status,headers:response.headers});
  const body=text.replace('</head>',css+'</head>').replace('<body>','<body>'+launch+palette).replace('</body>',dock+script+'</body>');
  const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-omega-ui','rich-operational-expansion-r126');
  return new Response(body,{status:response.status,headers});
}
