export const LIVE_PHASE_VISUAL_BOUNDARY = "R138 separates the live visual-computation channel from chat/text output and phase-locks visual sequencing to UTC milliseconds. The visual channel sequences time, phase, representational shell depth, symmetry/asymmetry, the 20,736-coordinate control shell and governed mode/operator participation over the existing canonical packet. It does not convert animation into evidence, does not mutate canonical state, and does not treat 144/1728/20736/12^n as physical dimensions.";

const css=`<style id="omegaLivePhaseVisualStyle">
:root{--op-alpha:#9b6cff;--op-base:#e6bd4e;--op-construct:#ef625f;--op-prune:#4f8fff;--op-omega:#42cb7c;--phase-bg:#02050a;--phase-line:#233953;--phase-text:#eaf2ff;--phase-muted:#7f94ad}
#omegaLivePhaseRail{position:sticky;top:72px;z-index:46;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;margin:0 0 12px;padding:9px 12px;border:1px solid #263d59;border-radius:15px;background:rgba(3,8,14,.86);backdrop-filter:blur(18px);box-shadow:0 14px 42px #0007}
.olpTrack{height:4px;border-radius:99px;overflow:hidden;background:#111d2a;position:relative}.olpTrack:after{content:"";position:absolute;inset:0 auto 0 0;width:var(--phase-progress,0%);background:linear-gradient(90deg,var(--op-alpha),var(--op-base),var(--op-construct),var(--op-prune),var(--op-omega));box-shadow:0 0 18px rgba(230,189,78,.45);transition:width .08s linear}.olpRead{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.olpPill{border:1px solid #334d6c;border-radius:999px;padding:5px 8px;background:#06101acc;color:#9eb1c8;font:700 9px/1.1 ui-monospace,monospace;letter-spacing:.04em}.olpPill strong{color:#fff}.olpVisualOnly{position:relative}.olpVisualOnly:before{content:"VISUAL COMPUTATION CHANNEL";position:absolute;left:12px;top:10px;z-index:8;color:#6f849e;font:700 8px ui-monospace,monospace;letter-spacing:.14em;pointer-events:none}.olpChatBoundary{border-left:2px solid #334b68!important;background:linear-gradient(180deg,rgba(7,13,22,.96),rgba(4,8,14,.96))!important}.olpChatBoundary:before{content:"TEXT / CHAT CHANNEL";display:block;color:#7589a2;font:700 8px ui-monospace,monospace;letter-spacing:.14em;margin-bottom:8px}.archiveWorkstation{isolation:isolate}.archiveWorkstation .awViewport{min-height:clamp(620px,72vh,1040px)!important;background:radial-gradient(circle at 50% 48%,#10213a 0,#06101b 38%,#02050a 78%)!important}.archiveWorkstation .awPanel{background:rgba(4,9,15,.94)!important}.archiveWorkstation .awTop{background:linear-gradient(180deg,#0a1522,#050b13)!important}.awViewport:after{content:"";position:absolute;inset:0;z-index:5;pointer-events:none;background:radial-gradient(circle at 50% 50%,transparent 0 38%,rgba(0,0,0,.18) 72%,rgba(0,0,0,.52)),linear-gradient(90deg,rgba(79,143,255,.025) 1px,transparent 1px),linear-gradient(rgba(79,143,255,.02) 1px,transparent 1px);background-size:auto,32px 32px,32px 32px;mix-blend-mode:screen}.awVirtualHud,.awStamp{z-index:8!important}.awVirtualLegend,.awCaption{z-index:8!important}.awLens{letter-spacing:.035em}.awLens.active{box-shadow:0 0 0 1px rgba(255,255,255,.04),0 0 22px rgba(111,151,204,.12)}
@media(max-width:760px){#omegaLivePhaseRail{top:104px;grid-template-columns:1fr;padding:8px}.olpRead{justify-content:flex-start;overflow-x:auto;flex-wrap:nowrap}.olpPill{white-space:nowrap}.archiveWorkstation .awViewport{min-height:66vh!important}}
</style>`;

const rail=`<div id="omegaLivePhaseRail" aria-label="Live phase and dimensional relativity sequence"><div class="olpTrack"></div><div class="olpRead"><span class="olpPill">UTC <strong id="olpClock">--:--:--.---</strong></span><span class="olpPill">PHASE <strong id="olpPhase">01/12</strong></span><span class="olpPill">CONTROL <strong id="olpControl">20,736D</strong></span><span class="olpPill">RELATIVITY <strong id="olpShell">144</strong></span><span class="olpPill">MODE <strong id="olpMode">BASELINE</strong></span><span class="olpPill">SYM/ASYM <strong id="olpSym">—</strong></span></div></div>`;

const js=`<script id="omegaLivePhaseVisualRuntime">(()=>{const rail=document.querySelector('#omegaLivePhaseRail');if(!rail)return;const q=s=>document.querySelector(s),shells=[144,1728,20736,248832,2985984,35831808,429981696,5159780352,61917364224];const state={phase:0,depth:0,sym:.5,asym:.5};function n(id,f=.5){const e=q('#'+id);const v=Number(e?.value);return Number.isFinite(v)?Math.max(0,Math.min(1,v)):f}function tick(){const now=Date.now(),sec=now/1000,c=n('c',.72),p=n('p',.68),qq=n('q',.18),b=n('b',.28),ph=n('phase',.42),mode=q('#hdMode')?.textContent?.trim()||q('[data-mode].active')?.textContent?.trim()||'BASELINE';const phaseRate=.035+.11*p+.04*c;state.phase=(ph*12+sec*phaseRate)%12;const phaseI=Math.floor(state.phase);const cycle=(sec*(.025+.025*p)+ph)%1;state.depth=Math.min(shells.length-1,Math.floor(cycle*shells.length));state.sym=Math.max(0,Math.min(1,(c+(1-qq)+(1-b)+(.5+.5*Math.cos(state.phase*Math.PI/6)))/4));state.asym=Math.max(0,Math.min(1,(qq+b+(1-c)+(.5+.5*Math.sin((state.phase+1)*Math.PI/6)))/4));rail.style.setProperty('--phase-progress',(((state.phase%12)/12)*100).toFixed(3)+'%');q('#olpClock').textContent=new Date(now).toISOString().slice(11,23)+'Z';q('#olpPhase').textContent=String(phaseI+1).padStart(2,'0')+'/12';q('#olpControl').textContent='20,736D';q('#olpShell').textContent=shells[state.depth].toLocaleString();q('#olpMode').textContent=mode.slice(0,22);q('#olpSym').textContent=state.sym.toFixed(3)+' / '+state.asym.toFixed(3);document.documentElement.dataset.omegaUtcMs=String(now);document.documentElement.dataset.omegaPhase=String(phaseI+1);document.documentElement.dataset.omegaRelativity=String(shells[state.depth]);document.documentElement.dataset.omegaControlShell='20736';requestAnimationFrame(tick)}const aw=q('#archiveWorkstation');if(aw){aw.classList.add('olpVisualOnly');const vp=q('#awViewport');vp?.classList.add('olpVisualOnly')}document.querySelectorAll('[data-view="Assistant"],.assistant,.chat,.chatPanel,[id*="assistant" i],[class*="assistant" i]').forEach(e=>e.classList.add('olpChatBoundary'));requestAnimationFrame(tick)})();</script>`;

export async function enhanceLivePhaseVisual(response:Response):Promise<Response>{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('OMEGA V6')||html.includes('omegaLivePhaseVisualStyle'))return new Response(html,{status:response.status,headers:response.headers});html=html.replace('</head>',css+'</head>');const target=html.includes('<main class="work">')?'<main class="work">':html.includes('<main class="wrap">')?'<main class="wrap">':'<body>';html=html.replace(target,target+rail);html=html.replace('</body>',js+'</body>');return new Response(html,{status:response.status,headers:response.headers});}
