export const MEMORY_SCAR_BOUNDARY = "Memory/scar packets are browser-supplied historical evidence for bounded comparison. They do not rewrite canonical V6/Genesis state, establish causation, or validate a forecast without held-out observations.";

export type ScarEvent = { t:number; continuity:number; plasticity:number; contradiction:number; burden:number; outcome:number|null; provenance:string };
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:null;
function event(v:any):ScarEvent|null{if(!v||typeof v!=="object")return null;const t=num(v.t),c=num(v.continuity),p=num(v.plasticity),q=num(v.contradiction),b=num(v.burden),o=v.outcome==null?null:num(v.outcome);if([t,c,p,q,b].some(x=>x===null))return null;if([c,p,q,b].some(x=>x!<0||x!>1)||o!==null&&(o<0||o>1))return null;return{t:t!,continuity:c!,plasticity:p!,contradiction:q!,burden:b!,outcome:o,provenance:String(v.provenance||"UNSPECIFIED").slice(0,240)}}
const score=(e:ScarEvent)=>clamp((e.continuity*e.plasticity)/(e.contradiction+e.burden+0.05));
export function memoryScarSchema(){return{schema:"OMEGA_MEMORY_SCAR_FORECAST_V1",authority:"computation-only",mutation:false,event_fields:["t","continuity","plasticity","contradiction","burden","outcome","provenance"],scar_rule:"Scar burden is the exponentially recency-weighted contradiction+burden history; it is a model feature, not a physical primitive.",forecast_rule:"Compare memory-aware forecast against a memoryless current-state baseline on held-out outcomes.",boundary:MEMORY_SCAR_BOUNDARY}}
export function evaluateMemoryScar(body:any){const raw=Array.isArray(body?.events)?body.events:[],events=raw.map(event).filter(Boolean) as ScarEvent[];if(events.length<2)return{status:400,body:{ok:false,error:"at_least_two_valid_events_required",boundary:MEMORY_SCAR_BOUNDARY}};events.sort((a,b)=>a.t-b.t);const alpha=typeof body?.alpha==="number"&&body.alpha>0&&body.alpha<=1?body.alpha:.72;let scar=0,continuity=events[0].continuity;const trace=events.map((e,i)=>{scar=alpha*scar+(1-alpha)*clamp((e.contradiction+e.burden)/2);continuity=i?alpha*continuity+(1-alpha)*e.continuity:e.continuity;return{t:e.t,scar:Number(scar.toFixed(6)),continuity_memory:Number(continuity.toFixed(6)),state_score:Number(score(e).toFixed(6))}});const observed=events.filter(e=>e.outcome!==null);let memoryBrier:null|number=null,baselineBrier:null|number=null;if(observed.length){let mem=0,base=0;for(const e of observed){const s=trace[events.indexOf(e)];const baseline=score(e);const memory=clamp(baseline*(1-s.scar)*(.5+.5*s.continuity_memory));mem+=(memory-e.outcome!)**2;base+=(baseline-e.outcome!)**2}memoryBrier=mem/observed.length;baselineBrier=base/observed.length}const last=events.at(-1)!,lastTrace=trace.at(-1)!;const baseline=score(last),forecast=clamp(baseline*(1-lastTrace.scar)*(.5+.5*lastTrace.continuity_memory));return{status:200,body:{ok:true,schema:"OMEGA_MEMORY_SCAR_FORECAST_EVALUATION_V1",mutation:false,event_count:events.length,alpha,trace,current:{scar:lastTrace.scar,continuity_memory:lastTrace.continuity_memory,memoryless_score:Number(baseline.toFixed(6)),memory_aware_forecast:Number(forecast.toFixed(6))},validation:{held_out_outcomes:observed.length,memory_brier:memoryBrier===null?null:Number(memoryBrier.toFixed(6)),memoryless_brier:baselineBrier===null?null:Number(baselineBrier.toFixed(6)),memory_improves_brier:memoryBrier!==null&&baselineBrier!==null?memoryBrier<baselineBrier:null,independently_validated:false},boundary:MEMORY_SCAR_BOUNDARY}}}
