export const SAI_HYBRID_MOTION_RELEASE = "r168-sai-hybrid-motion-fabric";
export const SAI_HYBRID_MOTION_BOUNDARY = "R168 adds a high-definition presentation layer that fuses canonical state, route-authority readiness, current Hybrid heartbeat truth and governed development status into motion. It does not create a second state authority, does not claim that the PC is online unless heartbeatTruth reports pc_online=true, does not fabricate model execution, and does not mutate canonical state. Its SAI/Hybrid context is appended to the existing atlas context as classified routing context for the already-governed route-before-generation pipeline.";

const style = `<style id="omegaSaiHybridMotionStyle">
#omegaSaiHybridCanvas{position:absolute;inset:0;width:100%;height:100%;z-index:4;pointer-events:none;mix-blend-mode:screen;opacity:.9;transition:opacity .2s ease}
#omegaSaiHybridCanvas[data-enabled="false"]{opacity:0}
#omegaSaiHybridHud{position:absolute;z-index:9;left:18px;bottom:78px;display:flex;gap:6px;align-items:center;max-width:calc(100% - 36px);pointer-events:none;transition:.2s opacity,.2s transform}
#omegaSaiHybridHud[data-enabled="false"]{opacity:0;transform:translateY(6px)}
.oshPill{display:flex;align-items:center;gap:6px;min-height:28px;padding:6px 8px;border:1px solid rgba(93,132,177,.35);border-radius:999px;background:rgba(3,8,14,.72);backdrop-filter:blur(16px);color:#8ca2ba;font:750 8px/1 ui-monospace,monospace;letter-spacing:.05em;white-space:nowrap}.oshPill b{color:#f4f8ff}.oshDot{width:6px;height:6px;border-radius:50%;background:#657489;box-shadow:0 0 0 transparent}.oshDot.ready{background:#6ed89f;box-shadow:0 0 14px rgba(110,216,159,.75)}.oshDot.warn{background:#e2bd65}.oshDot.active{background:#d993ff;box-shadow:0 0 16px rgba(217,147,255,.65)}
#omegaSaiHybridLayerStatus{margin-top:8px}
@media(max-width:760px){#omegaSaiHybridHud{left:10px;right:10px;bottom:146px;overflow-x:auto;scrollbar-width:none}#omegaSaiHybridHud::-webkit-scrollbar{display:none}.oshPill:nth-child(n+4){display:none}}
@media(prefers-reduced-motion:reduce){#omegaSaiHybridCanvas,#omegaSaiHybridHud{transition:none}}
</style>`;

const script = `<script id="omegaSaiHybridMotionRuntime">(()=>{
const RELEASE='r168-sai-hybrid-motion-fabric',BOUNDARY='presentation-only; canonical state and heartbeatTruth remain authoritative';
const root=document.querySelector('#gma'),vp=root&&root.querySelector('.gmaViewport'),grid=root&&root.querySelector('.gmaLayerGrid');if(!root||!vp||!grid)return;
if(document.querySelector('#omegaSaiHybridCanvas'))return;
const layer=document.createElement('button');layer.className='gmaLayer';layer.dataset.gmaLayer='sai';layer.setAttribute('aria-pressed','true');layer.innerHTML='<b>SAI / HYBRID</b><small>AI + heartbeat compute motion</small>';grid.appendChild(layer);
const truth=document.createElement('div');truth.id='omegaSaiHybridLayerStatus';truth.className='gmaLayerTruth';truth.textContent='SAI / Hybrid motion is reading governed runtime truth. No execution claim is inferred from animation.';grid.parentElement&&grid.parentElement.appendChild(truth);
const canvas=document.createElement('canvas');canvas.id='omegaSaiHybridCanvas';canvas.dataset.enabled='true';canvas.setAttribute('aria-hidden','true');vp.appendChild(canvas);
const hud=document.createElement('div');hud.id='omegaSaiHybridHud';hud.dataset.enabled='true';hud.innerHTML='<span class="oshPill"><i class="oshDot" id="oshRouteDot"></i>SAI <b id="oshRoute">PROBING</b></span><span class="oshPill"><i class="oshDot" id="oshHybridDot"></i>HYBRID <b id="oshHybrid">UNPROVEN</b></span><span class="oshPill"><i class="oshDot" id="oshDevDot"></i>BUILD <b id="oshDev">IDLE</b></span><span class="oshPill">LOD <b id="oshLod">—</b></span><span class="oshPill">FRAME <b id="oshFrame">0</b></span>';vp.appendChild(hud);
const ctx=canvas.getContext('2d',{alpha:true}),q=s=>document.querySelector(s),TAU=Math.PI*2,phasePalette=['#f4f7ff','#d993ff','#efb06a','#68d6cf','#ef7474','#93c56f','#b7a0ff','#f0cb6d','#62a9ff','#e58fb8','#7dddb3','#d6e2f2'];
let W=1,H=1,D=1,last=performance.now(),ema=16.7,frame=0,running=true,enabled=true,snapshot={state:null,route:false,pc:false,heartbeat:false,dev:false,devLabel:'IDLE',address:[1,1,1,1],evidence:'UNAVAILABLE',digest:''},scar=[],refreshBusy=false;
function clamp(v){return Math.max(0,Math.min(1,Number(v)||0))}
function parseState(d){const s=d&&d.state,m=s&&s.metrics,a=Array.isArray(s&&s.address)?s.address.map(Number):null;if(!s||!m||!a||a.length!==4)return null;const vals=[Number(m.continuity),Number(m.future_plasticity),Number(m.contradiction),Number(m.burden)];if(vals.some(v=>!Number.isFinite(v))||a.some(v=>!Number.isInteger(v)||v<1||v>12))return null;return{c:clamp(vals[0]),p:clamp(vals[1]),q:clamp(vals[2]),b:clamp(vals[3]),address:a,evidence:String(s.evidence_class||'UNKNOWN'),digest:String(d.digest||'')}}
async function get(path){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)return null;return await r.json()}catch{return null}}
function publishContext(){const s=snapshot.state,context={release:RELEASE,evidence_class:s?s.evidence:'UNAVAILABLE',canonical_state_bound:Boolean(s),canonical_digest:s?s.digest:'',address20736:s?s.address:null,route_authority_ready:Boolean(snapshot.route),hybrid:{pc_online:Boolean(snapshot.pc),heartbeat_current:Boolean(snapshot.heartbeat)},development:{active:Boolean(snapshot.dev),label:snapshot.devLabel},boundary:BOUNDARY};window.OMEGA_SAI_HYBRID_CONTEXT=context;const base=window.OMEGA_ATLAS_CONTEXT&&typeof window.OMEGA_ATLAS_CONTEXT==='object'?window.OMEGA_ATLAS_CONTEXT:{};window.OMEGA_ATLAS_CONTEXT=Object.assign({},base,{sai_hybrid:context})}
function setStatus(){const route=q('#oshRoute'),rd=q('#oshRouteDot'),hy=q('#oshHybrid'),hd=q('#oshHybridDot'),dv=q('#oshDev'),dd=q('#oshDevDot');if(route){route.textContent=snapshot.route?'ROUTE READY':'ROUTE UNPROVEN';rd.className='oshDot '+(snapshot.route?'ready':'warn')}if(hy){hy.textContent=snapshot.pc?'PC ONLINE':(snapshot.heartbeat?'HEARTBEAT CURRENT':'PC UNPROVEN');hd.className='oshDot '+(snapshot.pc?'ready':snapshot.heartbeat?'warn':'')}if(dv){dv.textContent=snapshot.devLabel;dd.className='oshDot '+(snapshot.dev?'active':'')}truth.textContent=(snapshot.state?'CANONICAL '+snapshot.state.evidence:'CANONICAL STATE UNAVAILABLE')+' · '+(snapshot.route?'route authority ready':'route authority unproven')+' · '+(snapshot.pc?'PC ONLINE by heartbeatTruth':'PC online not proven')+' · motion is derived presentation only.';document.documentElement.dataset.omegaSaiHybridState=snapshot.pc?'pc-online':snapshot.heartbeat?'heartbeat-current':'unproven'}
async function refresh(){if(refreshBusy)return;refreshBusy=true;const [state,edge,hybrid,dev]=await Promise.all([get('/api/omega/state'),get('/api/convergence/edge'),get('/api/hybrid/status'),get('/api/development/status')]);snapshot.state=parseState(state);const pc=edge&&edge.topology&&edge.topology.sovereign_pc||{};snapshot.pc=Boolean(pc.pc_online);snapshot.heartbeat=Boolean(pc.heartbeat_current);snapshot.route=Boolean(edge&&edge.convergence&&edge.convergence.authority_contract_ready);const active=dev&&((dev.active_job)||(dev.development&&dev.development.active_job));snapshot.dev=Boolean(active);snapshot.devLabel=active?String(active.kind||active.state||'ACTIVE').slice(0,22):String((dev&&dev.mode)||(dev&&dev.development&&dev.development.mode)||'IDLE').slice(0,22);if(!snapshot.heartbeat&&hybrid&&hybrid.heartbeat_current===true)snapshot.heartbeat=true;publishContext();setStatus();refreshBusy=false}
function fit(){const r=vp.getBoundingClientRect();D=Math.min(3,devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0)}
function node(k,phase,zoom){const a=(k/12)*TAU+phase*.018,ring=.19+((k*7)%5)*.052,rx=Math.min(W,H)*ring*zoom,ry=rx*(.62+.08*Math.sin(phase*.2+k));return{x:W*.5+Math.cos(a)*rx,y:H*.48+Math.sin(a)*ry}}
function draw(now){if(!ctx)return;const dt=Math.min(80,now-last);last=now;ema=ema*.93+dt*.07;frame++;if(!running){requestAnimationFrame(draw);return}ctx.clearRect(0,0,W,H);if(!enabled){requestAnimationFrame(draw);return}const s=snapshot.state||{c:.5,p:.5,q:.5,b:.5,address:[1,1,1,1]},phase=s.address[1]-1,t=now/1000,zoom=1+.025*Math.sin(t*.18),quality=ema<18?1:ema<24?.82:ema<32?.64:.48,lod=quality>.9?20736:quality>.7?1728:144,paths=quality>.9?144:quality>.7?96:54,particles=quality>.9?1728:quality>.7?864:432,base=phasePalette[phase]||'#f4f7ff';q('#oshLod').textContent=String(lod);q('#oshFrame').textContent=String(frame%100000);
ctx.globalCompositeOperation='lighter';ctx.lineCap='round';
for(let k=0;k<12;k++){const a=node(k,phase+t*.08,zoom),b=node((k+1+s.address[0])%12,phase-t*.05,zoom),c=node((k+s.address[2])%12,phase+t*.03,zoom);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.bezierCurveTo(W*.5+(a.x-W*.5)*.18,H*.48+(c.y-H*.48)*.22,W*.5+(b.x-W*.5)*.18,H*.48+(a.y-H*.48)*.22,b.x,b.y);ctx.strokeStyle=base;ctx.globalAlpha=.025+.05*s.c+.035*(snapshot.route?1:0);ctx.lineWidth=.5+1.2*s.p;ctx.stroke()}
for(let i=0;i<paths;i++){const u=i/paths,k=(i+s.address[3])%12,a=node(k,phase+t*(.05+.02*s.p),zoom),b=node((k+3+phase)%12,phase-t*.035,zoom),spin=(u-.5)*TAU,midX=W*.5+Math.cos(spin+t*.2)*Math.min(W,H)*(.035+.1*s.p),midY=H*.48+Math.sin(spin-t*.16)*Math.min(W,H)*(.025+.07*s.c);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(midX,midY,b.x,b.y);ctx.globalAlpha=.012+.035*(1-s.q)+.018*(snapshot.pc?1:0);ctx.lineWidth=.35+(i%5)*.12;ctx.strokeStyle=phasePalette[(phase+i)%12];ctx.stroke()}
for(let i=0;i<particles;i++){const seed=(i*73)%997/997,a=(seed*TAU*4+t*(.18+.4*s.p)+(i%12)*TAU/12),r=Math.min(W,H)*(.06+.37*((i*191)%991)/991),warp=1+.09*Math.sin(a*3+t*.7+s.q*4)+.05*Math.cos(a*5-t*.3+s.b*5),x=W*.5+Math.cos(a)*r*warp,y=H*.48+Math.sin(a)*r*(.62+.18*s.c),pulse=.5+.5*Math.sin(t*2.2+i*.17+(snapshot.dev?1.7:0));ctx.fillStyle=phasePalette[(phase+(i%5)*2)%12];ctx.globalAlpha=.025+.085*pulse*(snapshot.route?1:.55)+.035*(snapshot.pc?1:0);const size=.45+1.65*pulse+(snapshot.dev ? .4 : 0);ctx.fillRect(x,y,size,size)}
const focus=node(phase,phase+t*.12,zoom),scarPoint={x:focus.x,y:focus.y,t:now};if(frame%6===0){scar.push(scarPoint);if(scar.length>96)scar.shift()}if(scar.length>2){ctx.beginPath();scar.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.globalAlpha=.08+.12*s.b;ctx.lineWidth=.8+1.4*s.q;ctx.strokeStyle=phasePalette[(phase+9)%12];ctx.stroke()}
ctx.beginPath();ctx.arc(focus.x,focus.y,5+8*(snapshot.dev?1:.35)+4*Math.sin(t*2)**2,0,TAU);ctx.globalAlpha=.18+.22*(snapshot.route?1:.4);ctx.lineWidth=1.2;ctx.strokeStyle=base;ctx.stroke();ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';requestAnimationFrame(draw)}
function syncLayer(){enabled=layer.getAttribute('aria-pressed')==='true';canvas.dataset.enabled=String(enabled);hud.dataset.enabled=String(enabled);const all=[...grid.querySelectorAll('[data-gma-layer]')];const counter=q('#gmaLayers');if(counter)counter.textContent=String(all.filter(b=>b.getAttribute('aria-pressed')==='true').length)+'/'+String(all.length)}
layer.addEventListener('click',()=>setTimeout(syncLayer,0));document.addEventListener('omega-field-layer',syncLayer);document.addEventListener('omega-field-pause',e=>{running=!(e.detail&&e.detail.paused)});document.addEventListener('omega-field-reset',()=>{scar.length=0;frame=0});addEventListener('resize',fit,{passive:true});
fit();syncLayer();refresh();setInterval(refresh,2500);if(matchMedia('(prefers-reduced-motion: reduce)').matches){draw(performance.now());running=false}else requestAnimationFrame(draw);
})();</script>`;

export async function enhanceSaiHybridComputeField(response: Response): Promise<Response> {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  let html = await response.text();
  if (!html.includes("OMEGA V6") || html.includes("omegaSaiHybridMotionStyle")) return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  html = html.replace("</head>", style + "</head>");
  html = html.replace("</body>", script + "</body>");
  return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
}
