const R199_STYLE = `<style id="omega-r199-pc-style">
.r199pc{margin-top:16px;border:1px solid #33445f;border-radius:18px;background:linear-gradient(180deg,#0d1622,#080d14);padding:16px}.r199pcHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.r199pcHead h2{margin:4px 0 5px}.r199pcBadges,.r199pcActions{display:flex;gap:7px;flex-wrap:wrap}.r199pcBadge{border:1px solid #35465f;border-radius:999px;padding:6px 9px;background:#0a111a;font-size:.74rem}.r199pcGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-top:12px}.r199pcMetric{border:1px solid #28374d;border-radius:12px;padding:11px;background:#09111a}.r199pcMetric span{display:block;color:#92a1b6;font-size:.72rem;text-transform:uppercase;letter-spacing:.08em}.r199pcMetric b{display:block;margin-top:4px;font-size:1.02rem;overflow-wrap:anywhere}.r199pcPipe{display:grid;grid-template-columns:repeat(7,minmax(105px,1fr));gap:7px;margin-top:14px}.r199pcStage{border:1px solid #2c3a50;border-radius:12px;padding:10px;min-height:82px;background:#091019}.r199pcStage.ok{border-color:#2d8054;background:#0c1d16}.r199pcStage.warn{border-color:#8b713a;background:#1b160f}.r199pcStage.bad{border-color:#8c4545;background:#1c1112}.r199pcStage small{display:block;color:#8fa0b6}.r199pcStage b{display:block;margin-top:5px}.r199pcActions{margin-top:13px}.r199pcMsg{margin-top:10px;color:#a7b4c7;white-space:pre-wrap}.r199pcReceipt{margin-top:12px;border-top:1px solid #26354a;padding-top:10px}.r199pcReceipt pre{max-height:300px;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:.75rem;color:#a8b6ca}.r199pc button{border:1px solid #40526d;border-radius:11px;background:#101925;padding:9px 12px;color:#f4f7ff;cursor:pointer}.r199pc button.primary{background:#193052;border-color:#6487b8}.r199pc button:disabled{opacity:.42;cursor:not-allowed}@media(max-width:1100px){.r199pcGrid{grid-template-columns:1fr 1fr}.r199pcPipe{grid-template-columns:repeat(4,1fr)}}@media(max-width:700px){.r199pcHead{display:block}.r199pcGrid,.r199pcPipe{grid-template-columns:1fr}.r199pcActions button{width:100%}}
</style>`;

const R199_SCRIPT = `<script id="omega-r199-pc-script">
(function(){
const SESSION_KEY='omega.v6.runtime.session.r32',BRIDGE_KEY='omega.v6.hybrid.bridge.r32';let latest=null,active=false;
function el(id){return document.getElementById(id)}function h(v){return String(v==null?'—':v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function session(){let id='';try{id=localStorage.getItem(SESSION_KEY)||''}catch(_){}if(!/^[A-Za-z0-9._:-]{8,128}$/.test(id)){id='session_'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));try{localStorage.setItem(SESSION_KEY,id)}catch(_){}}return id}
function bridge(){try{let x=JSON.parse(localStorage.getItem(BRIDGE_KEY)||'null');return x&&x.bridgeId&&x.secret?x:null}catch(_){return null}}
function saveBridge(x){let v={bridgeId:x.bridgeId,secret:x.secret,pairingCode:x.pairingCode,createdAt:Date.now()};localStorage.setItem(BRIDGE_KEY,JSON.stringify(v));return v}
async function api(method,path,body){let b=bridge(),headers={'x-omega-session-id':session()};if(b){headers['x-omega-bridge-id']=b.bridgeId;headers['x-omega-bridge-secret']=b.secret}if(body!==undefined)headers['content-type']='application/json';let r=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'}),t=await r.text(),d;try{d=JSON.parse(t)}catch(_){d={raw:t}}if(!r.ok){let e=new Error(d.reply||d.code||('HTTP '+r.status));e.data=d;throw e}return d}
function metric(k,v){return '<div class="r199pcMetric"><span>'+h(k)+'</span><b>'+h(v)+'</b></div>'}
function stage(name,state,cls){return '<div class="r199pcStage '+(cls||'')+'"><small>'+h(name)+'</small><b>'+h(state)+'</b></div>'}
function bytes(v){let n=Number(v);if(!Number.isFinite(n)||n<=0)return'—';return n>=1073741824?(n/1073741824).toFixed(1)+' GiB':(n/1048576).toFixed(0)+' MiB'}
function onlineDevice(d){let rows=Array.isArray(d.devices)?d.devices:[];let b=bridge();return rows.find(x=>x.online&&!x.revoked&&(!b||x.id===b.deviceId||true))||rows.find(x=>x.online&&!x.revoked)||null}
function lastJob(d){let jobs=Array.isArray(d.jobs)?d.jobs:[];return jobs.length?jobs[jobs.length-1]:null}
function proof(job,op){let rows=job&&job.returnPacket&&Array.isArray(job.returnPacket.stepProofs)?job.returnPacket.stepProofs:[];return rows.find(x=>String(x.op).toUpperCase()===op)||null}
function render(d){latest=d;let device=onlineDevice(d),disc=device&&device.projectDiscovery,res=device&&device.resourceGuard,sel=disc&&disc.selected,job=lastJob(d),verify=job&&job.returnVerification;let closure=device&&device.sovereignClosureRevision||'LEGACY',ready=!!(device&&device.online&&sel&&res&&res.readyForHeavyWork&&closure==='R199');let activeStates=['QUEUED','LEASED','RUNNING','RETURNED_SUCCESS','RETURNED_FAILURE'];active=!!(job&&activeStates.includes(job.status));
el('r199Project').textContent=sel?sel.relativePath:'No project selected';el('r199Confidence').textContent=disc?disc.confidence||'UNKNOWN':'NO DISCOVERY';el('r199Resource').textContent=res?(res.readyForHeavyWork?'READY':'GUARDED'):'NO TELEMETRY';el('r199Revision').textContent=closure==='R199'?'R199 FULL':'UPGRADE REQUIRED';
el('r199Metrics').innerHTML=metric('Project types',sel&&sel.projectTypes?sel.projectTypes.join(' · '):'—')+metric('Disk free',res&&res.disk?bytes(res.disk.freeBytes):'—')+metric('Memory free',res&&res.memory?bytes(res.memory.availableBytes):'—')+metric('Latest job',job?job.status:'IDLE');
let build=proof(job,'BUILD'),test=proof(job,'TEST'),pack=proof(job,'PACKAGE');let discoveryState=sel?'SELECTED':'WAITING',preflightState=res?(res.readyForHeavyWork?'PASS':'BLOCKED'):'WAITING';
el('r199Pipeline').innerHTML=stage('DISCOVER',discoveryState,sel?'ok':'warn')+stage('PREFLIGHT',preflightState,res&&res.readyForHeavyWork?'ok':res?'bad':'warn')+stage('BUILD',build?(build.ok?'PASS':'FAIL'):job&&['LEASED','RUNNING'].includes(job.status)?'PENDING':'WAITING',build?(build.ok?'ok':'bad'):'')+stage('TEST',test?(test.ok?'PASS':'FAIL'):'WAITING',test?(test.ok?'ok':'bad'):'')+stage('PACKAGE',pack?(pack.ok?'PASS':'FAIL'):'WAITING',pack?(pack.ok?'ok':'bad'):'')+stage('RETURN',job?(job.status||'—'):'WAITING',job&&job.status==='COMPLETE'?'ok':job&&/FAIL|REJECT|HOLD/.test(job.status)?'bad':'')+stage('VERIFY',verify?(verify.verified?verify.state:'UNVERIFIED'):'WAITING',verify&&verify.verified?'ok':verify?'bad':'');
el('r199FullBuild').disabled=!ready||active||!bridge();el('r199Verify').disabled=!ready||active||!bridge();el('r199Pair').textContent=bridge()?'Browser paired':'Pair browser';el('r199Msg').textContent=ready?(bridge()?active?'A governed PC job is active. Heavy work remains sequential.':'R199 workstation is ready. Full Build performs build → test → package on the discovered project.':'PC is ready; pair this browser before queueing native work.'):(closure!=='R199'&&device?'The connected agent is still '+closure+'. Restart the zero-drift launcher after R199 is deployed so it promotes the new agent.':res&&!res.readyForHeavyWork?'Resource guard is blocking heavy work to protect the PC.':'Waiting for a current R199 heartbeat and deterministic project discovery.');
let receipt={device:device?{id:device.id,name:device.name,version:device.version,closure:device.sovereignClosureRevision,projectDiscovery:disc,resourceGuard:res}:null,job:job?{id:job.id,status:job.status,lifecycle:job.lifecycle,returnVerification:job.returnVerification,outputPaths:job.outputPaths}:null};el('r199ReceiptPre').textContent=JSON.stringify(receipt,null,2);
if(device&&device.online){let hs=document.getElementById('hybridState');if(hs)hs.textContent=closure==='R199'?'PC ONLINE · R199':'PC ONLINE · AGENT UPGRADE';}
}
async function refresh(){try{render(await api('GET','/api/hybrid/status'))}catch(e){el('r199Msg').textContent='R199 status unavailable: '+e.message}}
async function pairBrowser(){let current=bridge();if(current){el('r199Msg').textContent='This browser already holds an authenticated bridge credential.';return}try{let d=await api('POST','/api/hybrid/pair',{rotate:false});if(d.bridgeId&&d.secret){saveBridge(d);el('r199Msg').textContent='Browser paired. Start or restart the Windows launcher with the displayed pairing code if the agent is not already connected.';if(d.pairingCode)prompt('OMEGA pairing code — copy this into the launcher if needed:',d.pairingCode);await refresh();return}el('r199Msg').textContent='A pairing already exists but this browser does not hold its secret. Use Repair pairing only if you are ready to restart the Windows agent.'}catch(e){el('r199Msg').textContent='Pairing failed: '+e.message}}
async function repairPair(){if(!confirm('Rotate the Hybrid credential? The running Windows agent will need to be restarted with the new pairing code.'))return;try{let d=await api('POST','/api/hybrid/pair',{rotate:true});if(d.bridgeId&&d.secret){saveBridge(d);if(d.pairingCode)prompt('New OMEGA pairing code:',d.pairingCode);el('r199Msg').textContent='Pairing rotated. Restart the launcher once with the new code.';await refresh()}}catch(e){el('r199Msg').textContent='Pair repair failed: '+e.message}}
async function queue(kind){if(!latest)return;let device=onlineDevice(latest);if(!device)throw new Error('No current authenticated PC heartbeat.');let steps=kind==='verify'?[{id:'S01',op:'TEST',label:'Run declared verification',path:'.',autoProject:true,profile:'AUTO_BUILD'}]:[{id:'S01',op:'BUILD',label:'Build the discovered project',path:'.',autoProject:true,profile:'AUTO_BUILD'},{id:'S02',op:'TEST',label:'Verify the discovered project',path:'.',autoProject:true,profile:'AUTO_BUILD'},{id:'S03',op:'PACKAGE',label:'Package the verified project',path:'.',autoProject:true,profile:'AUTO_BUILD'}];let body={schema:'OMEGA_HYBRID_JOB_R199',action:kind==='verify'?'VERIFY_PROJECT':'FULL_SAFE_BUILD',profile:'AUTO_BUILD',projectPath:'.',instructions:'Operate on the deterministically discovered project under R199 resource and proof governance.',steps,targetDeviceId:device.id,confirmed:true};let d=await api('POST','/api/hybrid/jobs',body);el('r199Msg').textContent=(d.deduplicated?'Existing active job reused: ':'Queued: ')+(d.job&&d.job.id||'job');await refresh()}
function mount(){let hybrid=document.querySelector('[data-view="Hybrid"] .body');if(!hybrid||el('omegaR199Pc'))return;let box=document.createElement('section');box.id='omegaR199Pc';box.className='r199pc';box.innerHTML='<div class="r199pcHead"><div><div class="eyebrow">R199 · full sovereign workstation</div><h2>Project-aware PC execution</h2><div class="muted tiny">Not just connected: discover → preflight → build → test → package → verified return.</div></div><div class="r199pcBadges"><span class="r199pcBadge">ROOT-CONFINED</span><span class="r199pcBadge">REVERSIBLE WRITES</span><span class="r199pcBadge">SEQUENTIAL HEAVY WORK</span><span class="r199pcBadge">NO IMPLICIT INSTALLS</span><span class="r199pcBadge">NO OS TWEAKING</span></div></div><div class="r199pcGrid"><div class="r199pcMetric"><span>Selected project</span><b id="r199Project">Waiting</b></div><div class="r199pcMetric"><span>Discovery confidence</span><b id="r199Confidence">Waiting</b></div><div class="r199pcMetric"><span>PC resource guard</span><b id="r199Resource">Waiting</b></div><div class="r199pcMetric"><span>Agent closure</span><b id="r199Revision">Waiting</b></div></div><div class="r199pcGrid" id="r199Metrics"></div><div class="r199pcPipe" id="r199Pipeline"></div><div class="r199pcActions"><button id="r199Pair">Pair browser</button><button id="r199Repair">Repair pairing</button><button id="r199Refresh">Refresh readiness</button><button id="r199Verify">Verify project</button><button class="primary" id="r199FullBuild">Run full safe build</button></div><div class="r199pcMsg" id="r199Msg">Loading R199 workstation state…</div><details class="r199pcReceipt"><summary>Project / resource / return proof</summary><pre id="r199ReceiptPre">Waiting for proof.</pre></details></section>';hybrid.prepend(box);el('r199Pair').onclick=pairBrowser;el('r199Repair').onclick=repairPair;el('r199Refresh').onclick=refresh;el('r199Verify').onclick=()=>queue('verify').catch(e=>el('r199Msg').textContent='Queue failed: '+e.message);el('r199FullBuild').onclick=()=>queue('full').catch(e=>el('r199Msg').textContent='Queue failed: '+e.message);refresh();setInterval(()=>{let app=document.querySelector('.app.active');if(app&&app.dataset.view==='Hybrid')refresh()},3500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
</script>`;

export async function enhanceSovereignPcSurfaceR199(response: Response, pathname: string): Promise<Response> {
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html") || (pathname !== "/" && !pathname.startsWith("/hybrid"))) return response;
  const source = await response.text();
  if (!source.includes('data-view="Hybrid"') || source.includes('id="omega-r199-pc-style"')) {
    return new Response(source, { status: response.status, statusText: response.statusText, headers: response.headers });
  }
  const html = source.replace("</head>", R199_STYLE + "</head>").replace("</body>", R199_SCRIPT + "</body>");
  const headers = new Headers(response.headers);
  headers.set("cache-control", "no-store");
  headers.set("x-omega-sovereign-pc-surface", "R199");
  return new Response(html, { status: response.status, statusText: response.statusText, headers });
}
