import { ATLAS_SOURCE } from "./native20736Atlas";

export const UNIFIED_MOTION_RELATIVITY_BOUNDARY = "R147 renders the governed atlas as a calculus-driven field rather than a spoke diagram. The supplied 20,736-state topology supplies coefficients, focus, phase and boundary conditions; the visible surface evaluates a scalar potential, finite-difference gradient, Hessian/Laplacian curvature terms, a derived vector field, RK2 integral curves and advected trajectories. UTC render time synchronizes animation only and is not evidence time. Runtime observations, DERIVED_FRAMEWORK_MATH, SIMULATED_CONTINUATION and USER_DEFINED_MODEL projection remain distinct. 20,736 and representational 12^n shells are software/model coordinates, not physical dimensions.";

const css=`<style id="omegaUnifiedMotionRelativityStyle">
#gmaInfoUnified{border:1px solid #294159;border-radius:12px;background:linear-gradient(180deg,#07131e,#050b12);margin-bottom:9px;padding:11px}.umrHead{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:8px}.umrHead b{font:850 9px ui-monospace,monospace;letter-spacing:.1em;color:#e6bd4e}.umrLive{font:750 8px ui-monospace,monospace;color:#42cb7c}.umrMetric{display:grid;grid-template-columns:1fr auto;gap:4px 8px;color:#7990a8;font:650 8px ui-monospace,monospace}.umrMetric strong{color:#eef6ff}.umrEquation{margin-top:8px;padding:8px;border:1px solid #1e3448;border-radius:8px;background:#03080e;color:#8fa7bc;font:600 8px/1.45 ui-monospace,monospace}.umrEquation b{color:#dfeaf5}.umrPrompt{width:100%;min-height:54px;resize:vertical;margin-top:9px;border:1px solid #294159;border-radius:8px;background:#03080e;color:#e8f1fb;padding:8px;font:650 9px/1.35 ui-monospace,monospace}.umrActions{display:flex;gap:6px;margin-top:6px}.umrActions button{flex:1;border:1px solid #31506b;border-radius:7px;background:#0b1926;color:#afc4d8;padding:7px;font:750 8px ui-monospace,monospace;cursor:pointer}.umrActions button.primary{border-color:#745f26;color:#f1d16b}.umrActions button:disabled{opacity:.4}.umrResult{margin-top:7px;max-height:150px;overflow:auto;white-space:pre-wrap;color:#91a8bd;font:600 8px/1.4 ui-monospace,monospace}.umrTruth{margin-top:8px;border-top:1px solid #1d3142;padding-top:7px;color:#6f879d;font:600 8px/1.35 ui-monospace,monospace}.umrTruth b{color:#d8e5f2}
</style>`;

const card=`<div id="gmaInfoUnified"><div class="umrHead"><b>VISUAL ⇄ COMPUTE ⇄ AI · CALCULUS FIELD</b><span class="umrLive" id="umrLive">SOLVING</span></div><div class="umrMetric"><span>Atlas source</span><strong>${ATLAS_SOURCE.rows.toLocaleString()} rows</strong><span>Native states</span><strong>${ATLAS_SOURCE.atlasStates.toLocaleString()}</strong><span>Focus state</span><strong id="umrFocus">—</strong><span>|∇Φ|</span><strong id="umrGrad">—</strong><span>∇²Φ</span><strong id="umrLap">—</strong><span>curvature K</span><strong id="umrCurv">—</strong><span>flow speed</span><strong id="umrFlow">—</strong><span>Observation</span><strong id="umrObservation">—</strong></div><div class="umrEquation"><b>SOLVED SURFACE</b> · Φ(x,y,t) from state + mode + atlas focus → ∇Φ → Hessian / ∇²Φ → v(x,y,t) → RK2 trajectories. Atlas neighbor/antipode relations constrain coefficients; they are not drawn as fake geometry.</div><textarea class="umrPrompt" id="umrPrompt" placeholder="Ask OMEGA about the solved field / state / mode…"></textarea><div class="umrActions"><button class="primary" id="umrRoute">ROUTE</button><button id="umrGenerate" disabled>GENERATE</button></div><div class="umrResult" id="umrResult">AI receives the same solved-field metrics, atlas focus, mode, packet and provenance shown by this surface.</div><div class="umrTruth"><b>TRUTH BOUNDARY</b> · runtime observation ≠ derived calculus ≠ simulated continuation ≠ model projection.</div></div>`;

const js=`<script id="omegaUnifiedMotionRelativityRuntime">(()=>{
const root=document.querySelector('#gma');if(!root||document.documentElement.dataset.omegaUmr==='r147')return;document.documentElement.dataset.omegaUmr='r147';
const old=document.querySelector('#gmaCanvas');if(!old)return;const canvas=old.cloneNode(false);old.replaceWith(canvas);const ctx=canvas.getContext('2d',{alpha:false}),TAU=Math.PI*2,q=s=>document.querySelector(s),clamp=v=>Math.max(0,Math.min(1,Number(v)||0));
const info=q('.gmaInfo');if(info&&!q('#gmaInfoUnified'))info.insertAdjacentHTML('afterbegin',${JSON.stringify(card)});
const index=(d,p,r,l)=>(((d*12)+p)*12+r)*12+l;const addr=n=>{let l=n%12;n=Math.floor(n/12);let r=n%12;n=Math.floor(n/12);let p=n%12;n=Math.floor(n/12);return[n%12,p,r,l]};const antip=n=>{const a=addr(n);return index((a[0]+6)%12,(a[1]+6)%12,(a[2]+6)%12,(a[3]+6)%12)};const neigh=n=>{const a=addr(n),o=[];for(let ax=0;ax<4;ax++)for(const dir of[-1,1]){const b=a.slice();b[ax]=(b[ax]+dir+12)%12;o.push(index(b[0],b[1],b[2],b[3]))}return o};
let W=1,H=1,D=1,lastRoute=null,trail=[],quality=1,ema=16,lastFrame=performance.now();function fit(){const r=canvas.parentElement.getBoundingClientRect();D=Math.min(3,devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0)}
function num(id,f){const t=q(id)?.textContent||'';const n=Number(t.replace(/[^0-9+-.]/g,''));return Number.isFinite(n)?n:f}function activeMode(){return q('.gmaMode.active')?.dataset.gmaMode||'full-overall-canon'}function packet(){return{c:clamp(num('#gmaC',.72)),p:clamp(num('#gmaP',.68)),q:clamp(num('#gmaQ',.18)),b:clamp(num('#gmaB',.28)),dispatch:q('#gmaDispatch')?.textContent||'STAY'}}
function focusState(P,now){const phase=Math.floor((now/5000)%12),d=phase,p=Math.floor(P.c*11.999),r=Math.floor((1-P.q)*11.999),l=Math.floor(((P.p+(1-P.b))/2)*11.999);return index(d,p,r,l)}
function modeCoefficients(mode){let m=[1,1,1,1,1];if(mode==='dewey-calculus')m=[1.35,1.2,.85,1.1,1.3];else if(mode==='relational-skin')m=[.9,1.35,1.25,.8,1.05];else if(mode==='forecast')m=[.82,1.5,.72,1.18,1.35];else if(mode==='heavy-prune')m=[.72,.75,1.55,1.42,.7];else if(mode==='mode-188')m=[1.18,.88,1.42,1.15,.92];else if(mode==='unified-coherence')m=[1.45,1.12,.72,.86,1.28];else if(mode==='unified-recursion')m=[1.22,1.1,1.02,1.38,1.12];return m}
function solveContext(now){const P=packet(),mode=activeMode(),focus=focusState(P,now),a=addr(focus),neighbors=neigh(focus),anti=antip(focus),na=neighbors.map(addr),aa=addr(anti),m=modeCoefficients(mode),phase=a[0]/12*TAU+(now%60000)/60000*TAU;return{P,mode,focus,a,neighbors,na,anti,aa,m,phase}}
function potential(x,y,S){const P=S.P,a=S.a,m=S.m,ph=S.phase;const fx=(a[1]+.5)/12,fy=(a[2]+.5)/12,ax=(S.aa[1]+.5)/12,ay=(S.aa[2]+.5)/12;const dx=x-fx,dy=y-fy,da=x-ax,db=y-ay;const sig=.045+.11*(1-P.b);const focus=Math.exp(-(dx*dx+dy*dy)/sig);const anti=Math.exp(-(da*da+db*db)/(.07+.08*P.q));const k1=2+(a[3]%5),k2=3+(a[0]%4);const wave=Math.sin(TAU*(k1*x+k2*y)+ph)*Math.cos(TAU*((a[0]+1)*y/4-(a[3]+1)*x/5)-ph*.63);const fold=Math.sin(TAU*(x-y)*m[3]+ph*.7)*Math.sin(TAU*(x+y)*m[4]-ph*.31);const radial=Math.sin(TAU*Math.hypot(x-.5,y-.5)*(3+m[0]*2)-ph*.45);const boundary=Math.cos(TAU*x*(1+a[1]/12))*Math.cos(TAU*y*(1+a[2]/12));return m[0]*P.c*focus-m[2]*P.q*.72*anti+m[1]*P.p*.25*wave+m[3]*(1-P.b)*.17*fold+m[4]*.11*radial+.08*boundary}
function differential(x,y,S){const h=.0028;const f=potential(x,y,S),xp=potential(x+h,y,S),xm=potential(x-h,y,S),yp=potential(x,y+h,S),ym=potential(x,y-h,S),pp=potential(x+h,y+h,S),pm=potential(x+h,y-h,S),mp=potential(x-h,y+h,S),mm=potential(x-h,y-h,S);const gx=(xp-xm)/(2*h),gy=(yp-ym)/(2*h),fxx=(xp-2*f+xm)/(h*h),fyy=(yp-2*f+ym)/(h*h),fxy=(pp-pm-mp+mm)/(4*h*h),lap=fxx+fyy,curv=(fxx*fyy-fxy*fxy)/Math.pow(1+gx*gx+gy*gy,2);return{f,gx,gy,lap,curv}}
function velocity(x,y,S){const d=differential(x,y,S),P=S.P;const adv=.17+.48*P.p,rot=.1+.62*P.q,damp=.35+.65*(1-P.b),phaseDrift=.09*Math.sin(S.phase+TAU*y);let vx=(adv*d.gx-rot*d.gy)*.018*damp+phaseDrift,vy=(adv*d.gy+rot*d.gx)*.018*damp+.09*Math.cos(S.phase+TAU*x);const s=Math.hypot(vx,vy),cap=.32;if(s>cap){vx*=cap/s;vy*=cap/s}return{...d,vx,vy,speed:Math.hypot(vx,vy)}}
function operatorRGB(f,lap,curv,P){const alpha=[184,140,255],base=[240,201,90],construct=[255,123,114],prune=[104,167,255],omega=[101,216,148];const pos=clamp(.5+f*.7),edge=clamp(Math.abs(lap)*.0025),bend=clamp(Math.abs(curv)*.035),weights=[.08+.16*(1-pos),.14+.2*P.c,.1+.24*pos,.08+.35*edge,.16+.3*(1-P.q)+.1*bend],cols=[alpha,base,construct,prune,omega],sum=weights.reduce((a,b)=>a+b,0);return cols[0].map((_,i)=>Math.round(weights.reduce((z,w,j)=>z+w*cols[j][i],0)/sum))}
function renderField(S){const target=Math.max(52,Math.min(150,Math.round((W/7)*quality))),nx=target,ny=Math.max(38,Math.round(target*H/W)),cw=W/nx,ch=H/ny;for(let j=0;j<ny;j++){const y=(j+.5)/ny;for(let i=0;i<nx;i++){const x=(i+.5)/nx,d=differential(x,y,S),rgb=operatorRGB(d.f,d.lap,d.curv,S.P),light=clamp(.22+.32*(.5+d.f*.45)+.15*Math.tanh(Math.abs(d.lap)*.002));ctx.fillStyle='rgb('+Math.round(rgb[0]*light)+','+Math.round(rgb[1]*light)+','+Math.round(rgb[2]*light)+')';ctx.fillRect(i*cw,j*ch,cw+1,ch+1)}}}
function renderContours(S){const levels=[-.5,-.25,0,.25,.5],nx=Math.max(42,Math.round(W/18));ctx.lineWidth=.65;for(const level of levels){ctx.beginPath();for(let j=1;j<nx;j++){let started=false;const y=j/nx;for(let i=1;i<nx;i++){const x=i/nx,d=potential(x,y,S);if(Math.abs(d-level)<.025){const px=x*W,py=y*H;if(!started){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py)}}}ctx.strokeStyle='rgba(220,235,248,'+(level===0?.22:.1)+')';ctx.stroke()}}
function integrate(x,y,S,steps=26,dt=.018){const pts=[];for(let k=0;k<steps;k++){if(x<0||x>1||y<0||y>1)break;pts.push([x,y]);const v1=velocity(x,y,S),mx=x+v1.vx*dt*.5,my=y+v1.vy*dt*.5,v2=velocity(mx,my,S);x+=v2.vx*dt;y+=v2.vy*dt}return pts}
function renderFlow(S){ctx.globalCompositeOperation='lighter';const sx=W<700?6:9,sy=Math.max(5,Math.round(sx*H/W));for(let j=1;j<sy;j++)for(let i=1;i<sx;i++){const seedX=(i+.23*Math.sin(j+S.phase))/sx,seedY=(j+.21*Math.cos(i-S.phase))/sy,pts=integrate(seedX,seedY,S,W<700?18:28,.55);if(pts.length<2)continue;ctx.beginPath();pts.forEach((p,k)=>k?ctx.lineTo(p[0]*W,p[1]*H):ctx.moveTo(p[0]*W,p[1]*H));ctx.strokeStyle='rgba(96,205,222,.16)';ctx.lineWidth=.75;ctx.stroke()}ctx.globalCompositeOperation='source-over'}
function renderTrajectory(S,now){const start=[(S.a[1]+.5)/12,(S.a[2]+.5)/12],pts=integrate(start[0],start[1],S,52,.72);if(pts.length>1){ctx.beginPath();pts.forEach((p,k)=>k?ctx.lineTo(p[0]*W,p[1]*H):ctx.moveTo(p[0]*W,p[1]*H));ctx.strokeStyle='rgba(101,216,148,.85)';ctx.lineWidth=2;ctx.stroke();const k=Math.floor((now/70)%pts.length),p=pts[k];trail.push([p[0],p[1],now]);if(trail.length>48)trail.shift();ctx.beginPath();ctx.arc(p[0]*W,p[1]*H,4.5,0,TAU);ctx.fillStyle='#f6fbff';ctx.fill()}const fx=start[0]*W,fy=start[1]*H;ctx.beginPath();ctx.arc(fx,fy,5.5,0,TAU);ctx.strokeStyle='rgba(230,189,78,.95)';ctx.lineWidth=1.5;ctx.stroke()}
function context(now,S){const center=velocity((S.a[1]+.5)/12,(S.a[2]+.5)/12,S),obs=q('#gmaAge')?.textContent||'unknown';return{source:{sha256:'${ATLAS_SOURCE.sha256}',rows:${ATLAS_SOURCE.rows},states:${ATLAS_SOURCE.atlasStates},edges:${ATLAS_SOURCE.signedNeighborEdges}},mode:S.mode,packet:S.P,focus:{index:S.focus,address:S.a,phase:S.a[0],neighbors:S.neighbors,antipode:S.anti,parent:Math.floor(S.focus/12)},calculus:{potential:center.f,gradient:[center.gx,center.gy],gradient_magnitude:Math.hypot(center.gx,center.gy),laplacian:center.lap,gaussian_curvature:center.curv,velocity:[center.vx,center.vy],speed:center.speed,solver:'finite_difference + RK2 integral curves'},time:{render_utc:new Date(now).toISOString(),observation_age:obs},evidence:{runtime:'OBSERVED_RUNTIME_WHEN_AVAILABLE',topology:'DERIVED_FRAMEWORK_MATH',calculus:'DERIVED_FRAMEWORK_MATH',trajectory:'SIMULATED_CONTINUATION',geometry:'USER_DEFINED_MODEL'}}}
function draw(now){const dt=now-lastFrame;lastFrame=now;ema=ema*.92+dt*.08;quality=ema<19?1:ema<28?.78:.58;const S=solveContext(Date.now());ctx.fillStyle='#010306';ctx.fillRect(0,0,W,H);renderField(S);renderContours(S);renderFlow(S);renderTrajectory(S,now);const C=context(Date.now(),S),g=C.calculus.gradient_magnitude;const f=q('#umrFocus');if(f)f.textContent=S.focus.toLocaleString()+' · ('+S.a.join(',')+')';q('#umrGrad').textContent=g.toFixed(3);q('#umrLap').textContent=C.calculus.laplacian.toFixed(3);q('#umrCurv').textContent=C.calculus.gaussian_curvature.toExponential(2);q('#umrFlow').textContent=C.calculus.speed.toFixed(3);q('#umrObservation').textContent=C.time.observation_age;q('#umrLive').textContent='LIVE SOLVE · '+Math.round(quality*100)+'%';window.OMEGA_ATLAS_CONTEXT=C;requestAnimationFrame(draw)}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error('HTTP '+r.status+' '+t.slice(0,180));return d}
const route=q('#umrRoute'),gen=q('#umrGenerate'),prompt=q('#umrPrompt'),result=q('#umrResult');if(route)route.onclick=async()=>{const text=prompt.value.trim();if(!text)return;route.disabled=true;result.textContent='Routing through solved field + atlas context…';try{const atlas_context=window.OMEGA_ATLAS_CONTEXT;lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context});result.textContent=JSON.stringify(lastRoute,null,2);gen.disabled=false}catch(e){result.textContent='Route unavailable: '+String(e)}route.disabled=false};if(gen)gen.onclick=async()=>{const text=prompt.value.trim();if(!text||!lastRoute)return;gen.disabled=true;result.textContent='Generating from admitted route + solved field…';try{const atlas_context=window.OMEGA_ATLAS_CONTEXT;const out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context});result.textContent=JSON.stringify(out,null,2)}catch(e){result.textContent='Generation unavailable: '+String(e)}gen.disabled=false};
// Bind the existing Assistant to the same atlas packet too, without creating a second AI authority.
const rb=q('#routeBtn');if(rb&&rb.dataset.umr!=='1'){rb.dataset.umr='1';const nr=rb.cloneNode(true);rb.replaceWith(nr);nr.onclick=async()=>{const text=q('#prompt').value.trim();if(!text)return;q('#routeGate').textContent='ROUTING FIELD…';q('#generateBtn').disabled=true;try{lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context:window.OMEGA_ATLAS_CONTEXT});q('#routeProof').textContent=JSON.stringify(lastRoute,null,2);q('#routeGate').textContent='FIELD ROUTE READY';q('#generateBtn').disabled=false}catch(e){q('#routeGate').textContent='ROUTE FAILED';q('#routeProof').textContent=String(e)}}}const gb2=q('#generateBtn');if(gb2&&gb2.dataset.umr!=='1'){gb2.dataset.umr='1';const ng=gb2.cloneNode(true);gb2.replaceWith(ng);ng.onclick=async()=>{if(!lastRoute)return;const text=q('#prompt').value.trim();ng.disabled=true;try{const out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context:window.OMEGA_ATLAS_CONTEXT});q('#assistantResult').innerHTML='<b>Generated from route + solved calculus field.</b><pre style="white-space:pre-wrap">'+JSON.stringify(out,null,2).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))+'</pre>'}catch(e){q('#assistantResult').textContent='Generation unavailable: '+String(e)}ng.disabled=false}}
addEventListener('resize',fit,{passive:true});fit();requestAnimationFrame(draw)})();</script>`;

export async function enhanceUnifiedMotionRelativity(response:Response):Promise<Response>{
  const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;
  let html=await response.text();if(!html.includes('omegaGovernedModeAtlasRuntime')||html.includes('omegaUnifiedMotionRelativityRuntime'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
  html=html.replace('</head>',css+'</head>').replace('</body>',js+'</body>');
  return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
}
