import { ATLAS_SOURCE } from "./native20736Atlas";

export const UNIFIED_MOTION_RELATIVITY_BOUNDARY = "R146 binds one visible atlas surface, native 20,736-state computation, governed mode selection and AI route/generation context to the same current packet. Motion is traversal through the supplied atlas topology plus render interpolation; UTC render time is not evidence time. Runtime observations, derived atlas relations, forecasts and USER_DEFINED_MODEL geometry remain explicitly distinguishable. 20,736 is a representational state atlas, not physical dimensions.";

const css=`<style id="omegaUnifiedMotionRelativityStyle">
#gmaInfoUnified{border:1px solid #294159;border-radius:10px;background:#07111b;margin-bottom:9px;padding:10px}.umrHead{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:8px}.umrHead b{font:850 9px ui-monospace,monospace;letter-spacing:.1em;color:#e6bd4e}.umrLive{font:750 8px ui-monospace,monospace;color:#42cb7c}.umrMetric{display:grid;grid-template-columns:1fr auto;gap:4px 8px;color:#7990a8;font:650 8px ui-monospace,monospace}.umrMetric strong{color:#eef6ff}.umrPrompt{width:100%;min-height:58px;resize:vertical;margin-top:9px;border:1px solid #294159;border-radius:8px;background:#03080e;color:#e8f1fb;padding:8px;font:650 9px/1.35 ui-monospace,monospace}.umrActions{display:flex;gap:6px;margin-top:6px}.umrActions button{flex:1;border:1px solid #31506b;border-radius:7px;background:#0b1926;color:#afc4d8;padding:7px;font:750 8px ui-monospace,monospace;cursor:pointer}.umrActions button.primary{border-color:#745f26;color:#f1d16b}.umrActions button:disabled{opacity:.4}.umrResult{margin-top:7px;max-height:150px;overflow:auto;white-space:pre-wrap;color:#91a8bd;font:600 8px/1.4 ui-monospace,monospace}.umrTruth{margin-top:8px;border-top:1px solid #1d3142;padding-top:7px;color:#6f879d;font:600 8px/1.35 ui-monospace,monospace}.umrTruth b{color:#d8e5f2}
</style>`;

const card=`<div id="gmaInfoUnified"><div class="umrHead"><b>VISUAL ⇄ COMPUTE ⇄ AI</b><span class="umrLive" id="umrLive">SYNCING</span></div><div class="umrMetric"><span>Atlas source</span><strong>${ATLAS_SOURCE.rows.toLocaleString()} rows</strong><span>Native states</span><strong>${ATLAS_SOURCE.atlasStates.toLocaleString()}</strong><span>Graph edges</span><strong>${ATLAS_SOURCE.signedNeighborEdges.toLocaleString()}</strong><span>Focus state</span><strong id="umrFocus">—</strong><span>Motion Δ</span><strong id="umrDelta">—</strong><span>Observation</span><strong id="umrObservation">—</strong></div><textarea class="umrPrompt" id="umrPrompt" placeholder="Ask OMEGA about the current field / state / mode…"></textarea><div class="umrActions"><button class="primary" id="umrRoute">ROUTE</button><button id="umrGenerate" disabled>GENERATE</button></div><div class="umrResult" id="umrResult">AI receives the same atlas focus, mode, packet, neighbors, antipode, phase and provenance shown by this field.</div><div class="umrTruth"><b>TRUTH BOUNDARY</b> · runtime observation ≠ atlas derivation ≠ simulation ≠ model projection.</div></div>`;

const js=`<script id="omegaUnifiedMotionRelativityRuntime">(()=>{
const root=document.querySelector('#gma');if(!root||document.documentElement.dataset.omegaUmr==='r146')return;document.documentElement.dataset.omegaUmr='r146';
const old=document.querySelector('#gmaCanvas');if(!old)return;const canvas=old.cloneNode(false);old.replaceWith(canvas);const ctx=canvas.getContext('2d',{alpha:false}),TAU=Math.PI*2,q=s=>document.querySelector(s),clamp=v=>Math.max(0,Math.min(1,Number(v)||0));
const info=q('.gmaInfo');if(info&&!q('#gmaInfoUnified'))info.insertAdjacentHTML('afterbegin',${JSON.stringify(card)});
const index=(d,p,r,l)=>(((d*12)+p)*12+r)*12+l;const addr=n=>{let l=n%12;n=Math.floor(n/12);let r=n%12;n=Math.floor(n/12);let p=n%12;n=Math.floor(n/12);return[n%12,p,r,l]};const antip=n=>{const a=addr(n);return index((a[0]+6)%12,(a[1]+6)%12,(a[2]+6)%12,(a[3]+6)%12)};const neigh=n=>{const a=addr(n),o=[];for(let ax=0;ax<4;ax++)for(const dir of[-1,1]){const b=a.slice();b[ax]=(b[ax]+dir+12)%12;o.push(index(b[0],b[1],b[2],b[3]))}return o};
let W=1,H=1,D=1,lastFocus=-1,lastRoute=null,trail=[];function fit(){const r=canvas.parentElement.getBoundingClientRect();D=Math.min(2.5,devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0)}
function num(id,f){const t=q(id)?.textContent||'';const n=Number(t.replace(/[^0-9+-.]/g,''));return Number.isFinite(n)?n:f}function activeMode(){return q('.gmaMode.active')?.dataset.gmaMode||'full-overall-canon'}function packet(){return{c:clamp(num('#gmaC',.72)),p:clamp(num('#gmaP',.68)),q:clamp(num('#gmaQ',.18)),b:clamp(num('#gmaB',.28)),dispatch:q('#gmaDispatch')?.textContent||'STAY'}}
function focusState(P,now){const phase=Math.floor((now/5000)%12),d=phase,p=Math.floor(P.c*11.999),r=Math.floor((1-P.q)*11.999),l=Math.floor(((P.p+(1-P.b))/2)*11.999);return index(d,p,r,l)}
function project(n,mode,t,P){const a=addr(n),u=(a[1]+(a[3]/12))/12,v=(a[2]+(a[0]/12))/12,ph=a[0]/12*TAU+t*.00005;let x=.5,y=.5;if(mode==='dewey-calculus'){const rr=.08+.39*u;x=.5+Math.cos(ph+v*TAU)*rr;y=.5+Math.sin(ph+v*TAU)*rr*.72}else if(mode==='relational-skin'){const ang=u*TAU,rr=.18+.25*v+.05*Math.sin(ang*8+t*.0007+a[3])*P.q;x=.5+Math.cos(ang)*rr;y=.5+Math.sin(ang)*rr*.76}else if(mode==='forecast'){x=.12+u*.76;y=.5+(v-.5)*(.18+.48*u)+Math.sin(ph+a[3])*.025}else if(mode==='full-sphere'||mode==='unified-recursion'){const ang=(u+v*.16)*TAU+t*.000025,rr=.08+.4*v;x=.5+Math.cos(ang)*rr;y=.5+Math.sin(ang)*rr*(.55+.24*Math.cos(u*TAU))}else if(mode==='unified-coherence'||mode==='no-nothing-truth'){const ring=a[0]+1,ang=(a[1]*12+a[2])/144*TAU+t*.000015,rr=.05+ring/12*.4;x=.5+Math.cos(ang)*rr;y=.5+Math.sin(ang)*rr*.78}else if(mode==='mode-188'||mode==='heavy-prune'){const sector=a[0]/12*TAU,rr=.1+.36*(a[1]*144+a[2]*12+a[3])/1727;x=.5+Math.cos(sector+(a[2]-5.5)*.008)*rr;y=.5+Math.sin(sector+(a[2]-5.5)*.008)*rr*.78}else{const ang=(a[0]*12+a[1])/144*TAU+t*.00002,rr=.07+.4*((a[2]*12+a[3])/143);x=.5+Math.cos(ang)*rr;y=.5+Math.sin(ang)*rr*.78}return[x*W,y*H]}
function palette(mode){if(mode==='heavy-prune'||mode==='high-father')return[79,143,255];if(mode==='alpha')return[155,108,255];if(mode==='crimson')return[239,98,95];if(mode==='deep-mother'||mode==='guidance-field')return[66,203,124];return[230,189,78]}
function context(now){const P=packet(),mode=activeMode(),focus=focusState(P,now),a=addr(focus),neighbors=neigh(focus),anti=antip(focus),obs=q('#gmaAge')?.textContent||'unknown';return{source:{sha256:'${ATLAS_SOURCE.sha256}',rows:${ATLAS_SOURCE.rows},states:${ATLAS_SOURCE.atlasStates},edges:${ATLAS_SOURCE.signedNeighborEdges}},mode,packet:P,focus:{index:focus,address:a,phase:a[0],neighbors,antipode:anti,parent:Math.floor(focus/12)},time:{render_utc:new Date(now).toISOString(),observation_age:obs},evidence:{runtime:'OBSERVED_RUNTIME_WHEN_AVAILABLE',topology:'DERIVED_FRAMEWORK_MATH',geometry:'USER_DEFINED_MODEL'}}}
function draw(now){const C=context(Date.now()),P=C.packet,mode=C.mode,focus=C.focus.index,rgb=palette(mode);ctx.fillStyle='#010306';ctx.fillRect(0,0,W,H);const grad=ctx.createRadialGradient(W*.5,H*.5,10,W*.5,H*.5,Math.max(W,H)*.65);grad.addColorStop(0,'#0b1723');grad.addColorStop(.5,'#03080e');grad.addColorStop(1,'#010204');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
ctx.globalCompositeOperation='lighter';const stride=W<700?24:12;for(let n=0;n<20736;n+=stride){const p=project(n,mode,now,P),a=addr(n),phaseAffinity=1-Math.abs(a[0]-C.focus.phase)/12,alpha=.025+.095*phaseAffinity;ctx.fillStyle='rgba('+rgb.join(',')+','+alpha.toFixed(3)+')';ctx.fillRect(p[0],p[1],1.1,1.1)}
ctx.globalCompositeOperation='source-over';const fp=project(focus,mode,now,P);const ns=C.focus.neighbors;for(let i=0;i<ns.length;i++){const np=project(ns[i],mode,now,P);ctx.beginPath();ctx.moveTo(fp[0],fp[1]);ctx.quadraticCurveTo((fp[0]+np[0])/2+(i-3.5)*4,(fp[1]+np[1])/2-(i-3.5)*3,np[0],np[1]);ctx.strokeStyle='rgba(84,214,223,.38)';ctx.lineWidth=1.1;ctx.stroke()}const ap=project(C.focus.antipode,mode,now,P);ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(fp[0],fp[1]);ctx.lineTo(ap[0],ap[1]);ctx.strokeStyle='rgba(155,108,255,.32)';ctx.stroke();ctx.setLineDash([]);
if(focus!==lastFocus){trail.push([fp[0],fp[1],Date.now()]);if(trail.length>36)trail.shift();lastFocus=focus}if(trail.length>1){ctx.beginPath();trail.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle='rgba(66,203,124,.48)';ctx.lineWidth=1.4;ctx.stroke()}ctx.beginPath();ctx.arc(fp[0],fp[1],7,0,TAU);ctx.fillStyle='rgba('+rgb.join(',')+',.92)';ctx.fill();ctx.beginPath();ctx.arc(ap[0],ap[1],5,0,TAU);ctx.strokeStyle='rgba(155,108,255,.8)';ctx.stroke();
const f=q('#umrFocus');if(f)f.textContent=focus.toLocaleString()+' · ('+C.focus.address.join(',')+')';const d=q('#umrDelta');if(d)d.textContent=lastFocus<0?'—':P.dispatch+' · phase '+String(C.focus.phase+1).padStart(2,'0');const o=q('#umrObservation');if(o)o.textContent=C.time.observation_age;const live=q('#umrLive');if(live)live.textContent='LIVE · '+mode.toUpperCase().slice(0,14);window.OMEGA_ATLAS_CONTEXT=C;requestAnimationFrame(draw)}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error('HTTP '+r.status+' '+t.slice(0,180));return d}
const route=q('#umrRoute'),gen=q('#umrGenerate'),prompt=q('#umrPrompt'),result=q('#umrResult');if(route)route.onclick=async()=>{const text=prompt.value.trim();if(!text)return;route.disabled=true;result.textContent='Routing through current atlas context…';try{const atlas_context=context(Date.now());lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context});result.textContent=JSON.stringify(lastRoute,null,2);gen.disabled=false}catch(e){result.textContent='Route unavailable: '+String(e)}route.disabled=false};if(gen)gen.onclick=async()=>{const text=prompt.value.trim();if(!text||!lastRoute)return;gen.disabled=true;result.textContent='Generating from admitted route + current atlas context…';try{const atlas_context=context(Date.now());const out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context});result.textContent=JSON.stringify(out,null,2)}catch(e){result.textContent='Generation unavailable: '+String(e)}gen.disabled=false};
// Bind the existing Assistant to the same atlas packet too, without creating a second AI authority.
const rb=q('#routeBtn'),gb=q('#generateBtn');if(rb&&rb.dataset.umr!=='1'){rb.dataset.umr='1';const nr=rb.cloneNode(true);rb.replaceWith(nr);nr.onclick=async()=>{const text=q('#prompt').value.trim();if(!text)return;q('#routeGate').textContent='ROUTING ATLAS…';q('#generateBtn').disabled=true;try{lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context:context(Date.now())});q('#routeProof').textContent=JSON.stringify(lastRoute,null,2);q('#routeGate').textContent='ATLAS ROUTE READY';q('#generateBtn').disabled=false}catch(e){q('#routeGate').textContent='ROUTE FAILED';q('#routeProof').textContent=String(e)}}}const gb2=q('#generateBtn');if(gb2&&gb2.dataset.umr!=='1'){gb2.dataset.umr='1';const ng=gb2.cloneNode(true);gb2.replaceWith(ng);ng.onclick=async()=>{if(!lastRoute)return;const text=q('#prompt').value.trim();ng.disabled=true;try{const out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context:context(Date.now())});q('#assistantResult').innerHTML='<b>Generated from route + atlas context.</b><pre style="white-space:pre-wrap">'+JSON.stringify(out,null,2).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))+'</pre>'}catch(e){q('#assistantResult').textContent='Generation unavailable: '+String(e)}ng.disabled=false}}
addEventListener('resize',fit,{passive:true});fit();requestAnimationFrame(draw)})();</script>`;

export async function enhanceUnifiedMotionRelativity(response:Response):Promise<Response>{
  const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;
  let html=await response.text();if(!html.includes('omegaGovernedModeAtlasRuntime')||html.includes('omegaUnifiedMotionRelativityRuntime'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
  html=html.replace('</head>',css+'</head>').replace('</body>',js+'</body>');
  return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
}
