import { ATLAS_SOURCE } from "./native20736Atlas";

export const UNIFIED_MOTION_RELATIVITY_BOUNDARY =
  "R167 binds the calculus field to the canonical Address20736 and state metrics when they are available. The compact 20,736-state topology supplies address, nearest-neighbor and antipode context; declared mode coefficients are USER_DEFINED_MODEL visualization weights, not measured physical constants. The canvas evaluates a scalar presentation potential, finite-difference gradient, Hessian/Laplacian curvature, derived vector flow, RK2 integral curves and advected trajectories. If canonical state is unavailable, the renderer uses a neutral unbound basis and labels it as such. Drag, wheel, pinch, keyboard and probe interaction change only the view/projection and never canonical state. UTC render time is not evidence time. Runtime state, DERIVED_FRAMEWORK_MATH, SIMULATED_CONTINUATION and USER_DEFINED_MODEL projection remain distinct. 20,736 and representational 12^n shells are software/model coordinates, not physical dimensions.";

export const UNIFIED_FIELD_CHANNEL = "VISUAL ⇄ COMPUTE ⇄ AI";

const css = `<style id="omegaUnifiedMotionRelativityStyle">
#gmaInfoUnified{border:1px solid #294159;border-radius:13px;background:linear-gradient(180deg,#07131e,#050b12);margin-bottom:9px;padding:11px}.umrHead{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:8px}.umrHead b{font:850 9px ui-monospace,monospace;letter-spacing:.1em;color:#e6c86b}.umrLive{font:750 8px ui-monospace,monospace;color:#42cb7c}.umrMetric{display:grid;grid-template-columns:1fr auto;gap:5px 8px;color:#7990a8;font:650 8px ui-monospace,monospace}.umrMetric strong{color:#eef6ff}.umrEquation{margin-top:8px;padding:8px;border:1px solid #1e3448;border-radius:9px;background:#03080e;color:#8fa7bc;font:600 8px/1.45 ui-monospace,monospace}.umrEquation b{color:#dfeaf5}.umrPrompt{width:100%;min-height:64px;resize:vertical;margin-top:9px;border:1px solid #294159;border-radius:9px;background:#03080e;color:#e8f1fb;padding:8px;font:650 9px/1.35 ui-monospace,monospace}.umrActions{display:flex;gap:6px;margin-top:6px}.umrActions button{flex:1;border:1px solid #31506b;border-radius:8px;background:#0b1926;color:#afc4d8;padding:8px;font:750 8px ui-monospace,monospace;cursor:pointer}.umrActions button.primary{border-color:#745f26;color:#f1d16b}.umrActions button:disabled{opacity:.4}.umrResult{margin-top:7px;max-height:150px;overflow:auto;white-space:pre-wrap;color:#91a8bd;font:600 8px/1.4 ui-monospace,monospace}.umrTruth{margin-top:8px;border-top:1px solid #1d3142;padding-top:7px;color:#6f879d;font:600 8px/1.35 ui-monospace,monospace}.umrTruth b{color:#d8e5f2}
</style>`;

const card = `<div id="gmaInfoUnified"><div class="umrHead"><b>CALCULUS FIELD</b><span class="umrLive" id="umrLive">WAITING FOR STATE</span></div><div class="umrMetric"><span>Source CSV identity</span><strong>${ATLAS_SOURCE.rows.toLocaleString()} rows</strong><span>Compact topology</span><strong>${ATLAS_SOURCE.atlasStates.toLocaleString()} states</strong><span>Probe / focus</span><strong id="umrFocus">—</strong><span>|∇Φ|</span><strong id="umrGrad">—</strong><span>∇²Φ</span><strong id="umrLap">—</strong><span>curvature K</span><strong id="umrCurv">—</strong><span>flow speed</span><strong id="umrFlow">—</strong><span>Canonical state age</span><strong id="umrObservation">—</strong></div><div class="umrEquation"><b>DERIVED SURFACE</b> · canonical state metrics + Address20736 + governed mode → presentation potential Φ(x,y,t) → finite-difference derivatives → derived flow → RK2 simulated trajectories. Address/neighbors/antipode provide topology context; mode coefficients are declared visualization weights, not empirical constants.</div><textarea class="umrPrompt" id="umrPrompt" placeholder="Ask OMEGA about the solved field, state, or mode…"></textarea><div class="umrActions"><button class="primary" id="umrRoute">ROUTE</button><button id="umrGenerate" disabled>GENERATE</button></div><div class="umrResult" id="umrResult">AI receives the same solved-field metrics, atlas focus, view probe, mode, packet and provenance shown by this surface.</div><div class="umrTruth"><b>TRUTH BOUNDARY</b> · runtime observation ≠ derived calculus ≠ simulated continuation ≠ model projection.</div></div>`;

const js = `<script id="omegaUnifiedMotionRelativityRuntime">(()=>{
const root=document.querySelector('#gma');if(!root)return;const old=document.querySelector('#gmaCanvas');if(!old)return;const canvas=old.cloneNode(true);old.replaceWith(canvas);document.documentElement.dataset.omegaUmr='r167-authoritative-state';
const ctx=canvas.getContext('2d',{alpha:false}),fieldLayer=document.createElement('canvas'),fieldCtx=fieldLayer.getContext('2d',{alpha:false}),TAU=Math.PI*2,q=s=>document.querySelector(s),clamp=v=>Math.max(0,Math.min(1,Number(v)||0)),mix=(a,b,t)=>a.map((v,i)=>Math.round(v+(b[i]-v)*t));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const info=q('.gmaInfo');if(info&&!q('#gmaInfoUnified'))info.insertAdjacentHTML('afterbegin',${JSON.stringify(card)});
const index=(d,p,r,l)=>(((d*12)+p)*12+r)*12+l;const addr=n=>{let l=n%12;n=Math.floor(n/12);let r=n%12;n=Math.floor(n/12);let p=n%12;n=Math.floor(n/12);return[n%12,p,r,l]};const antip=n=>{const a=addr(n);return index((a[0]+6)%12,(a[1]+6)%12,(a[2]+6)%12,(a[3]+6)%12)};const neigh=n=>{const a=addr(n),o=[];for(let ax=0;ax<4;ax++)for(const dir of[-1,1]){const b=a.slice();b[ax]=(b[ax]+dir+12)%12;o.push(index(b[0],b[1],b[2],b[3]))}return o};
let W=1,H=1,D=1,lastRoute=null,quality=1,ema=16,lastFrame=performance.now(),lastHud=0,fieldStamp='',fieldFrame=-1,pinch=null;const pointers=new Map(),particles=[];const state={viewX:.5,viewY:.5,zoom:1,probeX:.5,probeY:.5,interacted:false,dragging:false,paused:false,frame:0,simTime:Date.now(),dirty:true,lastPointer:null,layers:{field:true,contours:true,flow:true,particles:true,trajectory:true}};
function setText(id,value){const e=q(id);if(e)e.textContent=value}function activeMode(){return q('.gmaMode.active')?.dataset.gmaMode||'full-overall-canon'}function packet(){const p=window.OMEGA_CANONICAL_PACKET;if(!p)return null;const values=[p.c,p.p,p.q,p.b].map(Number);if(values.some(v=>!Number.isFinite(v)))return null;return{c:clamp(values[0]),p:clamp(values[1]),q:clamp(values[2]),b:clamp(values[3]),dispatch:String(p.dispatch||'UNKNOWN'),address:Array.isArray(p.address)?p.address.map(Number):null,evidence_class:String(p.evidence_class||'UNKNOWN'),digest:String(p.digest||''),source_id:String(p.source_id||'runtime'),observed_at:Number(p.observed_at)||0}}
function fit(){const r=canvas.parentElement.getBoundingClientRect();D=Math.min(2.25,devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);ctx.setTransform(D,0,0,D,0,0);state.dirty=true;seedParticles(true)}
function worldFromScreen(sx,sy){return[state.viewX+(sx/W-.5)/state.zoom,state.viewY+(sy/H-.5)/state.zoom]}function screenFromWorld(x,y){return[(x-state.viewX)*state.zoom+.5,(y-state.viewY)*state.zoom+.5]}
function focusState(P,now){if(P?.address&&P.address.length===4&&P.address.every(v=>Number.isInteger(v)&&v>=1&&v<=12))return index(P.address[0]-1,P.address[1]-1,P.address[2]-1,P.address[3]-1);const phase=Math.floor((now/5000)%12);return index(0,phase,5,5)}
function modeCoefficients(mode){const table={
'full-overall-canon':[1.16,1.08,.92,1.02,1.12],'dewey-calculus':[1.38,1.22,.82,1.12,1.34],'relational-skin':[.9,1.36,1.24,.82,1.08],'forecast':[.82,1.52,.7,1.2,1.38],'heavy-prune':[.7,.76,1.56,1.42,.72],'mode-188':[1.2,.9,1.44,1.16,.94],'unified-coherence':[1.46,1.14,.7,.86,1.3],'unified-recursion':[1.24,1.12,1,1.4,1.14],'full-sphere':[1.12,1.02,.96,1.34,1.28],'guidance-field':[1.06,1.42,.78,1.1,1.46],'deep-mother':[1.34,1.28,.76,.82,1.12],'high-father':[.88,.82,1.28,1.48,.92],'alpha':[.92,1.5,.7,.88,1.34],'crimson':[1.24,1.02,1.16,1.28,.94],'no-nothing-truth':[1.32,.88,1.4,1.06,1.18]};return table[mode]||table['full-overall-canon']}
function solveContext(now){const canonical=packet(),P=canonical||{c:.5,p:.5,q:.5,b:.5,dispatch:'UNBOUND'},mode=activeMode(),focus=focusState(canonical,now),a=addr(focus),neighbors=neigh(focus),anti=antip(focus),na=neighbors.map(addr),aa=addr(anti),m=modeCoefficients(mode),phase=a[1]/12*TAU+(now%60000)/60000*TAU;return{P,canonical,stateBound:Boolean(canonical),mode,focus,a,neighbors,na,anti,aa,m,phase,probe:[state.probeX,state.probeY]}}
function potential(x,y,S){const P=S.P,a=S.a,m=S.m,ph=S.phase,fx=(a[1]+.5)/12,fy=(a[2]+.5)/12,ax=(S.aa[1]+.5)/12,ay=(S.aa[2]+.5)/12,dx=x-fx,dy=y-fy,da=x-ax,db=y-ay,sig=.045+.11*(1-P.b),focus=Math.exp(-(dx*dx+dy*dy)/sig),anti=Math.exp(-(da*da+db*db)/(.07+.08*P.q)),k1=2+(a[3]%5),k2=3+(a[0]%4),wave=Math.sin(TAU*(k1*x+k2*y)+ph)*Math.cos(TAU*((a[0]+1)*y/4-(a[3]+1)*x/5)-ph*.63),fold=Math.sin(TAU*(x-y)*m[3]+ph*.7)*Math.sin(TAU*(x+y)*m[4]-ph*.31),radial=Math.sin(TAU*Math.hypot(x-.5,y-.5)*(3+m[0]*2)-ph*.45),boundary=Math.cos(TAU*x*(1+a[1]/12))*Math.cos(TAU*y*(1+a[2]/12)),px=x-S.probe[0],py=y-S.probe[1],probe=state.interacted?Math.exp(-(px*px+py*py)/(.025+.035/state.zoom))*Math.sin(ph+Math.hypot(px,py)*42):0;return m[0]*P.c*focus-m[2]*P.q*.72*anti+m[1]*P.p*.25*wave+m[3]*(1-P.b)*.17*fold+m[4]*.11*radial+.08*boundary+.18*probe}
function differential(x,y,S){const h=.0032,state0=potential(x,y,S),xp=potential(x+h,y,S),xm=potential(x-h,y,S),yp=potential(x,y+h,S),ym=potential(x,y-h,S),pp=potential(x+h,y+h,S),pm=potential(x+h,y-h,S),mp=potential(x-h,y+h,S),mm=potential(x-h,y-h,S);const gx=(xp-xm)/(2*h),gy=(yp-ym)/(2*h),fxx=(xp-2*state0+xm)/(h*h),fyy=(yp-2*state0+ym)/(h*h),fxy=(pp-pm-mp+mm)/(4*h*h),lap=fxx+fyy,curv=(fxx*fyy-fxy*fxy)/Math.pow(1+gx*gx+gy*gy,2);return{f:state0,gx,gy,lap,curv}}
function velocity(x,y,S){const d=differential(x,y,S),P=S.P,adv=.15+.42*P.p,rot=.08+.5*P.q,damp=.3+.7*(1-P.b),phaseDrift=.045*Math.sin(S.phase+TAU*y);let vx=(adv*d.gx-rot*d.gy)*.015*damp+phaseDrift,vy=(adv*d.gy+rot*d.gx)*.015*damp+.045*Math.cos(S.phase+TAU*x);const speed=Math.hypot(vx,vy),cap=.26;if(speed>cap){vx*=cap/speed;vy*=cap/speed}return{...d,vx,vy,speed:Math.hypot(vx,vy)}}
function palette(mode,value,energy){const dark=[2,7,13],cold=mode==='relational-skin'?[50,78,112]:mode==='forecast'?[25,78,76]:mode==='heavy-prune'?[22,58,96]:[20,58,82],light=mode==='forecast'?[105,214,164]:mode==='crimson'?[226,123,103]:mode==='alpha'?[142,154,218]:mode==='dewey-calculus'?[230,199,103]:[104,188,211],t=clamp(.5+value*.42),base=t<.5?mix(dark,cold,t*2):mix(cold,light,(t-.5)*2),lift=.48+.52*clamp(energy);return base.map(v=>Math.round(v*lift))}
function paintField(S){const stamp=S.mode+'|'+S.focus+'|'+state.zoom.toFixed(2)+'|'+state.viewX.toFixed(3)+'|'+state.viewY.toFixed(3)+'|'+Math.floor(S.phase*8);if(!state.dirty&&fieldFrame>=0&&state.frame-fieldFrame<3&&stamp===fieldStamp){ctx.drawImage(fieldLayer,0,0,W,H);return}const cols=Math.max(72,Math.min(144,Math.round((W<700?86:126)*quality))),rows=Math.max(48,Math.round(cols*H/W));if(fieldLayer.width!==cols||fieldLayer.height!==rows){fieldLayer.width=cols;fieldLayer.height=rows}const image=fieldCtx.createImageData(cols,rows),data=image.data;for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const world=worldFromScreen((i+.5)/cols*W,(j+.5)/rows*H),f=potential(world[0],world[1],S),energy=.5+.5*Math.sin(f*2.7+S.phase*.35),rgb=palette(S.mode,f,energy),o=(j*cols+i)*4;data[o]=rgb[0];data[o+1]=rgb[1];data[o+2]=rgb[2];data[o+3]=255}fieldCtx.putImageData(image,0,0);fieldFrame=state.frame;fieldStamp=stamp;state.dirty=false;ctx.imageSmoothingEnabled=true;ctx.drawImage(fieldLayer,0,0,W,H)}
function renderContours(S){const center=state.interacted?S.probe:[(S.a[1]+.5)/12,(S.a[2]+.5)/12],R=.055/state.zoom;ctx.save();ctx.globalCompositeOperation='screen';for(let ring=1;ring<=9;ring++){ctx.beginPath();let visible=false;for(let k=0;k<=112;k++){const a=k/112*TAU,base=R*ring,wx=center[0]+Math.cos(a)*base,wy=center[1]+Math.sin(a)*base,warp=1+.045*Math.sin(a*12+S.phase+ring)+.025*potential(wx,wy,S),p=screenFromWorld(center[0]+Math.cos(a)*base*warp,center[1]+Math.sin(a)*base*warp),x=p[0]*W,y=p[1]*H;if(p[0]>-.2&&p[0]<1.2&&p[1]>-.2&&p[1]<1.2)visible=true;k?ctx.lineTo(x,y):ctx.moveTo(x,y)}if(visible){ctx.strokeStyle='rgba(185,220,235,'+(.035+ring*.012)+')';ctx.lineWidth=.55+(ring%3===0?.45:0);ctx.stroke()}}ctx.restore()}
function integrate(x,y,S,steps=28,dt=.16){const pts=[];for(let k=0;k<steps;k++){pts.push([x,y]);const v1=velocity(x,y,S),mx=x+v1.vx*dt*.5,my=y+v1.vy*dt*.5,v2=velocity(mx,my,S);x+=v2.vx*dt;y+=v2.vy*dt;if(Math.abs(x-state.viewX)>1.1/state.zoom||Math.abs(y-state.viewY)>1.1/state.zoom)break}return pts}
function renderFlow(S){ctx.save();ctx.globalCompositeOperation='lighter';const sx=W<700?5:8,sy=Math.max(4,Math.round(sx*H/W));for(let j=1;j<sy;j++)for(let i=1;i<sx;i++){const seed=worldFromScreen((i+.18*Math.sin(j+S.phase))/sx*W,(j+.16*Math.cos(i-S.phase))/sy*H),pts=integrate(seed[0],seed[1],S,W<700?18:24,.19);if(pts.length<2)continue;ctx.beginPath();pts.forEach((p,k)=>{const s=screenFromWorld(p[0],p[1]),x=s[0]*W,y=s[1]*H;k?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='rgba(116,205,222,.13)';ctx.lineWidth=.7;ctx.stroke()}ctx.restore()}
function hash(n){const x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x)}function seedParticle(p,i){const span=1.16/state.zoom;p.x=state.viewX+(hash(i*3.17+state.frame*.017)-.5)*span;p.y=state.viewY+(hash(i*7.91+state.frame*.011)-.5)*span;p.px=p.x;p.py=p.y;p.age=0;p.life=1.8+hash(i*11.3)*4.2;p.tone=hash(i*19.7)}function seedParticles(force=false){const target=Math.round((W<700?220:620)*quality*(reduced?.45:1));while(particles.length<target)particles.push({x:0,y:0,px:0,py:0,age:0,life:1,tone:0});if(particles.length>target)particles.length=target;if(force)particles.forEach(seedParticle)}
function renderParticles(S,dt){seedParticles();const step=Math.min(.042,dt/1000)*(reduced?.28:1);ctx.save();ctx.globalCompositeOperation='lighter';for(let i=0;i<particles.length;i++){const p=particles[i];p.px=p.x;p.py=p.y;if(!state.paused){const v=velocity(p.x,p.y,S);p.x+=v.vx*step*.95;p.y+=v.vy*step*.95;p.age+=step}const edge=Math.abs(p.x-state.viewX)>.62/state.zoom||Math.abs(p.y-state.viewY)>.62/state.zoom;if(edge||p.age>p.life){seedParticle(p,i);continue}const a=screenFromWorld(p.px,p.py),b=screenFromWorld(p.x,p.y),alpha=.12+.28*(1-p.age/p.life),rgb=p.tone>.82?[229,200,103]:p.tone>.58?[104,210,160]:[113,196,222];ctx.beginPath();ctx.moveTo(a[0]*W,a[1]*H);ctx.lineTo(b[0]*W,b[1]*H);ctx.strokeStyle='rgba('+rgb.join(',')+','+alpha.toFixed(3)+')';ctx.lineWidth=.65+(p.tone>.82?.75:0);ctx.stroke();ctx.fillStyle='rgba('+rgb.join(',')+','+Math.min(.85,alpha*1.5).toFixed(3)+')';ctx.fillRect(b[0]*W,b[1]*H,p.tone>.82?1.8:1.15,p.tone>.82?1.8:1.15)}ctx.restore()}
function renderTrajectory(S,now){const start=state.interacted?S.probe:[(S.a[1]+.5)/12,(S.a[2]+.5)/12],pts=integrate(start[0],start[1],S,58,.2);if(pts.length>1){ctx.save();ctx.globalCompositeOperation='lighter';ctx.beginPath();pts.forEach((p,k)=>{const s=screenFromWorld(p[0],p[1]),x=s[0]*W,y=s[1]*H;k?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='rgba(108,224,164,.72)';ctx.lineWidth=1.8;ctx.stroke();const k=Math.floor((now/58)%pts.length),p=screenFromWorld(pts[k][0],pts[k][1]);ctx.beginPath();ctx.arc(p[0]*W,p[1]*H,3.8,0,TAU);ctx.fillStyle='#f7fbff';ctx.shadowBlur=14;ctx.shadowColor='#8ee4b5';ctx.fill();ctx.restore()}const s=screenFromWorld(start[0],start[1]);ctx.beginPath();ctx.arc(s[0]*W,s[1]*H,7,0,TAU);ctx.strokeStyle='rgba(232,203,111,.9)';ctx.lineWidth=1.4;ctx.stroke();ctx.beginPath();ctx.arc(s[0]*W,s[1]*H,2.2,0,TAU);ctx.fillStyle='#f1d36e';ctx.fill()}
function context(now,S){const sample=state.interacted?S.probe:[(S.a[1]+.5)/12,(S.a[2]+.5)/12],center=velocity(sample[0],sample[1],S),observedAt=Number(document.documentElement.dataset.omegaStateObservedAt||S.canonical?.observed_at||0),age=observedAt?Math.max(0,Math.round((Date.now()-observedAt)/1000))+'s':'unavailable';return{source:{sha256:'${ATLAS_SOURCE.sha256}',rows:${ATLAS_SOURCE.rows},states:${ATLAS_SOURCE.atlasStates},edges:${ATLAS_SOURCE.signedNeighborEdges},axis_order:['domain','phase','regulation','layer']},state_bound:S.stateBound,canonical:S.canonical?{digest:S.canonical.digest,evidence_class:S.canonical.evidence_class,source_id:S.canonical.source_id,address:S.canonical.address,dispatch:S.canonical.dispatch}:null,mode:S.mode,packet:S.stateBound?S.P:null,presentation_basis:S.stateBound?null:S.P,focus:{index:S.focus,address:S.a,domain:S.a[0],phase:S.a[1],regulation:S.a[2],layer:S.a[3],neighbors:S.neighbors,antipode:S.anti,parent:Math.floor(S.focus/12)},view:{center:[state.viewX,state.viewY],zoom:state.zoom,probe:sample,user_interacted:state.interacted,layers:{...state.layers}},calculus:{potential:center.f,gradient:[center.gx,center.gy],gradient_magnitude:Math.hypot(center.gx,center.gy),laplacian:center.lap,gaussian_curvature:center.curv,velocity:[center.vx,center.vy],speed:center.speed,solver:'finite_difference + RK2 integral curves'},time:{render_utc:new Date(now).toISOString(),canonical_state_age:age},evidence:{runtime_state:S.stateBound?'CANONICAL_RUNTIME_STATE':'UNBOUND_PRESENTATION_BASIS',topology:'DERIVED_FRAMEWORK_MATH',mode_weights:'USER_DEFINED_MODEL',calculus:'DERIVED_FRAMEWORK_MATH',trajectory:'SIMULATED_CONTINUATION',geometry:'USER_DEFINED_MODEL'}}}
function updateHud(realNow,S){const C=context(realNow,S),g=C.calculus.gradient_magnitude,layerCount=Object.values(state.layers).filter(Boolean).length,fps=Math.round(1000/Math.max(1,ema));setText('#umrFocus',(S.stateBound?'state ':'unbound ')+S.focus.toLocaleString()+' · probe ('+C.view.probe.map(v=>v.toFixed(3)).join(', ')+')');setText('#umrGrad',g.toFixed(3));setText('#umrLap',C.calculus.laplacian.toFixed(3));setText('#umrCurv',C.calculus.gaussian_curvature.toExponential(2));setText('#umrFlow',C.calculus.speed.toFixed(3));setText('#umrObservation',C.time.canonical_state_age);setText('#umrLive',S.stateBound?((state.paused?'PAUSED':'BOUND')+' · '+fps+' FPS'):'UNBOUND · DISPLAY ONLY');setText('#gmaUtc',new Date(realNow).toISOString().slice(11,23)+'Z');setText('#gmaPhase',S.stateBound?String(S.a[1]+1).padStart(2,'0')+'/12':'—');setText('#gmaMotion',S.stateBound?(state.paused?'PAUSED':fps+' FPS'):'DISPLAY ONLY');setText('#gmaZoom',state.zoom.toFixed(2)+'×');setText('#gmaLayers',layerCount+'/5');window.OMEGA_ATLAS_CONTEXT=C;const h=document.documentElement;h.dataset.omegaFieldFrame=String(state.frame);h.dataset.omegaFieldMotion=S.stateBound?(state.paused?'paused':'live'):'unbound';h.dataset.omegaFieldQuality=quality.toFixed(2);if(S.stateBound)h.dataset.omegaPhase=String(S.a[1]+1);else delete h.dataset.omegaPhase;h.dataset.omegaRelativity='20736';h.dataset.omegaFieldStateBound=S.stateBound?'true':'false'}
function draw(now){const dt=Math.min(80,Math.max(1,now-lastFrame));lastFrame=now;ema=ema*.92+dt*.08;quality=ema<20?1:ema<30?.78:.58;if(!state.paused)state.simTime+=dt;const S=solveContext(state.simTime);ctx.fillStyle='#010308';ctx.fillRect(0,0,W,H);if(state.layers.field)paintField(S);if(state.layers.contours)renderContours(S);if(state.layers.flow)renderFlow(S);if(state.layers.particles)renderParticles(S,dt);if(state.layers.trajectory)renderTrajectory(S,now);if(now-lastHud>120){updateHud(Date.now(),S);lastHud=now}state.frame++;requestAnimationFrame(draw)}
function local(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function useGesture(){state.interacted=true;q('#gmaGesture')?.classList.add('used')}
function resetView(){state.viewX=.5;state.viewY=.5;state.zoom=1;state.probeX=.5;state.probeY=.5;state.interacted=false;state.dirty=true;seedParticles(true);q('#gmaGesture')?.classList.remove('used')}
canvas.addEventListener('pointerdown',e=>{const p=local(e),world=worldFromScreen(p.x,p.y);pointers.set(e.pointerId,p);state.probeX=world[0];state.probeY=world[1];state.lastPointer=p;state.dragging=true;canvas.classList.add('is-dragging');try{canvas.setPointerCapture(e.pointerId)}catch{}if(pointers.size===2){const pts=[...pointers.values()],dx=pts[1].x-pts[0].x,dy=pts[1].y-pts[0].y,mid={x:(pts[0].x+pts[1].x)/2,y:(pts[0].y+pts[1].y)/2};pinch={distance:Math.hypot(dx,dy),zoom:state.zoom,world:worldFromScreen(mid.x,mid.y),mid}}useGesture();state.dirty=true});
canvas.addEventListener('pointermove',e=>{const p=local(e),old=pointers.get(e.pointerId);if(!old){if(e.pointerType==='mouse'){const w=worldFromScreen(p.x,p.y);state.probeX=w[0];state.probeY=w[1]}return}pointers.set(e.pointerId,p);if(pointers.size>=2&&pinch){const pts=[...pointers.values()].slice(0,2),distance=Math.hypot(pts[1].x-pts[0].x,pts[1].y-pts[0].y),mid={x:(pts[0].x+pts[1].x)/2,y:(pts[0].y+pts[1].y)/2};state.zoom=Math.max(.5,Math.min(6,pinch.zoom*Math.max(.25,distance/Math.max(1,pinch.distance))));const after=worldFromScreen(mid.x,mid.y);state.viewX+=pinch.world[0]-after[0];state.viewY+=pinch.world[1]-after[1]}else if(state.dragging&&state.lastPointer){state.viewX-=(p.x-state.lastPointer.x)/W/state.zoom;state.viewY-=(p.y-state.lastPointer.y)/H/state.zoom;state.lastPointer=p}const w=worldFromScreen(p.x,p.y);state.probeX=w[0];state.probeY=w[1];state.dirty=true});
function endPointer(e){pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(!pointers.size){state.dragging=false;state.lastPointer=null;canvas.classList.remove('is-dragging')}else state.lastPointer=[...pointers.values()][0]}canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=local(e),before=worldFromScreen(p.x,p.y),next=Math.max(.5,Math.min(6,state.zoom*Math.exp(-e.deltaY*.0013)));state.zoom=next;const after=worldFromScreen(p.x,p.y);state.viewX+=before[0]-after[0];state.viewY+=before[1]-after[1];const probe=worldFromScreen(p.x,p.y);state.probeX=probe[0];state.probeY=probe[1];state.dirty=true;useGesture()},{passive:false});canvas.addEventListener('dblclick',resetView);
canvas.tabIndex=0;canvas.addEventListener('keydown',e=>{const step=.06/state.zoom;if(e.key==='ArrowLeft')state.viewX-=step;else if(e.key==='ArrowRight')state.viewX+=step;else if(e.key==='ArrowUp')state.viewY-=step;else if(e.key==='ArrowDown')state.viewY+=step;else if(e.key==='+'||e.key==='=')state.zoom=Math.min(6,state.zoom*1.15);else if(e.key==='-'||e.key==='_')state.zoom=Math.max(.5,state.zoom/1.15);else if(e.key.toLowerCase()==='r')resetView();else return;e.preventDefault();state.dirty=true;useGesture()});
document.addEventListener('omega-field-reset',resetView);document.addEventListener('omega-field-pause',e=>{state.paused=Boolean(e.detail?.paused)});document.addEventListener('omega-field-mode',()=>{state.dirty=true;seedParticles(true)});document.addEventListener('omega-field-layer',e=>{const layer=String(e.detail?.layer||''),enabled=Boolean(e.detail?.enabled);if(layer in state.layers){state.layers[layer]=enabled;state.dirty=true;if(layer==='particles'&&enabled)seedParticles(true)}document.documentElement.dataset.omegaFieldLayers=Object.entries(state.layers).filter(([,v])=>v).map(([k])=>k).join(',')});
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error('HTTP '+r.status+' '+t.slice(0,180));return d}
const route=q('#umrRoute'),gen=q('#umrGenerate'),prompt=q('#umrPrompt'),result=q('#umrResult');if(route)route.onclick=async()=>{const text=prompt.value.trim();if(!text)return;route.disabled=true;result.textContent='Routing through solved field + atlas context…';try{const atlas_context=window.OMEGA_ATLAS_CONTEXT;lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context});result.textContent=JSON.stringify(lastRoute,null,2);gen.disabled=false}catch(e){result.textContent='Route unavailable: '+String(e)}route.disabled=false};if(gen)gen.onclick=async()=>{const text=prompt.value.trim();if(!text||!lastRoute)return;gen.disabled=true;result.textContent='Generating from admitted route + solved field…';try{const atlas_context=window.OMEGA_ATLAS_CONTEXT,out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context});result.textContent=JSON.stringify(out,null,2)}catch(e){result.textContent='Generation unavailable: '+String(e)}gen.disabled=false};
const rb=q('#routeBtn');if(rb&&rb.dataset.umr!=='1'){rb.dataset.umr='1';const nr=rb.cloneNode(true);rb.replaceWith(nr);nr.onclick=async()=>{const text=q('#prompt').value.trim();if(!text)return;q('#routeGate').textContent='ROUTING FIELD…';q('#generateBtn').disabled=true;try{lastRoute=await api('/api/route-preview',{message:text,prompt:text,atlas_context:window.OMEGA_ATLAS_CONTEXT});q('#routeProof').textContent=JSON.stringify(lastRoute,null,2);q('#routeGate').textContent='FIELD ROUTE READY';q('#generateBtn').disabled=false}catch(e){q('#routeGate').textContent='ROUTE FAILED';q('#routeProof').textContent=String(e)}}}const gb2=q('#generateBtn');if(gb2&&gb2.dataset.umr!=='1'){gb2.dataset.umr='1';const ng=gb2.cloneNode(true);gb2.replaceWith(ng);ng.onclick=async()=>{if(!lastRoute)return;const text=q('#prompt').value.trim();ng.disabled=true;try{const out=await api('/api/chat',{message:text,prompt:text,route_preview:lastRoute,atlas_context:window.OMEGA_ATLAS_CONTEXT});q('#assistantResult').innerHTML='<b>Generated from route + solved calculus field.</b><pre style="white-space:pre-wrap">'+JSON.stringify(out,null,2).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))+'</pre>'}catch(e){q('#assistantResult').textContent='Generation unavailable: '+String(e)}ng.disabled=false}}
addEventListener('resize',fit,{passive:true});new ResizeObserver(fit).observe(canvas.parentElement);fit();seedParticles(true);requestAnimationFrame(draw);
})();</script>`;

export async function enhanceUnifiedMotionRelativity(response: Response): Promise<Response> {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  let html = await response.text();
  if (!html.includes("omegaGovernedModeAtlasRuntime") || html.includes("omegaUnifiedMotionRelativityRuntime")) {
    return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
  }
  html = html.replace("</head>", css + "</head>").replace("</body>", js + "</body>");
  return new Response(html, { status: response.status, statusText: response.statusText, headers: response.headers });
}
