export const VISUAL_RUNTIME_INTEGRITY_BOUNDARY = "R141 observes the delivered visual-computation channel only. It verifies that UTC, phase, relativity-depth and individual-skin markers continue changing in the browser; it does not mutate canonical state, create a new state authority, promote animation to evidence, or claim physical 20,736D/61.9-billion-pixel hardware.";

const css=`<style id="omegaVisualRuntimeIntegrityStyle">
.orsfIntegrity{position:absolute;z-index:12;left:16px;top:82px;display:flex;gap:6px;align-items:center;pointer-events:none}.orsfIntegrityDot{width:7px;height:7px;border-radius:50%;background:#5f7792;box-shadow:0 0 10px rgba(95,119,146,.45)}.orsfIntegrity[data-state="live"] .orsfIntegrityDot{background:#42cb7c;box-shadow:0 0 16px rgba(66,203,124,.8)}.orsfIntegrity[data-state="degraded"] .orsfIntegrityDot{background:#ef625f;box-shadow:0 0 16px rgba(239,98,95,.8)}.orsfIntegrityText{font:750 8px/1 ui-monospace,monospace;letter-spacing:.08em;color:#7890aa}.orsfIntegrity[data-state="live"] .orsfIntegrityText{color:#8ad9ae}.orsfIntegrity[data-state="degraded"] .orsfIntegrityText{color:#ff9a97}@media(max-width:760px){.orsfIntegrity{left:10px;top:76px}}
</style>`;
const markup=`<div class="orsfIntegrity" id="orsfIntegrity" data-state="starting"><span class="orsfIntegrityDot"></span><span class="orsfIntegrityText" id="orsfIntegrityText">VISUAL STARTING</span></div>`;
const js=`<script id="omegaVisualRuntimeIntegrityRuntime">(()=>{const root=document.querySelector('#omegaRootSovereignField');if(!root||document.querySelector('#orsfIntegrity'))return;root.insertAdjacentHTML('beforeend',${JSON.stringify(markup)});const box=document.querySelector('#orsfIntegrity'),text=document.querySelector('#orsfIntegrityText');let lastUtc='',lastPhase='',lastDepth='',lastSkin='',lastChange=performance.now(),samples=0;function tick(){const h=document.documentElement,utc=h.dataset.omegaUtcMs||'',phase=h.dataset.omegaPhase||'',depth=h.dataset.omegaRelativity||'',skin=h.dataset.omegaIndividualSkin||'';const changed=utc!==lastUtc||phase!==lastPhase||depth!==lastDepth||skin!==lastSkin;if(changed){lastUtc=utc;lastPhase=phase;lastDepth=depth;lastSkin=skin;lastChange=performance.now();samples++}const age=performance.now()-lastChange,ready=Boolean(utc&&phase&&depth&&skin),live=ready&&age<2200;if(box)box.dataset.state=live?'live':ready?'degraded':'starting';if(text)text.textContent=live?'VISUAL LIVE · '+samples:'degraded'===box?.dataset.state?'VISUAL DEGRADED':'VISUAL STARTING';h.dataset.omegaVisualIntegrity=live?'live':ready?'degraded':'starting'}setInterval(tick,500);tick()})();</script>`;

export async function enhanceVisualRuntimeIntegrity(response:Response):Promise<Response>{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('omegaRootSovereignField')||html.includes('omegaVisualRuntimeIntegrityStyle'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});html=html.replace('</head>',css+'</head>').replace('</body>',js+'</body>');return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});}
