import { AnyObj, DurableBinding, SwarmEnv, AUTONOMIC_REVISION, CONTINUITY_LAW, DOMAIN_PREFERENCE, MODE_COUNT, PROJECTIONS, SWARM_CELL_COUNT, SWARM_DOMAIN_ROLES, SWARM_LANE_COUNT, SWARM_SOURCE_COMMIT, TRUTH_BOUNDARY, c01, capabilityProfile, cellIndex, clip, decodeCell, evidence, jsonResponse, laneIndex, merkle, num, publicMission, schedule, sha, stableSeed } from "./swarmCoreR169";

function normalizeMetrics(m: AnyObj = {}): AnyObj { return { continuity: c01(m.continuity ?? 0.5), plasticity: c01(m.plasticity ?? 0.5), contradiction: c01(m.contradiction ?? 0.2), burden: c01(m.burden ?? 0.3), evidence: c01(m.evidence ?? 0.4), uncertainty: c01(m.uncertainty ?? 0.5), scar: c01(m.scar ?? 0.2) }; }
function decide(m: AnyObj): string { const d = Math.max(1e-9, m.burden + m.contradiction + m.burden * m.contradiction), score = m.continuity / d; return score >= 1.15 ? "STAY" : score >= 0.72 ? "TURN" : "ESCALATE"; }
function inferProjection(text = ""): string { const s = String(text); if (/earth|satellite|terrain|weather|map|ground/i.test(s)) return "EARTH"; if (/optical|light|rcwa|fdtd|etch|metasurface/i.test(s)) return "OPTICAL"; if (/build|code|repair|software|deploy|repository|github/i.test(s)) return "BUILD"; if (/proof|evidence|verify|audit|receipt|lineage/i.test(s)) return "PROOF"; if (/forecast|future|predict|trajectory/i.test(s)) return "FORECAST"; if (/relative|inverse|outverse|observer/i.test(s)) return "RELATIVITY"; if (/atom|matter|material|molecule|field/i.test(s)) return "MATTER"; if (/converge|merge|synthesize|rejoin/i.test(s)) return "CONVERGENCE"; return "FIELD"; }
function scope(scope: AnyObj = {}): AnyObj { const raw = String(scope.type || "").toUpperCase(), type = ["BODY", "ORGAN", "BRANCH", "CELL"].includes(raw) ? raw : "BODY"; return { type, domain: Math.max(0, Math.min(11, Math.trunc(num(scope.domain)))), phase: Math.max(0, Math.min(11, Math.trunc(num(scope.phase)))), regulation: Math.max(0, Math.min(11, Math.trunc(num(scope.regulation)))) }; }
function scopeIndices(s: AnyObj): number[] { if (s.type === "BODY") return Array.from({ length: SWARM_CELL_COUNT }, (_, i) => i); const out: number[] = []; if (s.type === "ORGAN") { for (let p = 0; p < 12; p++) for (let r = 0; r < 12; r++) out.push(cellIndex(s.domain, p, r)); return out; } if (s.type === "BRANCH") { for (let r = 0; r < 12; r++) out.push(cellIndex(s.domain, s.phase, r)); return out; } return [cellIndex(s.domain, s.phase, s.regulation)]; }
function reorder(indices: number[], projection: string, seed: number): number[] { const pref = DOMAIN_PREFERENCE[projection] || DOMAIN_PREFERENCE.FIELD, rank = new Map(pref.map((d, i) => [d, i])), noise = (i: number) => (stableSeed(`${seed}|${i}`) % 1000) / 100000; return [...indices].sort((a, b) => { const da = Math.floor(a / 144), db = Math.floor(b / 144), ra = rank.has(da) ? rank.get(da)! : 99, rb = rank.has(db) ? rank.get(db)! : 99; return ra - rb + noise(a) - noise(b) || a - b; }); }
function executor(cell: AnyObj, budget: AnyObj): string { if (cell.profile.domainRole === "ORCHESTRATION" && cell.profile.phaseRole === "FRAME" && budget.genesis > 0) { budget.genesis--; return "GENESIS"; } if (cell.profile.domainRole === "PHYSICS" && cell.profile.phaseRole === "EXECUTE" && budget.optical > 0) { budget.optical--; return "OPTICAL_CHAIN"; } if (cell.providerEligible && budget.ai > 0) { budget.ai--; return "WORKERS_AI"; } return "DETERMINISTIC"; }
function buildCapsule(intent: string, projection: string): AnyObj | null { return projection === "BUILD" ? { schema: "OMEGA_SELF_BUILD_CAPSULE_R125", title: clip(intent, 120), objective: clip(intent, 1600), target: "repository/runtime candidate", risk: "MEDIUM", operation: "INTEGRATE_RUNTIME", preserves: ["CANONICAL_AUTHORITY", "TRUTH_BOUNDARIES", "ROLLBACK_LINEAGE", "INHERITED_GATES"], tests: ["FOCUSED_INVARIANTS", "FULL_RUNTIME_TESTS", "TYPECHECK", "CLOUDFLARE_CONTRACT", "PUBLIC_PROOF"], status: "PROPOSED_NOT_EXECUTED", authority: "SELF_BUILD_CANDIDATE_NOT_ADMITTED" } : null; }

export function planAutonomicMission(input: AnyObj = {}): AnyObj {
  const intent = clip(input.intent || input.text); if (!intent) throw new Error("INTENT_REQUIRED");
  const metrics = normalizeMetrics(input.metrics), decision = decide(metrics), projectionRaw = String(input.projection || "").toUpperCase(), projection = PROJECTIONS.includes(projectionRaw) ? projectionRaw : inferProjection(intent), targetScope = scope(input.scope), available = scopeIndices(targetScope), seed = stableSeed(`${intent}|${projection}|${JSON.stringify(targetScope)}|${input.seed ?? ""}`), ordered = reorder(available, projection, seed), mode = String(input.mode || "AUTO").toUpperCase();
  let count: number; if (MODE_COUNT[mode]) count = Math.min(ordered.length, MODE_COUNT[mode]); else if (input.requestedCells != null) count = Math.max(1, Math.min(ordered.length, Math.trunc(num(input.requestedCells, 1)))); else if (targetScope.type !== "BODY") count = ordered.length; else count = decision === "STAY" ? Math.min(24, ordered.length) : decision === "TURN" ? Math.min(144, ordered.length) : Math.min(input.allowFullAuto === true ? 1728 : 288, ordered.length);
  const picked = ordered.slice(0, count), defaultBudget = projection === "PROOF" ? decision === "STAY" ? 2 : decision === "TURN" ? 4 : 6 : projection === "BUILD" ? decision === "STAY" ? 2 : decision === "TURN" ? 5 : 8 : decision === "STAY" ? 2 : decision === "TURN" ? 6 : 10, totalBudget = Math.max(0, Math.min(12, Math.trunc(num(input.providerBudget, defaultBudget)))), reconverge = input.reconvergeWithAI !== false && totalBudget > 0, cellAi = Math.max(0, totalBudget - (reconverge ? 1 : 0)), budget = { ai: cellAi, genesis: Math.max(0, Math.min(2, Math.trunc(num(input.genesisBudget, projection === "BUILD" || projection === "CONVERGENCE" ? 1 : 0)))), optical: Math.max(0, Math.min(2, Math.trunc(num(input.opticalBudget, projection === "OPTICAL" ? 1 : 0)))) }, cells = picked.map((index, order) => { const address = decodeCell(index), profile = capabilityProfile(address), cell = { order, index, id: profile.cellId, address, profile, providerEligible: order < cellAi + 4, lane: laneIndex(address, (seed + order) % 12) }; return { ...cell, executor: executor(cell, budget) }; }), branchMap = new Map<string, AnyObj>();
  for (const cell of cells) { const key = `${cell.address.domain}:${cell.address.phase}`; if (!branchMap.has(key)) branchMap.set(key, { key, domain: cell.address.domain, phase: cell.address.phase, organ: SWARM_DOMAIN_ROLES[cell.address.domain], cells: [] }); branchMap.get(key)!.cells.push(cell); }
  const branches = [...branchMap.values()].sort((a, b) => a.domain - b.domain || a.phase - b.phase), branchConcurrency = Math.max(1, Math.min(12, Math.trunc(num(input.branchConcurrency, Math.round(2 + (1 - metrics.burden) * 6 + (decision === "ESCALATE" ? 2 : 0))))));
  return { schema: "OMEGA_AUTONOMIC_PLAN_R125", runtimeRevision: AUTONOMIC_REVISION, recoveryRevision: "R169", intent, projection, decision, metrics, scope: targetScope, detached: targetScope.type !== "BODY", seed, cells, branches, totalCells: cells.length, totalBranches: branches.length, branchConcurrency, deadlineMs: Math.max(30000, Math.min(1800000, Math.trunc(num(input.deadlineMs, 900000)))), maxDeterministicRetries: Math.max(0, Math.min(2, Math.trunc(num(input.maxDeterministicRetries, 1)))), evidence: evidence(input.evidence), budgets: { providerTotal: totalBudget, providerCells: cellAi, reconvergence: reconverge ? 1 : 0, genesis: Math.max(0, Math.min(2, Math.trunc(num(input.genesisBudget, projection === "BUILD" || projection === "CONVERGENCE" ? 1 : 0)))), optical: Math.max(0, Math.min(2, Math.trunc(num(input.opticalBudget, projection === "OPTICAL" ? 1 : 0)))) }, buildCapsule: buildCapsule(intent, projection), hierarchy: { seed: 1, organs: 12, branches: 144, cells: SWARM_CELL_COUNT, lanes: SWARM_LANE_COUNT }, continuityLaw: CONTINUITY_LAW, authority: "AUTONOMIC_RESULT_FABRIC_NOT_CANON", truthBoundary: `${TRUTH_BOUNDARY} Explicit FULL is required for automatic use of all 1,728 cells unless allowFullAuto=true.` };
}

export class OmegaSwarmAutonomicCoordinator {
  private storage: any; private env: SwarmEnv;
  constructor(state: any, env: SwarmEnv) { this.storage = state.storage; this.env = env; }
  private async ids(): Promise<string[]> { return (await this.storage.get("ids")) || []; }
  private async get(id: string): Promise<AnyObj | null> { return await this.storage.get(`m:${id}`) || null; }
  private async save(m: AnyObj): Promise<AnyObj> { await this.storage.put(`m:${m.id}`, m); const ids = await this.ids(); if (!ids.includes(m.id)) await this.storage.put("ids", [m.id, ...ids].slice(0, 64)); return m; }
  private async create(body: AnyObj): Promise<AnyObj> { const plan = planAutonomicMission(body), id = `auto_${Date.now().toString(36)}_${(await sha(`${plan.seed}|${Date.now()}`)).slice(0, 10)}`, now = Date.now(), m: AnyObj = { schema: "OMEGA_AUTONOMIC_MISSION_R125", runtimeRevision: AUTONOMIC_REVISION, recoveryRevision: "R169", id, status: "QUEUED", intent: plan.intent, projection: plan.projection, decision: plan.decision, metrics: plan.metrics, scope: plan.scope, detached: plan.detached, createdAt: now, deadlineAt: now + plan.deadlineMs, totalCells: plan.totalCells, totalBranches: plan.totalBranches, completedCells: 0, failedCells: 0, completedBranches: 0, failedBranches: 0, queue: plan.branches, branchConcurrency: plan.branchConcurrency, maxDeterministicRetries: plan.maxDeterministicRetries, evidence: plan.evidence, budgets: plan.budgets, buildCapsule: plan.buildCapsule, branchReceipts: [], providerContributions: [], proofState: "QUEUED_NOT_ADMITTED", canonicalMutation: false }; await this.save(m); await schedule(this.storage, 80); return { m, plan }; }
  private async runBranch(m: AnyObj, b: AnyObj): Promise<AnyObj> { const binding = this.env.OMEGA_SWARM_ORGAN as DurableBinding | undefined; if (!binding) return { ok: false, branch: b, data: { code: "ORGAN_BINDING_UNAVAILABLE" } }; const stub = binding.get(binding.idFromName(`omega-swarm-organ-${b.domain}`)), response = await stub.fetch(new Request("https://organ.internal/branch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ missionId: m.id, intent: m.intent, mode: "AUTONOMIC", domain: b.domain, phase: b.phase, cells: b.cells, evidence: m.evidence, maxDeterministicRetries: m.maxDeterministicRetries, lineage: [`omega-v6:autonomic:${m.id}`, `scope:${m.scope.type}`, `projection:${m.projection}`, `decision:${m.decision}`] }) })); return { ok: response.ok, branch: b, status: response.status, data: await response.json().catch(() => null) }; }
  private async finalize(m: AnyObj): Promise<AnyObj> { m.status = m.completedCells ? "COMPLETE" : "FAILED"; m.completedAt = Date.now(); m.proofState = "RETURNED_NOT_ADMITTED"; m.merkleRoot = await merkle(m.branchReceipts.map((x: AnyObj) => x.merkleRoot)); m.quorum = { schema: "OMEGA_EXECUTION_QUORUM_R125", cellSuccess: m.totalCells ? m.completedCells / m.totalCells : 0, branchSuccess: m.totalBranches ? m.completedBranches / m.totalBranches : 0, evidenceHashCoverage: m.evidence.length ? m.evidence.filter((x: AnyObj) => x.sha256).length / m.evidence.length : 0, authority: "EXECUTION_QUORUM_NOT_TRUTH" }; m.receipt = { schema: "OMEGA_AUTONOMIC_RECEIPT_R125", missionId: m.id, scope: m.scope, detached: m.detached, projection: m.projection, decision: m.decision, totalCells: m.totalCells, completedCells: m.completedCells, failedCells: m.failedCells, totalBranches: m.totalBranches, completedBranches: m.completedBranches, failedBranches: m.failedBranches, merkleRoot: m.merkleRoot, quorum: m.quorum, createdAt: m.createdAt, completedAt: m.completedAt, buildCapsule: m.buildCapsule, canonicalMutation: false, authority: "AUTONOMIC_RECEIPT_NOT_CANON" }; m.checkpointSha256 = await sha(m.receipt); return this.save(m); }
  private async process(id: string): Promise<AnyObj | null> { let m = await this.get(id); if (!m || !["QUEUED", "RUNNING"].includes(m.status)) return m; if (Date.now() > m.deadlineAt) { m.status = "TIMED_OUT"; m.completedAt = Date.now(); m.proofState = "TIMED_OUT_NOT_ADMITTED"; return this.save(m); } if (!m.queue.length) return this.finalize(m); m.status = "RUNNING"; m.startedAt = m.startedAt || Date.now(); const count = Math.min(m.branchConcurrency, m.queue.length), batch = m.queue.splice(0, count); await this.save(m); const outs = await Promise.all(batch.map((b: AnyObj) => this.runBranch(m as AnyObj, b).catch(error => ({ ok: false, branch: b, status: 500, data: { error: error instanceof Error ? error.message : String(error) } })))); for (const x of outs) { const receipt = x.data?.branch?.receipt || x.data?.receipt, cells = num(receipt?.cells, x.branch.cells.length), completed = num(receipt?.completed), failed = num(receipt?.failed, cells - completed); m.completedCells += completed; m.failedCells += failed; m.completedBranches += x.ok ? 1 : 0; m.failedBranches += x.ok ? 0 : 1; if (receipt) m.branchReceipts.push(receipt); const c = x.data?.branch?.contributions || x.data?.contributions; if (Array.isArray(c)) m.providerContributions.push(...c); m.providerContributions = m.providerContributions.slice(0, 24); } if (m.queue.length) { await this.save(m); await schedule(this.storage, 250); return m; } return this.finalize(m); }
  async alarm(): Promise<void> { for (const id of (await this.ids()).slice(0, 8)) { const m = await this.get(id); if (m && ["QUEUED", "RUNNING"].includes(m.status)) { await this.process(id); break; } } }
  async fetch(request: Request): Promise<Response> { const url = new URL(request.url), parts = url.pathname.split("/").filter(Boolean); if (request.method === "GET" && url.pathname === "/manifest") return jsonResponse({ ok: true, schema: "OMEGA_AUTONOMIC_MANIFEST_R125", runtimeRevision: AUTONOMIC_REVISION, recoveryRevision: "R169", sourceCommit: SWARM_SOURCE_COMMIT, projections: PROJECTIONS, hierarchy: { seed: 1, organs: 12, branches: 144, cells: SWARM_CELL_COUNT, lanes: SWARM_LANE_COUNT }, continuityLaw: CONTINUITY_LAW, truthBoundary: TRUTH_BOUNDARY, canonicalMutation: false }); if (request.method === "GET" && url.pathname === "/status") { const missions: AnyObj[] = []; for (const id of (await this.ids()).slice(0, 12)) { const m = await this.get(id); if (m) missions.push(publicMission(m) as AnyObj); } return jsonResponse({ ok: true, schema: "OMEGA_AUTONOMIC_STATUS_R125", runtimeRevision: AUTONOMIC_REVISION, recoveryRevision: "R169", active: missions.filter(x => ["QUEUED", "RUNNING"].includes(x.status)).length, missions, canonicalMutation: false }); } if (request.method === "POST" && url.pathname === "/plan") { try { return jsonResponse({ ok: true, plan: planAutonomicMission(await request.json().catch(() => ({})) as AnyObj) }); } catch (error) { return jsonResponse({ ok: false, code: error instanceof Error ? error.message : "PLAN_INVALID" }, 400); } } if (request.method === "POST" && url.pathname === "/missions") { try { const { m, plan } = await this.create(await request.json().catch(() => ({})) as AnyObj); return jsonResponse({ ok: true, mission: publicMission(m), plan: { schema: plan.schema, projection: plan.projection, decision: plan.decision, scope: plan.scope, totalCells: plan.totalCells, totalBranches: plan.totalBranches, buildCapsule: plan.buildCapsule, hierarchy: plan.hierarchy, truthBoundary: plan.truthBoundary } }, 202); } catch (error) { return jsonResponse({ ok: false, code: error instanceof Error ? error.message : "MISSION_INVALID" }, 400); } } if (parts[0] === "missions" && parts[1]) { const id = parts[1]; if (request.method === "GET" && parts.length === 2) { const m = await this.get(id); return jsonResponse({ ok: Boolean(m), mission: publicMission(m) }, m ? 200 : 404); } if (request.method === "POST" && parts[2] === "tick") { const m = await this.process(id); return jsonResponse({ ok: Boolean(m), mission: publicMission(m) }, m ? 200 : 404); } } return jsonResponse({ ok: false, code: "NOT_FOUND" }, 404); }
}
