import { AnyObj, DurableBinding, SwarmEnv, ORGANISM_REVISION, SWARM_CELL_COUNT, SWARM_DOMAIN_ROLES, SWARM_LANE_COUNT, branchKey, clip, evidence, jsonResponse, merkle, num, planMission, publicMission, schedule, sha } from "./swarmCoreR169";

function executorForPlan(cell: AnyObj, budget: AnyObj): string {
  if (cell.profile.domainRole === "ORCHESTRATION" && cell.profile.phaseRole === "FRAME" && budget.genesis > 0) { budget.genesis--; return "GENESIS"; }
  if (cell.profile.domainRole === "PHYSICS" && cell.profile.phaseRole === "EXECUTE" && budget.optical > 0) { budget.optical--; return "OPTICAL_CHAIN"; }
  if (cell.providerEligible && budget.ai > 0) { budget.ai--; return "WORKERS_AI"; }
  return "DETERMINISTIC";
}

export class OmegaSwarmBranch {
  private storage: any; private env: SwarmEnv;
  constructor(state: any, env: SwarmEnv) { this.storage = state.storage; this.env = env; }
  async fetch(request: Request): Promise<Response> {
    if (request.method === "GET") return jsonResponse({ ok: true, state: (await this.storage.get("state")) || { status: "IDLE", runs: 0, failures: 0 } });
    if (request.method !== "POST") return jsonResponse({ ok: false, code: "METHOD_NOT_ALLOWED" }, 405);
    const job = await request.json().catch(() => ({})) as AnyObj, cells = Array.isArray(job.cells) ? job.cells.slice(0, 12) : [], startedAt = Date.now(), previous = (await this.storage.get("state")) || { runs: 0, failures: 0 }, binding = this.env.OMEGA_SWARM_CELL as DurableBinding | undefined;
    if (!binding) return jsonResponse({ ok: false, code: "CELL_BINDING_UNAVAILABLE" }, 503);
    await this.storage.put("state", { ...previous, status: "WORKING", missionId: job.missionId, domain: job.domain, phase: job.phase, startedAt });
    const results: AnyObj[] = [];
    for (const cell of cells) {
      const run = async () => { const stub = binding.get(binding.idFromName(cell.id)), task = { schema: "OMEGA_ORGANISM_CELL_TASK_R123", missionId: job.missionId, taskId: `${job.missionId}:${cell.index}`, cellId: cell.id, index: cell.index, lane: cell.lane, intent: job.intent, mode: job.mode, executor: cell.executor || "DETERMINISTIC", evidence: job.evidence || [], lineage: [...(job.lineage || []), `branch:${branchKey(job.domain, job.phase)}`, `cell:${cell.id}`] }, response = await stub.fetch(new Request("https://swarm-cell.internal/task", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(task) })); return { cell, ok: response.ok, status: response.status, data: await response.json().catch(() => null) }; };
      let out = await run(); if (!out.ok && cell.executor === "DETERMINISTIC" && num(job.maxDeterministicRetries) > 0) for (let retry = 0; retry < job.maxDeterministicRetries && !out.ok; retry++) out = await run(); results.push(out);
    }
    const completed = results.filter(x => x.ok).length, failed = results.length - completed, root = await merkle(results.map(x => x.data?.receipt?.resultSha256).filter(Boolean)), contributions = results.filter(x => x.ok && x.cell.executor === "WORKERS_AI").map(x => ({ cellId: x.cell.id, role: x.cell.profile?.domainRole, summary: clip(x.data?.result?.summary, 1400) })).filter(x => x.summary), finishedAt = Date.now(), receipt = { schema: "OMEGA_BRANCH_RECEIPT_R123", missionId: job.missionId, branch: branchKey(job.domain, job.phase), domain: job.domain, phase: job.phase, cells: results.length, completed, failed, merkleRoot: root, startedAt, finishedAt, runtimeMs: finishedAt - startedAt, canonicalMutation: false };
    await this.storage.put("state", { status: failed ? "DEGRADED" : "IDLE", missionId: job.missionId, domain: job.domain, phase: job.phase, runs: num(previous.runs) + 1, failures: num(previous.failures) + failed, lastReceipt: receipt, heartbeatAt: finishedAt });
    return jsonResponse({ ok: completed > 0 || !results.length, receipt, results: results.map(x => ({ cellId: x.cell.id, index: x.cell.index, executor: x.cell.executor, ok: x.ok, status: x.status, receiptSha: x.data?.receipt?.resultSha256 || null, summary: clip(x.data?.result?.summary || x.data?.result?.truthBoundary || x.data?.error || x.data?.code, 900) })), contributions }, failed ? 207 : 200);
  }
}

export class OmegaSwarmOrgan {
  private storage: any; private env: SwarmEnv;
  constructor(state: any, env: SwarmEnv) { this.storage = state.storage; this.env = env; }
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === "GET") return jsonResponse({ ok: true, state: (await this.storage.get("state")) || { status: "IDLE", branchRuns: 0, cellRuns: 0, failures: 0 } });
    if (request.method !== "POST" || url.pathname !== "/branch") return jsonResponse({ ok: false, code: "NOT_FOUND" }, 404);
    const job = await request.json().catch(() => ({})) as AnyObj, binding = this.env.OMEGA_SWARM_BRANCH as DurableBinding | undefined;
    if (!binding) return jsonResponse({ ok: false, code: "BRANCH_BINDING_UNAVAILABLE" }, 503);
    const prev = (await this.storage.get("state")) || { branchRuns: 0, cellRuns: 0, failures: 0 }, stub = binding.get(binding.idFromName(`omega-swarm-branch-${job.domain}-${job.phase}`)), started = Date.now();
    await this.storage.put("state", { ...prev, status: "WORKING", domain: job.domain, missionId: job.missionId, heartbeatAt: started });
    const response = await stub.fetch(new Request("https://branch.internal/run", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...job, lineage: [...(job.lineage || []), `organ:${SWARM_DOMAIN_ROLES[job.domain] || job.domain}`] }) })), data = await response.json().catch(() => null) as AnyObj | null, failed = num(data?.receipt?.failed), next = { status: response.ok && failed === 0 ? "IDLE" : "DEGRADED", domain: job.domain, missionId: job.missionId, branchRuns: num(prev.branchRuns) + 1, cellRuns: num(prev.cellRuns) + num(data?.receipt?.cells), failures: num(prev.failures) + failed, heartbeatAt: Date.now(), lastBranchReceipt: data?.receipt || null };
    await this.storage.put("state", next); return jsonResponse({ ok: response.ok, organ: { domain: job.domain, role: SWARM_DOMAIN_ROLES[job.domain], state: next }, branch: data }, response.status);
  }
}

export function planOrganismMission(input: AnyObj = {}): AnyObj {
  const totalProviderBudget = Math.max(0, Math.min(12, Math.trunc(num(input.providerBudget, 6)))), reconvergeWithAI = input.reconvergeWithAI !== false && totalProviderBudget > 0, cellAiBudget = Math.max(0, totalProviderBudget - (reconvergeWithAI ? 1 : 0)), base = planMission({ ...input, providerBudget: cellAiBudget }), budgets = { ai: cellAiBudget, genesis: Math.max(0, Math.min(2, Math.trunc(num(input.genesisBudget, 1)))), optical: Math.max(0, Math.min(2, Math.trunc(num(input.opticalBudget, 1)))) }, branchMap = new Map<string, AnyObj>();
  for (const cell of base.selected) { const key = branchKey(cell.address.domain, cell.address.phase), copy = { ...cell, executor: executorForPlan(cell, budgets) }; if (!branchMap.has(key)) branchMap.set(key, { key, domain: cell.address.domain, phase: cell.address.phase, organ: cell.profile.domainRole, cells: [] }); branchMap.get(key)!.cells.push(copy); }
  const branches = [...branchMap.values()].sort((a, b) => a.domain - b.domain || a.phase - b.phase);
  return { ...base, schema: "OMEGA_ORGANISM_PLAN_R123", runtimeRevision: ORGANISM_REVISION, totalProviderBudget, reconvergeWithAI, cellAiBudget, evidence: evidence(input.evidence), branches, branchCount: branches.length, organBranchCounts: Array.from({ length: 12 }, (_, d) => branches.filter(b => b.domain === d).length), budgets: { providerTotal: totalProviderBudget, providerCells: cellAiBudget, reconvergence: reconvergeWithAI ? 1 : 0, genesis: Math.max(0, Math.min(2, Math.trunc(num(input.genesisBudget, 1)))), optical: Math.max(0, Math.min(2, Math.trunc(num(input.opticalBudget, 1)))) }, deadlineMs: Math.max(30000, Math.min(1800000, Math.trunc(num(input.deadlineMs, 900000)))), branchConcurrency: Math.max(1, Math.min(12, Math.trunc(num(input.branchConcurrency, base.mode === "PIPELINE" ? 1 : 4)))), maxDeterministicRetries: Math.max(0, Math.min(2, Math.trunc(num(input.maxDeterministicRetries, 1)))), authority: "RESULT_FABRIC_NOT_CANON" };
}

export class OmegaSwarmOrganismCoordinator {
  private storage: any; private env: SwarmEnv;
  constructor(state: any, env: SwarmEnv) { this.storage = state.storage; this.env = env; }
  private async ids(): Promise<string[]> { return (await this.storage.get("mission_ids")) || []; }
  private async get(id: string): Promise<AnyObj | null> { return await this.storage.get(`mission:${id}`) || null; }
  private async save(m: AnyObj): Promise<AnyObj> { await this.storage.put(`mission:${m.id}`, m); const ids = await this.ids(); if (!ids.includes(m.id)) await this.storage.put("mission_ids", [m.id, ...ids].slice(0, 64)); return m; }
  private async create(body: AnyObj): Promise<AnyObj> { const plan = planOrganismMission(body), id = `organism_${Date.now().toString(36)}_${(await sha(`${plan.intent}|${plan.seed}|${Date.now()}`)).slice(0, 12)}`, now = Date.now(), m: AnyObj = { schema: "OMEGA_ORGANISM_MISSION_R123", runtimeRevision: ORGANISM_REVISION, id, status: "QUEUED", mode: plan.mode, intent: plan.intent, seed: plan.seed, createdAt: now, deadlineAt: now + plan.deadlineMs, totalCells: plan.selected.length, totalBranches: plan.branches.length, completedCells: 0, failedCells: 0, completedBranches: 0, failedBranches: 0, queue: plan.branches.map((b: AnyObj) => ({ ...b })), activeBranches: 0, branchConcurrency: plan.branchConcurrency, maxDeterministicRetries: plan.maxDeterministicRetries, evidence: plan.evidence, budgets: plan.budgets, providerContributions: [], branchReceipts: [], organ: { target: plan.organBranchCounts, completed: Array(12).fill(0), failed: Array(12).fill(0) }, proofState: "QUEUED_NOT_ADMITTED", authority: "RESULT_FABRIC_NOT_CANON", canonicalMutation: false }; await this.save(m); await schedule(this.storage, 75); return { m, plan }; }
  private async runBranch(m: AnyObj, b: AnyObj): Promise<AnyObj> { const binding = this.env.OMEGA_SWARM_ORGAN as DurableBinding | undefined; if (!binding) return { ok: false, branch: b, data: { code: "ORGAN_BINDING_UNAVAILABLE" } }; const stub = binding.get(binding.idFromName(`omega-swarm-organ-${b.domain}`)), response = await stub.fetch(new Request("https://organ.internal/branch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ missionId: m.id, intent: m.intent, mode: m.mode, domain: b.domain, phase: b.phase, cells: b.cells, evidence: m.evidence, maxDeterministicRetries: m.maxDeterministicRetries, lineage: [`omega-v6:organism:${m.id}`, `seed:${m.seed}`] }) })); return { ok: response.ok, branch: b, status: response.status, data: await response.json().catch(() => null) }; }
  private async finalize(m: AnyObj): Promise<AnyObj> { m.status = m.completedCells ? "COMPLETE" : "FAILED"; m.completedAt = Date.now(); m.proofState = "RETURNED_NOT_ADMITTED"; m.merkleRoot = await merkle(m.branchReceipts.map((x: AnyObj) => x.merkleRoot)); m.receipt = { schema: "OMEGA_ORGANISM_RECEIPT_R123", missionId: m.id, mode: m.mode, totalCells: m.totalCells, completedCells: m.completedCells, failedCells: m.failedCells, totalBranches: m.totalBranches, completedBranches: m.completedBranches, failedBranches: m.failedBranches, merkleRoot: m.merkleRoot, evidence: m.evidence.map((x: AnyObj) => ({ id: x.id, sha256: x.sha256, authority: x.authority })), budgets: m.budgets, createdAt: m.createdAt, completedAt: m.completedAt, canonicalMutation: false, authority: "RESULT_RECEIPT_NOT_CANON" }; return this.save(m); }
  private async process(id: string): Promise<AnyObj | null> { let m = await this.get(id); if (!m || !["QUEUED", "RUNNING"].includes(m.status)) return m; if (Date.now() > m.deadlineAt) { m.status = "TIMED_OUT"; m.completedAt = Date.now(); m.proofState = "TIMED_OUT_NOT_ADMITTED"; return this.save(m); } if (!m.queue.length) return this.finalize(m); m.status = "RUNNING"; m.startedAt = m.startedAt || Date.now(); const count = m.mode === "PIPELINE" ? 1 : Math.min(m.branchConcurrency, m.queue.length), batch = m.queue.splice(0, count); m.activeBranches = batch.length; await this.save(m); const outs = await Promise.all(batch.map((b: AnyObj) => this.runBranch(m as AnyObj, b).catch(error => ({ ok: false, branch: b, status: 500, data: { error: error instanceof Error ? error.message : String(error) } })))); for (const x of outs) { const receipt = x.data?.branch?.receipt || x.data?.receipt, cells = num(receipt?.cells, x.branch.cells.length), completed = num(receipt?.completed), failed = num(receipt?.failed, cells - completed); m.completedCells += completed; m.failedCells += failed; m.completedBranches += x.ok ? 1 : 0; m.failedBranches += x.ok ? 0 : 1; m.organ.completed[x.branch.domain] += x.ok ? 1 : 0; m.organ.failed[x.branch.domain] += x.ok ? 0 : 1; if (receipt) m.branchReceipts.push({ ...receipt, organ: SWARM_DOMAIN_ROLES[x.branch.domain] }); const c = x.data?.branch?.contributions || x.data?.contributions; if (Array.isArray(c)) m.providerContributions.push(...c); m.providerContributions = m.providerContributions.slice(0, 24); } m.activeBranches = 0; if (m.queue.length) { await this.save(m); await schedule(this.storage, 250); return m; } return this.finalize(m); }
  async alarm(): Promise<void> { for (const id of (await this.ids()).slice(0, 8)) { const m = await this.get(id); if (m && ["QUEUED", "RUNNING"].includes(m.status)) { await this.process(id); break; } } }
  async fetch(request: Request): Promise<Response> { const url = new URL(request.url), parts = url.pathname.split("/").filter(Boolean); if (request.method === "GET" && url.pathname === "/status") { const missions: AnyObj[] = []; for (const id of (await this.ids()).slice(0, 12)) { const m = await this.get(id); if (m) missions.push(publicMission(m) as AnyObj); } return jsonResponse({ ok: true, schema: "OMEGA_ORGANISM_STATUS_R123", runtimeRevision: ORGANISM_REVISION, recoveryRevision: "R169", hierarchy: { seed: 1, organs: 12, branches: 144, cells: SWARM_CELL_COUNT, lanes: SWARM_LANE_COUNT }, missions, canonicalMutation: false }); } if (request.method === "POST" && url.pathname === "/plan") { try { return jsonResponse({ ok: true, plan: planOrganismMission(await request.json().catch(() => ({})) as AnyObj) }); } catch (error) { return jsonResponse({ ok: false, code: error instanceof Error ? error.message : "PLAN_INVALID" }, 400); } } if (request.method === "POST" && url.pathname === "/missions") { try { const { m, plan } = await this.create(await request.json().catch(() => ({})) as AnyObj); return jsonResponse({ ok: true, mission: publicMission(m), plan: { schema: plan.schema, mode: plan.mode, totalCells: plan.selected.length, totalBranches: plan.branches.length, hierarchy: plan.hierarchy, truthBoundary: plan.truthBoundary } }, 202); } catch (error) { return jsonResponse({ ok: false, code: error instanceof Error ? error.message : "MISSION_INVALID" }, 400); } } if (parts[0] === "missions" && parts[1]) { const id = parts[1]; if (request.method === "GET" && parts.length === 2) { const m = await this.get(id); return jsonResponse({ ok: Boolean(m), mission: publicMission(m) }, m ? 200 : 404); } if (request.method === "POST" && parts[2] === "tick") { const m = await this.process(id); return jsonResponse({ ok: Boolean(m), mission: publicMission(m) }, m ? 200 : 404); } } return jsonResponse({ ok: false, code: "NOT_FOUND" }, 404); }
}
