const views=[
 ['overview','Command Overview','State, proof, motion and source authority in one instrument.'],
 ['runtime','01 Runtime Core','The only canonical state owner.'],['proof','02 Proof & Governance','Admission, replay, evidence and immutable receipts.'],
 ['traversal','03 Traversal','Addressable state motion and Dewey / RSC calculus.'],['render','04 Render Field','One projection packet; no decorative authority.'],
 ['host','05 Host Inputs','Evidence-classed adapters into the runtime.'],['ai','06 AI Orchestration','Human-governed planning, modes and translation.'],
 ['data','07 Data / Excel Atlas','Provenance-aware corpus and atlas control.'],['audio','08 Audio / Signal','Derived sonification with bounded claims.'],
 ['world','09 World / Bio / Forecast','Source-bound world traversal and frozen-prior forecast.'],['recovery','10–12 Recovery / Merge / Cockpit','Packaging, donor governance and operator control.'],
 ['plugins','Plugin Runtime','Bounded capabilities and mutation leases.']
];
const $=id=>document.getElementById(id); const fmt=(v,n=4)=>Number(v).toFixed(n); const json=x=>JSON.stringify(x,null,2);
$('nav').innerHTML=views.map((v,i)=>`<button class="${i?'':'active'}" data-view="${v[0]}"><i></i>${v[1]}</button>`).join('');
$('phaseDots').innerHTML=Array.from({length:12},(_,i)=>`<i data-p="${i+1}" style="--i:${i}"></i>`).join('');
$('nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===b.dataset.view));const m=views.find(v=>v[0]===b.dataset.view);$('viewTitle').textContent=m[1];$('viewSub').textContent=m[2];document.querySelector('.sidebar').classList.remove('open')};
$('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
async function api(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});const d=await r.json();if(!r.ok)throw d;return d}
let SNAP=null;
function metric(k,v,cls=''){return `<div class="metric"><small>${k}</small><strong class="${cls}">${v}</strong></div>`}
function renderSnap(d){SNAP=d;const s=d.state,m=s.metrics,c=d.calculus,p=d.projection;$('runtimeStatus').textContent='RUNTIME LIVE';$('sideDigest').textContent=s.digest.slice(0,18)+'…';$('sideEvidence').textContent=s.evidence_class;$('stateChip').textContent='STATE '+s.state_id;$('proofChip').textContent=d.proof.valid?'PROOF PASS':'PROOF FAIL';$('coreState').textContent='STATE '+s.state_id;$('corePhase').textContent='P'+String(s.address[1]).padStart(2,'0');document.querySelectorAll('.phase-dots i').forEach(x=>x.classList.toggle('active',Number(x.dataset.p)===s.address[1]));$('projectionFingerprint').textContent=p.packet_fingerprint.slice(0,24)+'…';$('metrics').innerHTML=metric('CΩ continuity',fmt(m.continuity),'green')+metric('Φ plasticity',fmt(m.future_plasticity),'teal')+metric('Λ burden',fmt(m.burden))+metric('q contradiction',fmt(m.contradiction),m.contradiction>m.continuity?'red':'')+metric('S stability',fmt(m.stability))+metric('scar',fmt(m.scar))+metric('evidence',fmt(m.evidence_strength))+metric('water',fmt(c.water));$('dispatch').textContent=c.mode188.dispatch;$('admission').textContent=c.mode188.admission;$('ratio').textContent=Number.isFinite(c.mode188.ratio)?fmt(c.mode188.ratio,3):'∞';$('lensBars').innerHTML=[['RSC capacity',Math.min(1,c.rsc.capacity/3)],['Deep Mother',c.deep_mother],['High Father',c.high_father],['Deep Thought',c.deep_thought]].map(([k,v])=>`<div class="lens"><span>${k}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,v*100))}%"></i></div><b>${fmt(v,2)}</b></div>`).join('');$('stateRaw').textContent=json(d);document.documentElement.style.setProperty('--field-pressure',Math.min(1,(m.burden+m.contradiction)/2));}
async function refresh(){try{renderSnap(await api('/api/state'));await proof()}catch(e){$('runtimeStatus').textContent='RUNTIME OFFLINE';console.error(e)}}
async function capabilities(){const d=await api('/api/capabilities');$('overviewCards').innerHTML=d.menus.slice(0,6).map(x=>`<article class="card mini-card"><small>${x[0]} MASTER SURFACE</small><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');$('gates').innerHTML=d.acceptance_gates.map((g,i)=>`<div><i></i><b>G${String(i+1).padStart(2,'0')}</b><span>${g}</span></div>`).join('')}
async function plugins(){const d=await api('/api/plugins');$('pluginRows').innerHTML=d.plugins.map(p=>`<tr><td><b>${p.name||p.id||p.path}</b><br><small>${p.version||''}</small></td><td>${p.status}</td><td>${(p.permissions||[]).join(', ')||'—'}</td><td>${(p.capabilities||[]).join(', ')||'—'}</td></tr>`).join('')||'<tr><td colspan="4">No plugins registered.</td></tr>'}
async function modes(){const d=await api('/api/modes');$('modeGrid').innerHTML=d.modes.map(m=>`<div class="mode" data-mode="${m.id}"><b>${m.name}</b><small>${m.purpose}</small></div>`).join('');$('modeGrid').onclick=async e=>{const m=e.target.closest('.mode');if(!m)return;const d=await api('/api/mode?id='+encodeURIComponent(m.dataset.mode));alert(m.dataset.mode+'\n\n'+json(d.result))}}
async function proof(){const d=await api('/api/proof');$('proofRows').innerHTML=d.records.slice().reverse().map(r=>`<tr><td>${r.sequence}</td><td>${r.kind}</td><td>${r.decision}</td><td><code>${r.state_before.slice(0,10)}</code></td><td><code>${r.state_after?r.state_after.slice(0,10):'—'}</code></td></tr>`).join('')||'<tr><td colspan="5">No mutations recorded yet.</td></tr>'}
async function post(url,body){return api(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}
document.body.onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{if(b.dataset.action==='refresh-proof')await proof();if(b.dataset.action==='refresh-plugins')await plugins();if(b.dataset.action==='run-plugin')$('pluginResult').textContent=json(await post('/api/plugins/run',{id:b.dataset.plugin,payload:{request:'self-test'}}));if(b.dataset.action==='atlas')$('atlasResult').textContent=json(await api('/api/atlas?index='+$('atlasIndex').value));if(b.dataset.action==='forecast')$('forecastResult').textContent=json(await api('/api/forecast?horizon='+$('horizon').value));if(b.dataset.action==='classify')$('classifyResult').textContent=json(await api('/api/corpus/classify?name='+encodeURIComponent($('corpusName').value)));if(b.dataset.action==='dewey')$('deweyResult').textContent=json(await post('/api/dewey-bal/validate',{source_state:11499,target_state:11687,source_burden:0.8000063837447882,target_burden:0.42901814817581707,edge:'MODE188+'}));if(b.dataset.action==='simulate'){const addr=SNAP.state.address;const body={address:addr,evidence_class:'DERIVED',mode:'MODE188',metrics:{continuity:+$('c').value,future_plasticity:+$('phi').value,burden:+$('lambda').value,contradiction:+$('q').value,stability:+$('stability').value,evidence_strength:+$('evidence').value,scar:SNAP.state.metrics.scar,water_conductance:SNAP.state.metrics.water_conductance,triangulation:SNAP.state.metrics.triangulation,occupancy:SNAP.state.metrics.occupancy,proof_scar:SNAP.state.metrics.proof_scar,normalized_mri:SNAP.state.metrics.normalized_mri}};$('simResult').textContent=json(await post('/api/transition',body));await refresh()}}catch(err){const el=$('simResult')||$('deweyResult');if(el)el.textContent=json(err)}};
refresh();capabilities();modes();plugins();setInterval(refresh,7000);
